'use client';
import {PortalSidebar} from '@/components/portal-sidebar';
import {SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,FileText,Plus,RefreshCw,Send,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {LiveState} from '@/lib/live-store';
import type {Recipient} from '@/lib/demo-store';
function stage(r:Recipient){return r.reviewedAt?'Reviewed':r.status==='Completed'?'Returned':r.delivery==='sent'?'Sent':r.delivery==='uncertain'||r.delivery==='sending'?'Check delivery':r.delivery==='failed'?'Send failed':r.delivery==='ready'?'Ready':'Draft'}
export default function Performance(){
 const [state,setState]=useState<LiveState|null>(null),[active,setActive]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[person,setPerson]=useState(''),[modalVersion,setModalVersion]=useState(''),[groups,setGroups]=useState<string[]>([]),[template,setTemplate]=useState(''),[requestId,setRequestId]=useState('');
 async function refresh(){try{const r=await fetch('/api/live');const data=await r.json() as LiveState & {error?:string};if(!r.ok)throw Error(data.error);setState(data)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void refresh()},[]);
 async function run(action:string,extra:Record<string,string>={},form?:FormData){setBusy(true);setError('');setNotice('');try{const f=form||new FormData();f.set('action',action);for(const [key,value] of Object.entries(extra))f.set(key,value);const result=await fetch(['sync','collect'].includes(action)?'/api/live':'/api/performance',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state?.workspaceRevision??0)},body:f});const data=await result.json() as LiveState & {error?:string};if(!result.ok)throw Error(data.error);setState(data);if(action==='create'){const created=data.assignments.find((a)=>a.requestId===requestId);if(created)setActive(created.id)}setModal('');setNotice(action==='send'?'Send attempted. Check the employee’s delivery status below.':action==='collect'?'Responses checked. Returned PDFs need your signature review.':action==='prepare'?'PDF prepared. Preview it, then mark it ready.':'Saved.');return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 const batches=state?.assignments.filter(a=>a.workflow==='performance')||[],batch=batches.find(a=>a.id===active),recipient=batch?.recipients.find(r=>r.id===person);
 const total=batch?.recipients.length||0;
 const prepared=batch?.recipients.filter(r=>!!r.preparedPdfId).length||0;
 const sent=batch?.recipients.filter(r=>r.delivery==='sent').length||0;
 const returned=batch?.recipients.filter(r=>r.status==='Completed').length||0;
 const unsent=batch?.recipients.filter(r=>r.preparedPdfId&&![ 'sent','sending','uncertain'].includes(r.delivery||'')).length||0;
 const unconfirmed=batch?.recipients.filter(r=>['sending','uncertain'].includes(r.delivery||'')).length||0;
 const templates=state?.documents.filter(d=>['DOC','DOCX'].includes(d.type)&&d.parentIds?.includes(state.folders?.templates||''))||[];
 const preview=(id:string,p:string,version?:string)=>`/api/performance?id=${encodeURIComponent(id)}&person=${encodeURIComponent(p)}&version=${encodeURIComponent(version||'')}`;
 const members=[...new Map((state?.groups||[]).filter(g=>groups.includes(g.id)).flatMap(g=>g.members).map(p=>[p.email.toLowerCase(),p])).values()];
 return <SidebarProvider><PortalSidebar active="performance" reviewCount={state?.reviews.filter(r=>!r.resolved).length||0}/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows</span><span>/</span><strong>Performance Review</strong></div><span className="demo-badge">LIVE GOOGLE</span></header><main className="performance-page"><div className="page-heading"><div><p className="eyebrow">WORKFLOWS</p><h1>Performance Review</h1><p>Prepare individual reviews, send PDFs and collect signed returns.</p></div><Button disabled={busy||!state} onClick={()=>{setGroups([]);setTemplate('');setRequestId(crypto.randomUUID());setModal('create')}}><Plus size={16}/>New review batch</Button></div>
 <div className="live-actions"><Button variant="outline" disabled={busy||!state} onClick={()=>void run('sync')}><RefreshCw size={16}/>Sync templates</Button><Button variant="outline" disabled={busy||!state} onClick={()=>setModal('upload')}>Upload Word template</Button><Button variant="outline" disabled={busy||!state} onClick={()=>void run('collect')}>Check signed returns</Button><a className="text-link" href="/google">Google connection</a></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="demo-notice" role="status">{notice}</p>}{state?.collectionError&&<p className="error">{state.collectionError}</p>}
 {!state?<div className="panel empty">{error?'Connect Google to use this workflow.':'Loading performance reviews…'}<a className="text-link" href="/google">Open Google connection</a></div>:!batch?<div className="assignment-list">{batches.map(a=><button className="panel assignment-card" key={a.id} onClick={()=>setActive(a.id)}><span className="file-icon"><FileText/></span><div><h2>{a.name}</h2><p>{a.recipients.length} employees · Due {a.due||'not set'}</p></div><div>{a.recipients.filter(r=>r.status==='Completed').length} returned · {a.recipients.filter(r=>r.reviewedAt).length} reviewed</div><ArrowUpRight size={18}/></button>)}{!batches.length&&<section className="panel empty"><FileText size={32}/><h2>Your first performance review</h2><p>Choose a Word or Google Docs template and an employee group. Each employee gets a separate editable copy.</p><p>Original template → Personal Google Doc → Prepared PDF → Signed return → Reviewed</p></section>}</div>:<>
 <Button variant="ghost" onClick={()=>setActive('')}><ArrowLeft size={16}/>All review batches</Button><div className="assignment-summary"><strong>{batch.name}</strong><span>Due {batch.due||'not set'}</span><span>{batch.recipients.filter(r=>r.reviewedAt).length}/{batch.recipients.length} reviewed</span>{batch.recipients.some(r=>!r.draftId)&&<Button disabled={busy} variant="outline" onClick={()=>void run('generate',{id:batch.id})}>Create missing drafts</Button>}</div>
 <section className="performance-progress" aria-label="Batch progress">{[
 {label:'PDFs prepared',count:prepared,note:`${total-prepared} still to prepare`,icon:FileText},
 {label:'PDFs sent',count:sent,note:`${total-sent} not confirmed sent`,icon:Send},
 {label:'Employee replies',count:returned,note:`${sent-returned>0?sent-returned:0} sent reviews awaiting a reply`,icon:Check}
 ].map(({label,count,note,icon:Icon})=><article className="panel performance-metric" key={label}><div className="metric-label"><span>{label}</span><Icon size={20}/></div><div className="metric-value"><strong>{count}</strong><span>/ {total}</span></div><progress aria-label={label} value={count} max={total||1}/><p>{note}</p></article>)}</section>
 {(unsent>0||unconfirmed>0)&&<div className="performance-send-reminder" role="status">{unsent>0&&<p><Send size={17}/><span><strong>{unsent} prepared PDF{unsent===1?'':'s'} still to send.</strong> Check the PDF, mark it Ready and use Review &amp; send below.</span></p>}{unconfirmed>0&&<p><RefreshCw size={17}/><span>{unconfirmed} delivery result{unconfirmed===1?' is':'s are'} unconfirmed. Use Check signed returns to reconcile Gmail before resending.</span></p>}</div>}
 <p className="performance-hint">Edit each copy in Google Docs and wait for it to save. Prepare a PDF, preview its contents, then mark it ready. If you edit again, prepare a new PDF. Received PDFs are marked Returned; check the signature before marking Reviewed.</p>
 <section className="panel"><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Status</TableHead><TableHead>Individual document</TableHead><TableHead>Signed return</TableHead></TableRow></TableHeader><TableBody>{batch.recipients.map(r=>{const locked=['sent','sending','uncertain'].includes(r.delivery||'');return <TableRow key={r.id}><TableCell><strong>{r.name}</strong><small className="block muted">{r.email}</small>{(r.preparationError||r.deliveryError)&&<p className="error">{r.preparationError||r.deliveryError}</p>}</TableCell><TableCell><span className={'status '+(r.reviewedAt?'completed':'pending')}>{stage(r)}</span>{r.preparedAt&&<small className="block muted">PDF: {new Date(r.preparedAt).toLocaleString()}</small>}</TableCell><TableCell><div className="performance-controls">{r.draftId&&<a className="text-link" target="_blank" rel="noreferrer" href={`https://docs.google.com/document/d/${r.draftId}/edit`}>{locked?'Open Google Doc':'Edit in Google Docs'} <ArrowUpRight size={14}/></a>}{!locked&&r.draftId&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void run('prepare',{id:batch.id,person:r.id})}>{r.preparedPdfId?'Prepare new PDF':'Prepare PDF'}</Button>}{r.preparedPdfId&&<a className="text-link" href={preview(batch.id,r.id,r.preparedPdfId)} target="_blank" rel="noreferrer">Preview {locked?'sent':'prepared'} PDF <ArrowUpRight size={14}/></a>}{!locked&&r.preparedPdfId&&<><Button size="sm" disabled={busy} variant="outline" onClick={()=>{setPerson(r.id);setModalVersion(r.preparedPdfId||'');setModal(r.delivery==='ready'||r.delivery==='failed'?'send':'ready')}}>{r.delivery==='ready'||r.delivery==='failed'?<><Send size={14}/>Review & send</>:'Mark ready'}</Button>{r.delivery==='ready'&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void run('draft',{id:batch.id,person:r.id})}>Return to draft</Button>}</>}{r.delivery==='uncertain'&&<span className="muted">Check signed returns to reconcile Gmail delivery. Do not resend manually.</span>}</div></TableCell><TableCell>{r.returnedUrl?<div className="performance-controls"><a className="text-link" href={r.returnedUrl} target="_blank" rel="noreferrer">Open returned PDF <ArrowUpRight size={14}/></a><small>{r.received?new Date(r.received).toLocaleString():''}</small>{r.reviewedAt?<span className="text-link"><Check size={14}/>Signature reviewed</span>:<Button variant="outline" size="sm" disabled={busy} onClick={()=>{setPerson(r.id);setModal('reviewed')}}>Confirm signature reviewed</Button>}</div>:<span className="muted">{locked?'Awaiting signed PDF':'Send after editing'}</span>}</TableCell></TableRow>})}</TableBody></Table></section>
 {state.reviews.filter(r=>!r.resolved&&r.assignmentId.includes(batch.id)).map(r=><div className="panel review-row" key={r.id}><div><strong>{r.sender}</strong><p>{r.reason}</p>{r.gmailMessageId&&<a className="text-link" target="_blank" rel="noreferrer" href={`https://mail.google.com/mail/u/0/#all/${r.gmailMessageId}`}>Inspect email in Gmail</a>}</div></div>)}
 </>}
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal('')}}><DialogContent className="portal-dialog"><DialogTitle>{modal==='create'?'New performance review batch':modal==='upload'?'Upload Word template':modal==='send'?'Confirm individual PDF delivery':modal==='reviewed'?'Confirm signature review':'Mark PDF ready'}</DialogTitle><DialogDescription>{modal==='create'?'Create a separate Google Docs copy for each employee. Your template stays unchanged.':modal==='upload'?'Your DOCX is imported as a reusable Google Docs template in Templates. Check formatting after conversion.':'Check the employee and document before continuing.'}</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}
 {modal==='create'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run('create',{groups:JSON.stringify(groups),docId:template,requestId},new FormData(e.currentTarget))}}><label>Batch name<Input name="name" required maxLength={160} placeholder="September 2026 performance reviews"/></label><label>Template<Select value={template} onValueChange={setTemplate}><SelectTrigger><SelectValue placeholder="Select a template"/></SelectTrigger><SelectContent>{templates.map(d=><SelectItem key={d.id} value={d.id}>{d.name} ({d.type})</SelectItem>)}</SelectContent></Select></label>{!templates.length&&<p>No Word or Google Docs templates found. Upload a Word template or add your existing document to Templates in the library.</p>}<fieldset><legend>Employee groups</legend>{state?.groups.map(g=><label className="group-option" key={g.id}><Checkbox checked={groups.includes(g.id)} onCheckedChange={checked=>setGroups(checked?[...groups,g.id]:groups.filter(id=>id!==g.id))}/><span>{g.name}<small>{g.members.map(p=>p.name).join(', ')}</small></span></label>)}</fieldset>{!state?.groups.length&&<p>Create your employee group in the document portal first.</p>}<p>{members.length} individual copies · {members.map(p=>p.email).join(', ')}</p><label>Return due date<Input name="due" type="date" min={new Date().toISOString().slice(0,10)}/></label><Button disabled={busy||!template||!members.length}>{busy?'Creating copies…':'Create individual drafts'}</Button></form>}
 {modal==='upload'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run('upload',{},new FormData(e.currentTarget))}}><label>Template name<Input name="name" required maxLength={160}/></label><label>Word document<Input name="file" type="file" accept=".docx" required/></label><Button disabled={busy}>{busy?'Importing…':'Import to Templates'}</Button></form>}
 {['ready','send','reviewed'].includes(modal)&&batch&&recipient&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(modal,{id:batch.id,person:recipient.id,version:modalVersion,...(modal==='send'?{confirmLive:'yes'}:modal==='reviewed'?{confirmSignature:'yes'}:{})})}}><div className="selected-doc"><FileText/><div><strong>{recipient.name}</strong><p>{recipient.email}</p><small>{batch.name}</small></div></div><a className="text-link" href={modal==='reviewed'?recipient.returnedUrl:preview(batch.id,recipient.id,modalVersion)} target="_blank" rel="noreferrer">{modal==='reviewed'?'Open returned PDF':'Preview this employee’s PDF'} <ArrowUpRight size={14}/></a><label className="live-confirm"><input type="checkbox" required/>{modal==='reviewed'?'I checked this employee’s returned PDF and confirmed the signature.':modal==='send'?'I confirm sending this prepared PDF to this employee by real Gmail.':'I checked this PDF and confirm it contains the correct employee’s review.'}</label><Button disabled={busy}>{busy?'Saving…':modal==='send'?'Send PDF to this employee':modal==='reviewed'?'Mark Reviewed':'Mark Ready'}</Button></form>}
 </DialogContent></Dialog></main></div></SidebarProvider>
}
