// No live Google requests, emails or payroll transactions.
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'jym-roster-test-'));process.env.GOOGLE_DATA_DIR=path.join(temp,'data');
try{for(const n of ['portal-auth','request-security','google-auth','live-store','people-db','business-rules','shift-templates','pay-rates','roster-model','floor-planning','floor-scheduler','roster','roster-reports','timetable-model','employee-model','demo-store','annual-leave','employees','hiring-candidates','hiring-model'])fs.writeFileSync(path.join(temp,n+'.mjs'),ts.transpileModule(fs.readFileSync('lib/'+n+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`));
const load=n=>import(pathToFileURL(path.join(temp,n+'.mjs'))),store=await load('live-store'),r=await load('roster'),m=await load('roster-model'),rules=await load('business-rules'),reports=await load('roster-reports'),employees=await load('employees');const email='owner@example.com';let s=store.loadLive(email);assert.equal(s.businessRules.length,23);const now=new Date().toISOString();s.employees=[['p','Part-Time',26],['f','Full-Time',30],['c','Casual',35],['u','Casual',undefined]].map(([id,type,hourlyRate])=>({id,personId:id,sourceCandidateId:id,name:id,email:id+'@example.com',phone:'123',position:'Staff',notes:'',type,assignedShops:['CARLTONS','SPENCER'],dateOfBirth:id==='u'?undefined:'2000-01-01',casualLevel:type==='Casual'?2:undefined,status:'Active',hourlyRate,currency:'AUD',hiringHistory:{id},created:now,updated:now}));store.saveLive(email,s);
const weekStart='2026-08-03',base={weekStart,revision:'0',employeeId:'p',date:weekStart,start:'08:00',end:'15:00',breakMinutes:'30',notes:''};assert.throws(()=>r.saveShift(s,email,base),/outside employee-confirmed/);assert.equal(s.rosters,undefined);
const revision=()=>String(s.rosters?.find(w=>w.weekStart===weekStart)?.revision||0);const availability=(id,date=weekStart,start='08:00',end='20:00')=>r.saveManualAvailability(s,email,{weekStart,revision:revision(),employeeId:id,date,start,end,note:'Employee confirmed by phone',confirm:'yes'});availability('p');assert.throws(()=>r.saveShift(s,email,base),/changed in another/);assert.throws(()=>r.saveShift(s,email,{...base,revision:revision(),start:'07:00'}),/outside/);
assert.deepEqual(m.openAvailability(s,weekStart,'p',weekStart),[{start:'08:00',end:'20:00'}]);
let w=r.saveShift(s,email,{...base,revision:revision(),actualConfirmed:'yes',actual_start:'08:00',actual_end:'15:00',actual_breakMinutes:'30'});const id=w.shifts[0].id;assert.deepEqual(m.openAvailability(s,weekStart,'p',weekStart),[{start:'15:00',end:'20:00'}]);assert.deepEqual(m.openAvailability(s,weekStart,'u',weekStart),[]);assert.equal(w.shifts.length,1);assert.equal(m.financeRows(s,weekStart)[0].actualPay,171.86);assert.equal(m.financeRows(s,weekStart)[0].annual,0.5);assert.ok(Math.abs(m.financeRows(s,weekStart)[0].personal-6.5*0.038462)<1e-10);assert.equal(m.financeRows(s,weekStart)[0].scheduledMinutes,390);
assert.throws(()=>r.saveShift(s,email,{...base,revision:revision()}),/overlapping/);assert.throws(()=>r.saveShift(s,email,{...base,revision:revision(),start:'20:00',end:'08:00'}),/same day/);assert.throws(()=>r.saveShift(s,email,{...base,revision:revision(),id,breakMinutes:'500'}),/break/);const manual=w.manualAvailability[0];assert.throws(()=>r.deleteManualAvailability(s,email,{weekStart,revision:revision(),id:manual.id}),/Adjust affected/);
s.employees[0].hourlyRate=100;s.employees[0].type='Casual';s.employees[0].casualLevel=1;store.saveLive(email,s);assert.equal(m.financeRows(s,weekStart)[0].actualPay,214.83);assert.equal(m.financeRows(s,weekStart)[0].annual,0.5);
r.saveShift(s,email,{...base,revision:revision(),id,start:'09:00',end:'15:00'});assert.equal(s.rosters[0].shifts[0].employee.hourlyRate,26);assert.equal(s.rosters[0].shifts[0].actual,undefined);assert.equal(m.financeRows(s,weekStart)[0].annual,0);assert.equal(m.financeRows(s,weekStart)[0].unconfirmed,1);
r.saveShift(s,email,{...base,revision:revision(),id,refreshPay:'yes'});assert.equal(s.rosters[0].shifts[0].employee.hourlyRate,100);assert.equal(s.rosters[0].shifts[0].employee.type,'Casual');
for(const id of ['f','c','u']){availability(id);r.saveShift(s,email,{...base,revision:revision(),employeeId:id,actualConfirmed:'yes',actual_start:'08:00',actual_end:'15:00',actual_breakMinutes:'30'});}
const finance=m.financeRows(s,weekStart);assert.equal(finance.find(r=>r.employeeId==='f').annual,0.5);assert.equal(finance.find(r=>r.employeeId==='c').annual,0);assert.equal(finance.find(r=>r.employeeId==='c').personal,0);assert.equal(finance.find(r=>r.employeeId==='u').estimated,null);assert.equal(finance.find(r=>r.employeeId==='u').actualPay,null);
const annual=rules.leaveForHours(13,'Full-Time',s.businessRules);assert.equal(annual.annual,1);assert.equal(rules.leaveForHours(13,'Casual',s.businessRules).annual,0);assert.throws(()=>employees.payDetails('-1','AUD'),/hourly rate/);assert.throws(()=>employees.payDetails('20',''),/currency/);assert.deepEqual(employees.payDetails('','AUD'),{hourlyRate:undefined,currency:'AUD'});assert.equal(employees.payDetails('0','AUD').hourlyRate,0);
const future='2099-08-03';assert.ok(m.validMonday(future));r.saveManualAvailability(s,email,{weekStart:future,revision:'0',employeeId:'f',date:future,start:'08:00',end:'16:00',note:'Employee replied',confirm:'yes'});assert.throws(()=>r.saveShift(s,email,{...base,weekStart:future,date:future,revision:'1',employeeId:'f',actualConfirmed:'yes',actual_start:'08:00',actual_end:'15:00',actual_breakMinutes:'0'}),/finished/);
const csv=reports.financeCSV(s,weekStart);assert.ok(csv.startsWith('\uFEFF'));assert.ok(csv.includes('Employee age required'));assert.ok(csv.includes('Unconfirmed shifts'));const rosterCSV=reports.rosterCSV(s,weekStart);assert.ok(!rosterCSV.includes('@example.com'));assert.ok(!rosterCSV.includes('Hourly base'));s.rosters.find(w=>w.weekStart===weekStart).shifts[0].employee.name='=HYPERLINK("bad")<script>alert(1)</script>';assert.ok(reports.rosterCSV(s,weekStart).includes("'=HYPERLINK"));assert.ok(!reports.printableRoster(s,weekStart).includes('<script>alert'));
store.saveLive(email,s);s=store.loadLive(email);assert.equal(s.rosters.find(w=>w.weekStart===weekStart).shifts.length,4);assert.equal(s.businessRules.length,23);assert.equal(store.loadLive('other@example.com').rosters,undefined);const db=new DatabaseSync(path.join(process.env.GOOGLE_DATA_DIR,'portal.sqlite'));assert.equal(db.prepare('SELECT COUNT(*) AS n FROM business_rule').get().n,23);db.close();const before=s.rosters.find(w=>w.weekStart===weekStart).shifts.length;assert.throws(()=>r.deleteShift(s,email,{weekStart,revision:revision(),id}),/Confirm/);r.deleteShift(s,email,{weekStart,revision:revision(),id,confirm:'yes'});assert.equal(s.rosters.find(w=>w.weekStart===weekStart).shifts.length,before-1);
// Exercise real route handlers with a temporary authenticated session, without HTTP or live credentials.
process.env.PORTAL_ADMIN_EMAIL='test-admin@example.com';const portal=await load('portal-auth');const portalToken=portal.createLogin({sub:'test-admin',email:process.env.PORTAL_ADMIN_EMAIL,email_verified:true});const auth=await load('google-auth');auth.saveConnection({accessToken:'fake',refreshToken:'fake',expiresAt:Date.now()+60000,email,sessionHash:auth.hash('test-cookie'),sessionExpires:Date.now()+60000,connectedAt:now});
for(const [filename,source] of [['route','app/api/roster/route.ts'],['export-route','app/api/roster/export/route.ts']])fs.writeFileSync(path.join(temp,filename+'.mjs'),ts.transpileModule(fs.readFileSync(source,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]@\/lib\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`));
const route=await load('route'),exportRoute=await load('export-route');const headers={host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000','x-portal-request':'1',cookie:'jym_portal='+portalToken,get 'x-workspace-revision'(){return String(store.loadLive(auth.readConnection().email).workspaceRevision)}};
const unauth=await exportRoute.GET(new Request('http://127.0.0.1:3000/api/roster/export?week='+weekStart+'&kind=finance',{headers:{host:headers.host}}));assert.equal(unauth.status,400);assert.match((await unauth.json()).error,/Sign in with your approved Google/);
for(const kind of ['roster','finance','payroll','print']){const result=await exportRoute.GET(new Request('http://127.0.0.1:3000/api/roster/export?week='+weekStart+'&kind='+kind,{headers}));assert.equal(result.status,200);assert.equal(result.headers.get('cache-control'),'no-store');assert.ok((await result.text()).length>100);}
const badRequest=new FormData();badRequest.set('action','shift');const rejected=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers:{...headers,origin:'https://other.example'},body:badRequest}));assert.equal(rejected.status,400);assert.match((await rejected.json()).error,/originate/);
const postData=new FormData();Object.entries({...base,action:'shift',revision:revision(),employeeId:'p',start:'16:00',end:'18:00'}).forEach(([k,v])=>postData.set(k,v));const posted=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:postData}));assert.equal(posted.status,200);assert.equal((await posted.json()).rosters.find(w=>w.weekStart===weekStart).shifts.length,4);
const autoState=store.loadLive('auto@example.com');autoState.employees=structuredClone(s.employees);autoState.timetable={settings:{employeeIds:[],timezone:'Etc/GMT-10',sendTime:'08:00',enabled:false,openHour:8,closeHour:20},weeks:[{id:'auto-test',weekStart,employeeIds:['p'],settings:{},responses:[{employeeId:'p',hours:{[weekStart]:[8,9,10,11,18,19,20,21]}}],responseErrors:[],created:now}]};
assert.equal(r.autoAllocateWeek(autoState,'auto@example.com',weekStart),2);assert.deepEqual(autoState.rosters[0].shifts.map(sh=>[sh.start,sh.end]),[['08:00','12:00'],['18:00','22:00']]);assert.deepEqual(m.openAvailability(autoState,weekStart,'p',weekStart),[]);assert.equal(r.autoAllocateWeek(autoState,'auto@example.com',weekStart),0);const removed=autoState.rosters[0].shifts[0];r.deleteShift(autoState,'auto@example.com',{weekStart,revision:String(autoState.rosters[0].revision),id:removed.id,confirm:'yes'});assert.deepEqual(m.openAvailability(autoState,weekStart,'p',weekStart),[{start:'08:00',end:'12:00'}]);assert.equal(r.autoAllocateWeek(autoState,'auto@example.com',weekStart),0);assert.equal(store.loadLive('auto@example.com').rosters[0].shifts.length,1);
autoState.timetable.weeks[0].employeeIds.push('f');autoState.timetable.weeks[0].responses.push({employeeId:'f',hours:{[weekStart]:[10,11]}});assert.equal(r.autoAllocateWeek(autoState,'auto@example.com',weekStart),1);assert.equal(autoState.rosters[0].shifts.filter(sh=>sh.employeeId==='p').length,1);
console.log('PASS: split-day auto allocation 08–12 and 18–22, remaining hours 8→0→4 after deletion, refresh preserves HR changes, new respondent automatically scheduled, persistence.');
const templates=await load('shift-templates');assert.equal(templates.shiftTemplates.length,6);assert.equal(templates.templateHours(templates.shiftTemplates[0]),6);assert.equal(templates.templateHours(templates.shiftTemplates.find(t=>t.id==='CARLTONS-FULL')),9);assert.equal(templates.templateHours(templates.shiftTemplates.find(t=>t.id==='SPENCER-LATE')),4);assert.equal(templates.templateApplies(templates.shiftTemplates.find(t=>t.id==='SPENCER-FULL'),'2026-08-09'),true);
const floor=store.loadLive('floor@example.com');floor.employees=structuredClone(s.employees);const fw='2026-07-27';const frev=()=>String(floor.rosters?.find(w=>w.weekStart===fw)?.revision||0);r.saveManualAvailability(floor,'floor@example.com',{weekStart:fw,revision:frev(),employeeId:'f',date:fw,start:'08:00',end:'22:00',note:'Confirmed hours',confirm:'yes'});const finput={weekStart:fw,revision:frev(),employeeId:'f',date:fw,start:'10:30',end:'17:30',breakMinutes:'60',restaurant:'CARLTONS',category:'Floor',templateId:'CARLTONS-EARLY'};r.saveShift(floor,'floor@example.com',finput);const fsaved=floor.rosters[0].shifts[0];assert.equal(fsaved.breakStart,'14:30');assert.equal(fsaved.breakEnd,'15:30');assert.equal(m.netMinutes(fsaved),360);assert.equal(m.financeRows(floor,fw)[0].estimated,158.64);assert.equal(m.filterRoster(floor,'Kitchen').rosters[0].shifts.length,0);assert.equal(m.filterRoster(floor,'Floor','CARLTONS').rosters[0].shifts.length,1);assert.throws(()=>r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),restaurant:'SPENCER',templateId:'SPENCER-EARLY'}),/overlapping/);assert.throws(()=>r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),id:fsaved.id,start:'10:00'}),/Template times/);assert.throws(()=>r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),id:fsaved.id,category:'Kitchen'}),/does not apply/);assert.throws(()=>r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),id:fsaved.id,templateId:'',breakStart:'15:00',breakEnd:'15:30'}),/match the unpaid minutes/);
r.saveManualAvailability(floor,'floor@example.com',{weekStart:fw,revision:frev(),employeeId:'f',date:'2026-08-01',start:'08:00',end:'22:00',note:'Confirmed weekend hours',confirm:'yes'});assert.throws(()=>r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),date:'2026-08-01',restaurant:'SPENCER',templateId:'SPENCER-LATE',start:'17:30',end:'22:00',breakMinutes:'0'}),/Template times/);r.saveShift(floor,'floor@example.com',{...finput,revision:frev(),date:'2026-08-01',restaurant:'SPENCER',templateId:'SPENCER-LATE',start:'18:00',end:'22:00',breakMinutes:'0'});assert.equal(m.financeRows(floor,fw).length,2);assert.equal(m.financeRows(floor,fw).reduce((sum,r)=>sum+r.scheduledMinutes,0),600);assert.ok(reports.rosterCSV(floor,fw).includes('14:30'));assert.ok(reports.financeCSV(floor,fw).includes('CARLTONS'));assert.equal(store.loadLive('floor@example.com').rosters[0].shifts[0].category,'Floor');console.log('PASS: six shared Floor templates, paid hours, precise unpaid breaks, weekday/weekend gating, no category-specific rule leakage, cross-restaurant overlap prevention, separate report groups, filters and persistence.');
// Candidate trials are manual, persisted, isolated from employee finance, and guarded by hiring stages.
const trialAccount='trials@example.com';let trialState=store.loadLive(trialAccount);
const hc=await load('hiring-candidates');const tc=hc.saveCandidate(trialState,trialAccount,{name:'Trial candidate',email:'trial@example.com'});
const trialInput={weekStart,revision:'0',candidateId:tc.id,date:weekStart,start:'10:00',end:'11:00',restaurant:'CARLTONS'};
assert.throws(()=>r.saveTrial(trialState,trialAccount,trialInput),/interview and acknowledgement/);
tc.interview='Passed';tc.ackAssignmentId='trial-ack';trialState.assignments=[{id:'trial-ack',recipients:[{status:'Completed'}]}];
r.saveTrial(trialState,trialAccount,trialInput);trialState=store.loadLive(trialAccount);const trialShift=trialState.rosters[0].shifts[0];
assert.equal(trialShift.category,'Trial');assert.equal(trialShift.employee.type,'Candidate');assert.equal(m.netMinutes(trialShift),60);assert.equal(trialState.hiring.candidates[0].trial,'Scheduled');assert.equal(trialState.hiring.candidates[0].trialAt,'2026-08-03T00:00:00.000Z');assert.equal(trialState.employees.length,0);assert.equal(m.financeRows(trialState,weekStart).length,0);
assert.ok(reports.rosterCSV(trialState,weekStart).includes('Manually scheduled trial'));assert.ok(reports.printableRoster(trialState,weekStart).includes('Trial candidate'));
assert.throws(()=>r.saveTrial(trialState,trialAccount,trialInput),/another window/);
assert.throws(()=>r.saveTrial(trialState,trialAccount,{...trialInput,revision:'1',start:'10:30',end:'12:30'}),/overlapping/);
assert.throws(()=>r.saveTrial(trialState,trialAccount,{...trialInput,revision:'1',date:'2026-08-10'}),/selected week/);
assert.throws(()=>r.saveTrial(trialState,trialAccount,{...trialInput,revision:'1',start:'12:00'}),/end after start/);
r.saveTrial(trialState,trialAccount,{...trialInput,revision:'1',id:trialShift.id,end:'12:00'});assert.equal(m.netMinutes(trialState.rosters[0].shifts[0]),120);
assert.equal(r.autoAllocateWeek(trialState,trialAccount,weekStart),0);assert.equal(store.loadLive(trialAccount).rosters[0].shifts[0].end,'12:00');
r.saveTrial(trialState,trialAccount,{...trialInput,revision:'2',id:trialShift.id,start:'10:02',end:'13:47'});assert.equal(m.netMinutes(trialState.rosters[0].shifts[0]),225);
r.saveTrial(trialState,trialAccount,{...trialInput,revision:'3',id:trialShift.id,start:'10:02',end:'10:19'});assert.equal(m.netMinutes(trialState.rosters[0].shifts[0]),17);
r.deleteShift(trialState,trialAccount,{weekStart,revision:'4',id:trialShift.id,confirm:'yes'});assert.equal(trialState.hiring.candidates[0].trial,'Pending');assert.equal(trialState.hiring.candidates[0].trialAt,undefined);
trialState.rosters[0].shifts=[{...trialShift,category:'Trade',candidateId:undefined}];store.saveLive(trialAccount,trialState);assert.equal(store.loadLive(trialAccount).rosters[0].shifts[0].category,'Trial');
console.log('PASS: candidate trial gates, one/two-hour scheduling, edit/delete, overlap validation, stale writes, UTC+10, persistence, reports, finance exclusion and legacy Trade migration.');
// Verify employee + automatic allocation + day rates + CSV using isolated mock data.
const payrollAccount='payroll-test@example.com',pw='2026-09-28';
let ps=store.loadLive(payrollAccount);
ps.employees=[{...s.employees.find(e=>e.id==='f'),id:'pay-test',personId:'pay-test',sourceCandidateId:'pay-test',name:'[Mock] Payroll test',email:'payroll@demo.invalid',type:'Part-Time',level:2,casualLevel:undefined,dateOfBirth:'2006-10-01',hourlyRate:999}];
ps.timetable={weeks:[{weekStart:pw,employeeIds:['pay-test'],settings:{slotMinutes:60},responses:[{employeeId:'pay-test',hours:{'2026-09-28':[10,11,12],'2026-10-01':[10,11],'2026-10-03':[10,11],'2026-10-04':[10,11]}}]}]};
assert.equal(r.autoAllocateWeek(ps,payrollAccount,pw),4);
let details=m.payrollRows(ps,pw);
assert.deepEqual(details.map(p=>[p.age,p.ageGroup,p.dayType,p.rateCents,p.estimatedCents]),[[19,'19','Weekday',2302,6906],[20,'20+','Weekday',2708,5416],[20,'20+','Saturday',3385,6770],[20,'20+','Sunday',4062,8124]]);
assert.equal(m.financeRows(ps,pw)[0].estimated,272.16);
const pshift=ps.rosters[0].shifts[0];
r.saveShift(ps,payrollAccount,{weekStart:pw,revision:String(ps.rosters[0].revision),id:pshift.id,employeeId:'pay-test',date:pw,start:'10:00',end:'13:00',breakMinutes:'30'});
assert.equal(m.payrollRows(ps,pw)[0].scheduledMinutes,150);
assert.equal(m.payrollRows(ps,pw)[0].estimatedCents,5755);
assert.equal(m.financeRows(ps,pw)[0].estimated,260.65);
r.setPublicHoliday(ps,payrollAccount,{weekStart:pw,revision:String(ps.rosters[0].revision),date:'2026-10-04',enabled:'yes'});
assert.equal(m.payrollRows(ps,pw).at(-1).dayType,'Public Holiday');
assert.equal(m.payrollRows(ps,pw).at(-1).rateCents,6093);
assert.equal(m.financeRows(ps,pw)[0].estimated,301.27);
ps=store.loadLive(payrollAccount);assert.deepEqual(ps.rosters[0].publicHolidays,['2026-10-04']);
assert.throws(()=>r.setPublicHoliday(ps,payrollAccount,{weekStart:pw,revision:'0',date:pw,enabled:'yes'}),/another window/);
assert.throws(()=>r.setPublicHoliday(ps,payrollAccount,{weekStart:pw,revision:String(ps.rosters[0].revision),date:'2026-10-05',enabled:'yes'}),/selected week/);
assert.throws(()=>r.setPublicHoliday(ps,payrollAccount,{weekStart:pw,revision:String(ps.rosters[0].revision),date:pw,enabled:'maybe'}),/whether/);
// Check another isolated company fixture. Reset ONLY this temporary test workspace binding.
const memberDb=new DatabaseSync(path.join(process.env.GOOGLE_DATA_DIR,'members.sqlite'));memberDb.exec("DELETE FROM setting WHERE key='company-mailbox'");memberDb.close();
// Check real holiday POST route and detailed export with the same stored fixture.
auth.saveConnection({accessToken:'fake',refreshToken:'fake',expiresAt:Date.now()+60000,email:payrollAccount,sessionHash:auth.hash('test-cookie'),sessionExpires:Date.now()+60000,connectedAt:now});
const holidayForm=new FormData();Object.entries({action:'holiday',weekStart:pw,revision:String(ps.rosters[0].revision),date:'2026-10-04',enabled:'no'}).forEach(([k,v])=>holidayForm.set(k,v));
const holidayResult=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:holidayForm}));assert.equal(holidayResult.status,200);ps=await holidayResult.json();assert.deepEqual(ps.rosters[0].publicHolidays,[]);
const detailResponse=await exportRoute.GET(new Request('http://127.0.0.1:3000/api/roster/export?week='+pw+'&kind=payroll',{headers}));assert.equal(detailResponse.status,200);const detailCSV=await detailResponse.text();assert.ok(detailCSV.includes('"19","19"'));assert.ok(detailCSV.includes('"23.02","57.55"'));assert.ok(detailCSV.includes('"Sunday"'));assert.ok(detailCSV.includes('"MOCK"'));assert.ok(reports.financeCSV(ps,pw).includes('"260.65"'));
// Arbitrary minute durations are charged precisely; confirmed actual work uses its own hours.
const fixture=ps.rosters[0].shifts[0];fixture.start='10:02';fixture.end='10:19';fixture.breakMinutes=0;fixture.actual={start:'10:02',end:'10:13',breakMinutes:1,confirmedAt:now};
let pd=m.payrollRows(ps,pw)[0];assert.equal(pd.estimatedCents,652);assert.equal(pd.actualMinutes,10);assert.equal(pd.actualCents,384);
ps.employees[0].type='Casual';ps.employees[0].casualLevel=2;
assert.equal(m.payrollRows(ps,pw)[0].rateCents,2878);
assert.equal(m.financeRows(ps,pw)[0].annual,10/60/13);
ps.employees[0].level=1;assert.equal(m.payrollRows(ps,pw)[0].rateCents,2810);
ps.employees[0].dateOfBirth='2010-01-01';assert.equal(m.payrollRows(ps,pw)[0].ageGroup,'Under 17');assert.equal(m.payrollRows(ps,pw)[0].rateCents,1653);
ps.employees[0].dateOfBirth=undefined;assert.equal(m.financeRows(ps,pw)[0].estimated,null);assert.equal(m.financeRows(ps,pw)[0].actualPay,null);assert.match(m.payrollRows(ps,pw)[0].issues.join(),/birth/);
ps.employees[0].manualAge=19;assert.equal(m.payrollRows(ps,pw)[0].ageGroup,'19');assert.ok(m.payrollRows(ps,pw)[0].rateCents>0);assert.equal(m.financeRows(ps,pw)[0].status.target,'ready');
ps.employees[0].dateOfBirth='2010-01-01';assert.equal(m.payrollRows(ps,pw)[0].ageGroup,'Under 17');
ps.employees[0].dateOfBirth=undefined;ps.employees[0].manualAge=20;assert.equal(m.payrollRows(ps,pw)[0].ageGroup,'20+');
for(const age of [-1,19.5,NaN,121]){ps.employees[0].manualAge=age;assert.equal(m.payrollRows(ps,pw)[0].rateCents,null);}
ps.employees[0].manualAge=undefined;
ps.employees[0].dateOfBirth='2026-02-30';assert.equal(m.payrollRows(ps,pw)[0].rateCents,null);
ps.employees[0].dateOfBirth='2000-01-01';fixture.date='2026-06-30';assert.match(m.payrollRows(ps,pw)[0].issues.join(),/No rate table before/);fixture.date=pw;
ps.employees=[];assert.match(m.payrollRows(ps,pw)[0].issues.join(),/profile missing/);assert.equal(m.financeRows(ps,pw)[0].estimated,null);
console.log('PASS: automatic allocation → current employee profile → exact day rates → preview and CSV; birthday during week, junior/adult, weekend, holiday priority and authenticated persistence, profile changes, arbitrary minutes, break deduction, actual hours, missing/invalid DOB, version gate and no legacy-rate fallback.');
assert.equal(m.payrollStatus(['Date of birth or manual age required']).label,'Employee age required');
assert.equal(m.payrollStatus(['No rate table before 2026-07-01']).target,'rates');
assert.equal(m.payrollStatus(['Invalid working hours']).target,'shifts');
assert.equal(m.payrollStatus(['Employee profile missing']).target,'directory');
assert.equal(m.payrollStatus([]).label,'Calculated automatically');
// Legacy employee has no manual hourly rate or explicit Level. Filling DOB alone fixes existing shifts.
ps.employees=[{...s.employees.find(e=>e.id==='f'),id:'pay-test',personId:'pay-test',type:'Part-Time',level:undefined,casualLevel:undefined,dateOfBirth:undefined,hourlyRate:undefined}];
assert.equal(m.financeRows(ps,pw)[0].status.label,'Employee age required');
ps.employees[0].dateOfBirth='2000-01-01';
assert.equal(m.payrollRows(ps,pw)[0].rateCents,2644);
assert.equal(m.financeRows(ps,pw)[0].status.target,'ready');
assert.ok(!reports.financeCSV(ps,pw).includes('RATE REQUIRED'));
console.log('PASS: legacy profiles calculate without manual hourlyRate, DOB repair updates existing shifts directly, and missing-profile/date/rule/hours states show the correct resolution.');
const floorStateBefore=store.loadLive(payrollAccount),floorRevision=String(floorStateBefore.rosters[0].revision);floorStateBefore.rosters[0].shifts[0].notes='Owner retained shift';store.saveLive(payrollAccount,floorStateBefore);
const floorForm=new FormData();Object.entries({action:'floor-auto',restaurant:'CARLTONS',weekStart:pw,revision:floorRevision,teams:JSON.stringify({CARLTONS:['pay-test'],SPENCER:[]}),closedDates:JSON.stringify({CARLTONS:[],SPENCER:[]})}).forEach(([k,v])=>floorForm.set(k,v));
const floorResponse=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:floorForm}));assert.equal(floorResponse.status,200);
const floorSaved=store.loadLive(payrollAccount);assert.deepEqual(floorSaved.rosters[0].floorPlan.teams.CARLTONS,['pay-test']);assert.deepEqual(floorSaved.rosters[0].floorPlan.teams.SPENCER,['pay-test']); // posted empty SPENCER team is ignored; profiles are authoritative
assert.ok(floorSaved.rosters[0].floorPlan.missing.length>0);
for(const before of floorStateBefore.rosters[0].shifts.filter(sh=>sh.notes==='Owner retained shift'))assert.deepEqual(floorSaved.rosters[0].shifts.find(sh=>sh.id===before.id),before);
const staleFloor=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:floorForm}));assert.equal(staleFloor.status,400);
const closuresForm=new FormData();Object.entries({action:'floor-closures',restaurant:'SPENCER',weekStart:pw,revision:String(floorSaved.rosters[0].revision),closedDates:JSON.stringify({CARLTONS:['invalid-ignored'],SPENCER:[pw]})}).forEach(([k,v])=>closuresForm.set(k,v));
const closureResponse=await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:closuresForm}));assert.equal(closureResponse.status,200);
const closureSaved=store.loadLive(payrollAccount);assert.deepEqual(closureSaved.rosters[0].shifts,floorSaved.rosters[0].shifts);assert.deepEqual(closureSaved.rosters[0].floorPlan.closedDates,{CARLTONS:[],SPENCER:[pw]});
const missingShop=new FormData();Object.entries({action:'floor-auto',weekStart:pw,revision:String(closureSaved.rosters[0].revision)}).forEach(([k,v])=>missingShop.set(k,v));assert.equal((await route.POST(new Request('http://127.0.0.1:3000/api/roster',{method:'POST',headers,body:missingShop}))).status,400);
console.log('PASS: closed dates save independently without altering shifts or another shop; auto arrange requires an explicit shop.');
console.log('PASS: authenticated Floor auto arrangement persists teams, missing roles and manual shifts; rejects stale requests.');
console.log('PASS: authenticated roster mutation and all four export routes; unauthenticated financial report and cross-origin mutation blocked.');
console.log('PASS: 23 SQLite rules, exact annual leave, personal leave, casual exclusion, required confirmed availability, manual confirmation, overlap and break validation, stale edits, future actual-work rejection, CRUD, legacy shift metadata preservation, automatic profile-based rates, missing rates, actual-only accrual, CSV injection protection, staff report privacy, HTML escaping, persistence and account isolation. No live Google calls.');
}finally{fs.rmSync(temp,{recursive:true,force:true})}
