// Isolated contract tests. All Google HTTP is mocked; no credentials or live accounts are used.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'jym-google-test-'));
process.env.GOOGLE_DATA_DIR=path.join(temp,'secrets');
process.env.APP_ORIGIN='http://127.0.0.1:3000';
process.env.GOOGLE_POLL_INTERVAL_SECONDS='0';
for(const name of ['portal-auth','request-security','google-auth','live-store','people-db','business-rules','shift-templates','employee-model','google-workflow','hiring-candidates','department-availability','availability','floor-planning','floor-scheduler','roster','pay-rates','roster-model','timetable-model','person-forms','google-forms','hiring-sync','hiring-model','demo-store','library-filter']){const source=fs.readFileSync(`lib/${name}.ts`,'utf8');const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`);fs.writeFileSync(path.join(temp,name+'.mjs'),js)}
const auth=await import(pathToFileURL(path.join(temp,'google-auth.mjs')));
const store=await import(pathToFileURL(path.join(temp,'live-store.mjs')));
const work=await import(pathToFileURL(path.join(temp,'google-workflow.mjs')));
const demo=await import(pathToFileURL(path.join(temp,'demo-store.mjs')));
auth.saveClientConfig('test.apps.googleusercontent.com','secret-example');assert.equal(auth.configured(),true);assert.equal(fs.readFileSync(path.join(temp,'secrets/oauth-client.enc'),'utf8').includes('secret-example'),false);
const cipher=auth.encrypt({state:'abc'});assert.deepEqual(auth.decrypt(cipher),{state:'abc'});assert.throws(()=>auth.decrypt(cipher.slice(0,-2)+'ZZ'));
const email='manager@example.com',sessionToken='session-test';auth.saveConnection({accessToken:'access-test',refreshToken:'refresh-test',expiresAt:Date.now()+3600000,email,sessionHash:auth.hash(sessionToken),sessionExpires:Date.now()+3600000,connectedAt:new Date().toISOString()});
process.env.PORTAL_ADMIN_EMAIL=email;const portal=await import(pathToFileURL(path.join(temp,'portal-auth.mjs')));const loginToken=portal.createLogin({sub:'test-admin',email,email_verified:true});assert.equal(auth.session(new Request('http://127.0.0.1:3000',{headers:{cookie:'jym_portal='+loginToken}})).email,email);assert.throws(()=>auth.session(new Request('http://127.0.0.1:3000',{headers:{cookie:'jym_session='+sessionToken}})));assert.throws(()=>auth.session(new Request('http://127.0.0.1:3000')));
assert.throws(()=>auth.localRequest(new Request('http://127.0.0.1:3000',{headers:{host:'evil.example'}})));
assert.throws(()=>auth.localRequest(new Request('http://127.0.0.1:3000',{headers:{host:'127.0.0.1:3000',origin:'https://evil.example','x-portal-request':'1'}}),true));
let sendCalls=0,uploadCalls=0,folderCalls=0;let failSecond=true;let messages=[];let returnFile=null;let tokenCalls=0;const pdf=demo.samplePdf('Returned employee review');
const respond=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}});
globalThis.fetch=async(url,init={})=>{const u=new URL(url);if(u.hostname==='oauth2.googleapis.com'){tokenCalls++;return respond({access_token:'refreshed-test',expires_in:3600})}assert.ok(['www.googleapis.com','gmail.googleapis.com'].includes(u.hostname));assert.match(init.headers.Authorization,/Bearer (access-test|refreshed-test)/);
if(u.pathname.endsWith('/messages/send')){sendCalls++;const raw=JSON.parse(init.body).raw;const mime=Buffer.from(raw,'base64url').toString();assert.match(mime,/Content-Disposition: attachment/);assert.match(mime,/Message-ID:/);if(sendCalls===2&&failSecond)throw Error('Simulated timeout');return respond({id:'out-'+sendCalls,threadId:'thread-'+sendCalls})}
if(u.pathname.includes('/threads/'))return respond({messages});
if(u.pathname.endsWith('/attachments/attachment-1'))return respond({data:pdf.toString('base64url')});
if(u.pathname.endsWith('/messages'))return respond({messages:u.searchParams.get('q')?.includes('rfc822msgid')?[{id:'out-2',threadId:'thread-2'}]:[]});
if(u.pathname==='/upload/drive/v3/files'){uploadCalls++;const text=Buffer.from(init.body).toString();assert.match(text,/multipart|application\/json/);returnFile={id:'returned-drive-id',name:'Return.pdf',mimeType:'application/pdf',webViewLink:'https://drive.google.com/file/d/returned-drive-id/view'};return respond(returnFile)}
if(u.pathname==='/drive/v3/files/source-pdf'&&u.searchParams.get('alt')==='media')return new Response(pdf);
if(u.pathname==='/drive/v3/files/source-pdf')return respond({id:'source-pdf',size:String(pdf.length),mimeType:'application/pdf'});
if(u.pathname==='/drive/v3/files'&&init.method==='POST'){folderCalls++;return respond({id:'folder-'+folderCalls})}
if(u.pathname==='/drive/v3/files'){const q=u.searchParams.get('q')||'';if(q.includes('gmailMessageId'))return respond({files:returnFile?[returnFile]:[]});return respond({files:[]})}
throw Error('Unexpected mocked Google request '+u.pathname)};
let s=store.loadLive(email);assert.equal(s.documents.length,0);assert.equal(s.groups.length,0);assert.equal(store.loadLive('other@example.com').assignments.length,0);
s.documents=[{id:'source-pdf',driveId:'source-pdf',name:'Review',type:'PDF',category:'Templates',updated:'2026-09-21',size:'1 KB'}];s.groups=[{id:'g1',name:'Team',description:'',members:[{id:'p1',name:'One',email:'one@example.com'},{id:'p2',name:'Two',email:'two@example.com'}]},{id:'g2',name:'Overlap',description:'',members:[{id:'p1',name:'One',email:'one@example.com'}]}];
const input={name:'Live review',docId:'source-pdf',groups:['g1','g2'],due:'',message:'Please return',requestId:'request-unique'};
const a=await work.sendAssignment(s,email,input);assert.equal(a.recipients.length,2);assert.equal(a.recipients[0].delivery,'sent');assert.equal(a.recipients[1].delivery,'uncertain');assert.equal(sendCalls,2);
await work.sendAssignment(s,email,input);assert.equal(sendCalls,2,'repeated request must not send again');
const makeMessage=(id,overrides={})=>({id,threadId:'thread-1',internalDate:String(Date.now()),payload:{headers:[{name:'From',value:'One <one@example.com>'},{name:'Subject',value:'Re: ['+a.id+'] Live review'}],parts:[{mimeType:'multipart/mixed',parts:[{filename:'unrelated-name.pdf',mimeType:'application/pdf',body:{size:pdf.length,attachmentId:'attachment-1'}}]}]},...overrides});
assert.equal(work.matchReply(s,makeMessage('match')).r.email,'one@example.com');const encodedMessage=makeMessage('encoded');encodedMessage.payload.headers[1].value='=?UTF-8?B?'+Buffer.from('Re: ['+a.id+'] Review').toString('base64')+'?=';assert.equal(work.matchReply(s,encodedMessage).r.email,'one@example.com');assert.match(work.matchReply(s,makeMessage('wrong',{threadId:'other-thread'})).reason,/thread/);
messages=[makeMessage('return-1')];await work.collectReplies(s,email);assert.equal(a.recipients[1].delivery,'sent','ambiguous send recovered by RFC message id');assert.equal(a.recipients[0].status,'Completed');assert.equal(a.recipients[0].returnedDriveId,'returned-drive-id');assert.ok(a.recipients[0].destination.includes('/Live review/One/'));assert.equal(uploadCalls,1);
await work.collectReplies(s,email);assert.equal(uploadCalls,1,'repeated collection must not duplicate uploads');
messages=[makeMessage('bad-thread',{threadId:'other-thread'})];await work.collectReplies(s,email);assert.ok(s.reviews.some(r=>r.gmailMessageId==='bad-thread'));
messages=[makeMessage('no-pdf',{threadId:'thread-2',payload:{headers:[{name:'From',value:'two@example.com'},{name:'Subject',value:'Re: ['+a.id+']'}]}})];await work.collectReplies(s,email);assert.equal(a.recipients[1].status,'Pending');assert.ok(s.reviews.some(r=>r.reason==='No valid PDF attachment found.'));
assert.equal(store.loadLive(email).assignments[0].recipients[0].status,'Completed');
const c=auth.readConnection();auth.saveConnection({...c,expiresAt:0});await Promise.all([auth.googleJson('https://www.googleapis.com/drive/v3/files'),auth.googleJson('https://www.googleapis.com/drive/v3/files')]);assert.equal(tokenCalls,1,'concurrent refresh must share one token request');
await assert.rejects(()=>auth.googleFetch('https://evil.example/'),/Unsupported/);
const library=await import(pathToFileURL(path.join(temp,'library-filter.mjs')));
const originalMockFetch=globalThis.fetch;let libraryPageCalls=0;
globalThis.fetch=async(url,init)=>{const u=new URL(url);assert.equal(u.pathname,'/drive/v3/files');assert.ok(u.searchParams.get('fields').includes('parents'),'folder relationships must be requested');assert.ok(u.searchParams.get('q').includes('application/vnd.google-apps.folder'));libraryPageCalls++;return respond(u.searchParams.get('pageToken')?{files:[{id:'pdf-2',name:'Second.pdf',mimeType:'application/pdf',parents:['templates']},{id:'nested-pdf',name:'Nested.pdf',mimeType:'application/pdf',parents:['child']},{id:'form-1',name:'Feedback',mimeType:'application/vnd.google-apps.form',parents:['templates']},{id:'submission',name:'Returned.pdf',mimeType:'application/pdf',parents:['templates'],appProperties:{role:'submission'}}]}:{nextPageToken:'page-2',files:[{id:'root-a',name:'Company A',mimeType:'application/vnd.google-apps.folder'},{id:'templates',name:'Templates',mimeType:'application/vnd.google-apps.folder',parents:['root-a']},{id:'root-b',name:'Company B',mimeType:'application/vnd.google-apps.folder'},{id:'other-templates',name:'Templates',mimeType:'application/vnd.google-apps.folder',parents:['root-b']},{id:'child',name:'Archive',mimeType:'application/vnd.google-apps.folder',parents:['templates']},{id:'empty',name:'Empty',mimeType:'application/vnd.google-apps.folder'},{id:'pdf-1',name:'First.pdf',mimeType:'application/pdf',parents:['templates']},{id:'other-pdf',name:'Other.pdf',mimeType:'application/pdf',parents:['other-templates']} ]})};
await work.syncDrive(s,email);assert.equal(libraryPageCalls,2);assert.deepEqual(library.filterLibrary(s.documents,'templates','','PDF').map(d=>d.id).sort(),['pdf-1','pdf-2']);assert.equal(library.filterLibrary(s.documents,'templates','second','PDF').length,1);assert.equal(library.filterLibrary(s.documents,'empty').length,0);assert.equal(library.filterLibrary(s.documents,'all').length,5);assert.equal(library.filterLibrary(s.documents,'other-templates')[0].id,'other-pdf');assert.ok(!s.documents.some(d=>d.id==='submission'));assert.ok(library.folderChoices(s.folderOptions).some(f=>f.label==='Company A / Templates'));assert.ok(library.folderChoices(s.folderOptions).some(f=>f.label==='Company B / Templates'));assert.deepEqual(store.loadLive(email).documents.find(d=>d.id==='pdf-2').parentIds,['templates']);globalThis.fetch=originalMockFetch;
console.log('PASS: paginated Drive folder metadata, exactly two PDFs in Templates, combined name/type/folder filters, nested-file exclusion, empty folder, duplicate folder names, all-folders view and persisted parent IDs.');
const templateState=store.loadLive('templates-test@example.com');templateState.folders={root:'portal-root',templates:'portal-templates',assignments:'portal-assignments',submissions:'portal-submissions'};
const source={id:'existing-form',name:'Existing Form',mimeType:'application/vnd.google-apps.form',parents:['original-folder'],webViewLink:'https://docs.google.com/forms/d/existing-form/edit'};let shortcut;let shortcutCreates=0;
globalThis.fetch=async(url,init={})=>{const u=new URL(url);if(u.pathname==='/drive/v3/files/existing-form')return respond(source);if(u.pathname==='/drive/v3/files'&&init.method==='POST'){const body=JSON.parse(init.body);assert.equal(body.mimeType,'application/vnd.google-apps.shortcut');assert.deepEqual(body.parents,['portal-templates']);assert.equal(body.shortcutDetails.targetId,source.id);shortcutCreates++;shortcut={...body,id:'shortcut-form'};return respond(shortcut)}if(u.pathname==='/drive/v3/files'){if(u.searchParams.get('q').includes("'portal-templates' in parents"))return respond({files:shortcut?[shortcut]:[]});return respond({files:[source,...(shortcut?[shortcut]:[]),{id:'portal-templates',name:'Templates',mimeType:'application/vnd.google-apps.folder'}]})}throw Error('Unexpected mutation/request '+u.pathname)};
await work.linkGoogleDocument(templateState,'templates-test@example.com',source.webViewLink,' Testing 1 ');assert.equal(templateState.documents[0].name,'Testing 1');assert.equal(shortcut.name,'Testing 1');await work.linkGoogleDocument(templateState,'templates-test@example.com',source.webViewLink);assert.equal(shortcutCreates,1);assert.equal(templateState.documents.length,1);assert.deepEqual(source.parents,['original-folder']);assert.equal(templateState.documents[0].id,source.id);assert.equal(templateState.documents[0].url,source.webViewLink);assert.ok(templateState.documents[0].parentIds.includes('portal-templates'));
await work.syncDrive(templateState,'templates-test@example.com');assert.equal(templateState.documents.length,1);assert.equal(library.filterLibrary(templateState.documents,'portal-templates')[0].type,'FORM');assert.equal(templateState.documents[0].templateShortcutId,'shortcut-form');assert.equal(templateState.documents[0].name,'Testing 1');assert.equal(store.loadLive('templates-test@example.com').documents[0].name,'Testing 1');await work.linkGoogleDocument(templateState,'templates-test@example.com',source.webViewLink,'Testing 2');await work.syncDrive(templateState,'templates-test@example.com');assert.equal(templateState.documents[0].name,'Testing 2');assert.equal(shortcutCreates,1);assert.equal(source.name,'Existing Form');await assert.rejects(()=>work.linkGoogleDocument(templateState,'templates-test@example.com',source.webViewLink,'   '),/document name/);
await assert.rejects(()=>work.linkGoogleDocument(templateState,'templates-test@example.com','https://docs.google.com/forms/d/e/public-id/viewform'),/responder link/);
source.parents=['portal-templates'];await work.addGoogleTemplate(templateState,'templates-test@example.com',source.id);assert.equal(shortcutCreates,1,'file already in Templates must not create a shortcut');globalThis.fetch=originalMockFetch;
console.log('PASS: linked Form creates one physical Templates shortcut, duplicate adds are idempotent, original file/link preserved, folder filtering survives sync, already-filed sources reused and responder IDs rejected.');
auth.forgetConnection();assert.equal(auth.readConnection(),null);
console.log('PASS: encrypted credentials/tokens, sessions, origin protection, account isolation, MIME PDF delivery, group deduplication, send idempotency, uncertain-send recovery, nested attachments, strict reply matching, Drive collection, duplicate prevention, manual review, persistence, token refresh, API host restriction and disconnect. No live Google calls were made.');
