// Offline hiring workflow integration test. Never uses live Google credentials.
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'jym-hiring-test-'));process.env.GOOGLE_DATA_DIR=path.join(temp,'data');
for(const name of ['portal-auth','request-security','google-auth','live-store','people-db','business-rules','shift-templates','employee-model','demo-store','google-workflow','department-availability','availability','floor-planning','floor-scheduler','roster','pay-rates','roster-model','timetable-model','person-forms','google-forms','hiring','hiring-model','hiring-candidates','hiring-sync'])fs.writeFileSync(path.join(temp,name+'.mjs'),ts.transpileModule(fs.readFileSync('lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`));
const load=n=>import(pathToFileURL(path.join(temp,n+'.mjs')));const auth=await load('google-auth'),store=await load('live-store','people-db','employee-model'),model=await load('hiring-model'),candidates=await load('hiring-candidates'),hiring=await load('hiring'),sheet=await load('hiring-sync'),work=await load('google-workflow','availability','timetable-model'),forms=await load('google-forms'),demo=await load('demo-store');
const email='hr@example.com';auth.saveConnection({accessToken:'fake',refreshToken:'fake',expiresAt:Date.now()+3600000,email,connectedAt:new Date().toISOString()});const s=store.loadLive(email);s.documents=[{id:'ack',type:'FORM',name:'Acknowledgement'},{id:'info',type:'FORM',name:'Employee information'}];let sendCount=0,createCount=0,updates=[],responses={},messages=[],failSheets=false;
const json=(d,status=200)=>new Response(JSON.stringify(d),{status});
globalThis.fetch=async(url,init={})=>{const u=new URL(url),p=u.pathname;if(u.hostname==='forms.googleapis.com'){const id=p.split('/')[3];return json(p.endsWith('/responses')?{responses:responses[id]||[]}:{items:[{title:'Confirmation',questionItem:{question:{questionId:'confirmation'}}}],settings:{emailCollectionType:'VERIFIED'},responderUri:`https://docs.google.com/forms/d/e/${id}/viewform`})}
 if(u.hostname==='sheets.googleapis.com'){if(failSheets)return json({},403);if(p.endsWith(':batchUpdate')){updates.push(JSON.parse(init.body));return json({})}return json({sheets:[{properties:{sheetId:0}}]})}
 if(p==='/drive/v3/files'&&init.method==='POST'){createCount++;assert.equal(JSON.parse(init.body).mimeType,'application/vnd.google-apps.spreadsheet');return json({id:'hiring-sheet'})}if(p==='/drive/v3/files')return json({files:[]});
 if(p.endsWith('/messages/send')){sendCount++;return json({id:'sent-'+sendCount,threadId:'thread-'+sendCount})}if(p.includes('/threads/'))return json({messages});if(p.endsWith('/messages'))return json({messages:[]});throw Error('Unexpected request '+url)};
const input={name:'Candidate A',email:'candidate@example.com',phone:'123',position:'=not a formula',notes:'HR reviewed',employment:'Casual'};const c=candidates.saveCandidate(s,email,input);assert.equal(model.hiringProgress(c,s.assignments).current,'Interview');assert.throws(()=>candidates.saveCandidate(s,email,input),/already has/);assert.throws(()=>candidates.updateHiringStage(s,email,c.id,'trial','Passed',''),/Complete/);
hiring.configureHiring(s,email,'ack','info');assert.throws(()=>hiring.configureHiring(s,email,'ack','ack'),/different/);await assert.rejects(()=>hiring.sendHiringForm(s,email,c.id,'ack'),/interview/);
candidates.updateHiringStage(s,email,c.id,'interview','Passed','');await hiring.sendHiringForm(s,email,c.id,'ack');await hiring.sendHiringForm(s,email,c.id,'ack');assert.equal(sendCount,1);assert.equal(model.hiringProgress(c,s.assignments).acknowledgement,'Waiting Response');assert.throws(()=>candidates.updateHiringStage(s,email,c.id,'trial','Passed',''),/Complete/);assert.throws(()=>candidates.saveCandidate(s,email,{...input,id:c.id,email:'other@example.com'}),/cannot change/);
const assignment=s.assignments.find(a=>a.id===c.ackAssignmentId);messages=[{id:'pdf-reply',threadId:'thread-1',payload:{headers:[{name:'from',value:c.email},{name:'subject',value:`Re: [${assignment.id}]`}],parts:[{filename:'reply.pdf',mimeType:'application/pdf',body:{data:demo.samplePdf('Wrong return').toString('base64url')}}]}}];await work.collectReplies(s,email);assert.equal(model.hiringProgress(c,s.assignments).acknowledged,false);assert.match(s.reviews[0].reason,/requires a Google Form/);messages=[];
responses.ack=[{responseId:'ack-response',respondentEmail:c.email,createTime:new Date(Date.now()+1000).toISOString()}];await forms.collectFormResponses(s,email);assert.equal(model.hiringProgress(c,s.assignments).acknowledged,true);assert.equal(model.hiringProgress(c,s.assignments).stage3,'Pending');assert.equal(model.hiringProgress(c,s.assignments).employeeInformation,'Not Started');await assert.rejects(()=>hiring.sendHiringForm(s,email,c.id,'form'),/trial/);candidates.updateHiringStage(s,email,c.id,'trial','Passed','');await hiring.sendHiringForm(s,email,c.id,'form');assert.equal(sendCount,2);responses.info=[{responseId:'info-response',respondentEmail:c.email,createTime:new Date(Date.now()+2000).toISOString()}];await forms.collectFormResponses(s,email);assert.equal(model.hiringProgress(c,s.assignments).final,'Ready for HR confirmation');assert.throws(()=>candidates.updateHiringStage(s,email,c.id,'trial','Failed',''),/completed/);
await sheet.syncHiringSheet(s,email,true);assert.equal(createCount,1);assert.equal(updates.length,1);const written=updates[0].requests[1].updateCells;assert.equal(written.rows[1].values[4].userEnteredValue.stringValue,'=not a formula');assert.equal(written.rows[1].values[12].userEnteredValue.stringValue,'Ready for HR confirmation');assert.equal(s.hiring.syncError,undefined);await sheet.syncHiringSheet(s,email,true);assert.equal(updates.length,1);
const rejected=candidates.saveCandidate(s,email,{...input,name:'Rejected B',email:'b@example.com'});candidates.updateHiringStage(s,email,rejected.id,'interview','Failed','');assert.equal(model.hiringProgress(rejected,s.assignments).final,'Rejected');await assert.rejects(()=>hiring.sendHiringForm(s,email,rejected.id,'ack'),/closed/);failSheets=true;await sheet.syncHiringSheet(s,email);assert.match(s.hiring.syncError,/Sheets API/);assert.equal(store.loadLive(email).hiring.candidates.length,2);failSheets=false;await sheet.syncHiringSheet(s,email);assert.equal(s.hiring.syncError,undefined);assert.equal(s.hiring.sheetRows,3);
candidates.deleteCandidate(s,email,rejected.id);await sheet.syncHiringSheet(s,email);assert.equal(updates.at(-1).requests[1].updateCells.range.endRowIndex,3);assert.equal(updates.at(-1).requests[1].updateCells.rows.length,2);assert.equal(s.hiring.candidates.length,1);assert.equal(model.hiringProgress(s.hiring.candidates[0],s.assignments).completed,true);assert.equal(createCount,1);
fs.rmSync(temp,{recursive:true,force:true});console.log('PASS: candidate CRUD, resume-stage defaults, duplicate email checks, interview/trial gating, two verified Form stages, email PDF cannot complete a Form, duplicate-send prevention, rejected and completed records, Sheet creation reuse, exact stage columns, formula-safe values, deleted-row clearing, sync failure persistence and recovery. All Google calls mocked.');
