import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'portal-finance-'));
process.env.GOOGLE_DATA_DIR=path.join(temp,'data');
try {
 for(const name of ['roster-month','trial-finance','monthly-finance','finance-model','floor-planning','roster-reports','roster-model','timetable-model','employee-model','pay-rates','business-rules','live-store','people-db','portal-auth','request-security','google-auth','shift-templates'])fs.writeFileSync(path.join(temp,name+'.mjs'),ts.transpileModule(fs.readFileSync('lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]\.\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`));
 const {checkoutWeek}=await import(pathToFileURL(path.join(temp,'finance-model.mjs'))),store=await import(pathToFileURL(path.join(temp,'live-store.mjs')));
 const s=store.loadLive('finance-test@example.com'),week='2026-09-28';
 const employee={id:'employee',personId:'person',sourceCandidateId:'candidate',hiringHistory:{id:'candidate'},name:'=Test Employee',email:'test@example.invalid',phone:'123',position:'Staff',type:'Part-Time',level:1,status:'Active',dateOfBirth:'2000-01-01',created:'2026-09-01',updated:'2026-09-01'};
 s.employees=[employee];
 const shift={id:'shift',employeeId:employee.id,employee:{...employee},date:week,start:'08:00',end:'19:00',breakMinutes:60,notes:'',created:'2026-09-01',updated:'2026-09-01',ruleVersion:1};
 s.rosters=[{weekStart:week,revision:1,shifts:[shift],manualAvailability:[],updated:'2026-09-01'}];
 let input={week,revision:1,previousId:'',confirmEarly:false,confirmReplace:false,reason:'Corrected hours'};
 assert.throws(()=>checkoutWeek(s,input,'tester','a',new Date('2026-10-04T13:59:59Z')),/has not ended/);
 const first=checkoutWeek(s,input,'tester','a',new Date('2026-10-04T14:00:00Z'));
 assert.equal(first.month,'2026-10');assert.equal(first.early,false);assert.equal(first.details[0].scheduledMinutes,600);assert.equal(first.rows[0].estimated,264.4);assert.equal(first.rows[0].unconfirmed,0);assert.equal(first.details[0].actualCents,26440);assert.ok(first.exports.finance.includes("'=Test Employee"));
 input.revision=s.rosters[0].revision;assert.equal(checkoutWeek(s,input,'tester','duplicate',new Date('2026-10-05')).id,'a');assert.equal(s.financeRecords.length,1);
 shift.end='20:00';s.rosters[0].revision++;assert.equal(first.details[0].shift.end,'19:00');assert.equal(first.rows[0].estimated,264.4);
 assert.throws(()=>checkoutWeek(s,input,'tester','b',new Date('2026-10-05')),/timetable changed/);
 input={...input,revision:s.rosters[0].revision};assert.throws(()=>checkoutWeek(s,input,'tester','b',new Date('2026-10-05')),/updated elsewhere/);
 input.previousId='a';assert.throws(()=>checkoutWeek(s,input,'tester','b',new Date('2026-10-05')),/new version/);
 input.confirmReplace=true;const second=checkoutWeek(s,input,'tester','b',new Date('2026-10-05'));assert.equal(second.version,2);assert.equal(second.rows[0].estimated,290.84);
 input.revision=s.rosters[0].revision;employee.dateOfBirth=undefined;input.previousId='b';const missing=checkoutWeek(s,input,'tester','c',new Date('2026-10-05'));assert.equal(missing.rows[0].estimated,null);assert.ok(missing.exports.payroll.includes('Employee age required'));assert.equal(second.rows[0].estimated,290.84);
 store.saveLive('finance-test@example.com',s);assert.deepEqual(store.loadLive('finance-test@example.com').financeRecords,JSON.parse(JSON.stringify(s.financeRecords)));assert.equal(store.loadLive('other@example.com').financeRecords,undefined);
 s.rosters[0].shifts=[{...shift,candidateId:'trial',employee:{...employee,type:'Candidate'}}];assert.throws(()=>checkoutWeek({...s,financeRecords:[]},{...input,previousId:''},'tester','d',new Date('2026-10-05')),/Candidate trials/);
 s.rosters[0].shifts=[shift];input.confirmEarly=true;input.previousId='c';shift.end='21:00';const early=checkoutWeek(s,input,'tester','d',new Date('2026-09-28'));assert.equal(early.early,true);
 // Partial checkout confirms only included employee shifts and never trials.
 const partial=structuredClone(s);partial.financeRecords=[];partial.rosters[0].revision=1;
 partial.rosters[0].shifts=[{...structuredClone(shift),actual:undefined,date:week,end:'19:00'}, {...structuredClone(shift),id:'later',actual:undefined,date:'2026-10-01'}, {...structuredClone(shift),id:'trial',actual:undefined,candidateId:'trial',employee:{...employee,type:'Candidate'}}];
 const partialInput={week,revision:1,previousId:'',confirmEarly:true,confirmReplace:false,through:week};
 const partialRecord=checkoutWeek(partial,partialInput,'owner','partial',new Date('2026-09-28'));
 assert.equal(partialRecord.details.length,1);assert.equal(partialRecord.details[0].actualMinutes,600);assert.equal(partial.rosters[0].shifts[1].actual,undefined);assert.equal(partial.rosters[0].shifts[2].actual,undefined);
 assert.equal(partialRecord.createdBy,'owner');assert.equal(partialRecord.early,true);
 partial.rosters[0].shifts[0].end='18:00';partial.rosters[0].revision++;
 const beforeRejected=JSON.stringify(partial);assert.throws(()=>checkoutWeek(partial,{...partialInput,revision:partial.rosters[0].revision,previousId:'partial',confirmReplace:true,reason:''},'owner','rejected'),/reason/);assert.equal(JSON.stringify(partial),beforeRejected);
 const revised=checkoutWeek(partial,{...partialInput,revision:partial.rosters[0].revision,previousId:'partial',confirmReplace:true,reason:'Employee left early'},'owner','revised');assert.equal(revised.details[0].actualMinutes,540);assert.equal(partialRecord.details[0].actualMinutes,600);
 console.log('PASS: checkout confirms timetable paid hours, early approval, partial cutoff, trial exclusion, atomic failure, revised hours and frozen historical approval.');
 process.env.PORTAL_ADMIN_EMAIL='test-admin@example.com';const portal=await import(pathToFileURL(path.join(temp,'portal-auth.mjs')));const portalToken=portal.createLogin({sub:'test-admin',email:process.env.PORTAL_ADMIN_EMAIL,email_verified:true});const auth=await import(pathToFileURL(path.join(temp,'google-auth.mjs')));
 auth.saveConnection({accessToken:'fake',refreshToken:'fake',expiresAt:Date.now()+60000,email:'finance-test@example.com',sessionHash:auth.hash('test-cookie'),sessionExpires:Date.now()+60000,connectedAt:new Date().toISOString()});
 fs.writeFileSync(path.join(temp,'route.mjs'),ts.transpileModule(fs.readFileSync('app/api/finance/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from ['"]@\/lib\/([^'"]+)['"]/g,(_,n)=>`from './${n}.mjs'`));
 const route=await import(pathToFileURL(path.join(temp,'route.mjs')));
 const headers={host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000','x-portal-request':'1',cookie:'jym_portal='+portalToken,get 'x-workspace-revision'(){return String(store.loadLive(auth.readConnection().email).workspaceRevision)}};
 let response=await route.GET(new Request('http://127.0.0.1:3000/api/finance',{headers}));assert.equal(response.status,200);assert.equal((await response.json()).records.length,3);
 response=await route.GET(new Request('http://127.0.0.1:3000/api/finance?id=a&kind=finance',{headers}));assert.deepEqual(Buffer.from(await response.arrayBuffer()),Buffer.from(first.exports.finance));assert.match(response.headers.get('Content-Disposition'),/v1/);
 assert.equal((await route.GET(new Request('http://127.0.0.1:3000/api/finance',{headers:{host:headers.host}}))).status,400);
 const form=new FormData();for(const [key,value] of Object.entries({week,revision:String(store.loadLive('finance-test@example.com').rosters[0].revision),previousId:'c',confirmReplace:'yes',confirmEarly:'yes',reason:'Correct public holiday',holidays:JSON.stringify([week])}))form.set(key,value);
 response=await route.POST(new Request('http://127.0.0.1:3000/api/finance',{method:'POST',headers,body:form}));assert.equal(response.status,200);assert.equal(store.loadLive('finance-test@example.com').financeRecords.length,4);assert.equal(store.loadLive('finance-test@example.com').rosters[0].revision,5);
 assert.equal((await route.POST(new Request('http://127.0.0.1:3000/api/finance',{method:'POST',headers,body:form}))).status,400);
 assert.equal((await route.POST(new Request('http://127.0.0.1:3000/api/finance',{method:'POST',headers:{...headers,origin:'http://evil.invalid'},body:form}))).status,400);
 console.log('PASS: authenticated Finance list/export/checkout, frozen export contents, holiday changes, stale checkout and cross-origin protection.');
 if(process.env.FINANCE_FIXTURE_PATH)fs.writeFileSync(process.env.FINANCE_FIXTURE_PATH,JSON.stringify(s));
 console.log('PASS: checkout date boundary (UTC+10), early confirmation, cross-month filing, 10-hour pay, frozen snapshots, duplicate submission, stale revisions, replacement confirmation, profile changes, missing rates, CSV injection protection, SQLite persistence, account isolation, trial exclusion.');
}finally{fs.rmSync(temp,{recursive:true,force:true});}
