'use client';
import {AvailabilityResultsView} from './availability-results-view';
import {departmentKey,departmentRecipients} from '@/lib/department-availability';
import {ShopWorkspacePicker} from './shop-workspace-picker';
import {restaurants,type Restaurant} from '@/lib/shift-templates';
import {AvailabilityResultsCalendar} from './availability-results-calendar';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Send,Users} from 'lucide-react';
import {PortalSidebar} from './portal-sidebar';
import {SidebarProvider,SidebarTrigger} from './ui/sidebar';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import type {LiveState} from '@/lib/live-store';
import {defaultSettings,nextMonday,localClock,dayAdd,type AvailabilityGroup} from '@/lib/timetable-model';
export function AvailabilityGroups({step:requestedStep=1}:{step?:1|2|3|4}){const [shop,setShop]=useState(''),[department,setDepartment]=useState('');const [state,setState]=useState<LiveState|null>(null),[week,setWeek]=useState(''),[group,setGroup]=useState<AvailabilityGroup>(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[enabled,setEnabled]=useState(false),[url,setUrl]=useState('');
 const direct=restaurants.includes(shop as Restaurant)&&['Floor','Kitchen'].includes(department);const step=direct&&requestedStep===1?3:requestedStep;
 async function refresh(){try{const r=await fetch('/api/live');const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);data.timetable??={settings:defaultSettings,weeks:[]};data.timetable.groups??={};for(const restaurant of restaurants)for(const d of ['Floor','Kitchen'] as const){const key=departmentKey(restaurant,d);if(!data.timetable.groups[key]){const old=Object.values(data.timetable.groups).filter(c=>c?.restaurant===restaurant&&c.department===d&&!c.profileRecipients);const inherited=old.length===1?old[0]:undefined;data.timetable.groups[key]={...inherited,restaurant,department:d,profileRecipients:true,employeeGroupId:undefined,name:restaurant+' · '+(d==='Floor'?'Front of house':'Back of house'),settings:{...(inherited?.settings||defaultSettings),enabled:false,employeeIds:departmentRecipients(data.employees||[],restaurant,d).map(e=>e.id)},configured:inherited?.configured||false,formSource:'custom'};}}setState(data);}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const params=new URLSearchParams(location.search);setShop(params.get('restaurant')||'');setDepartment(['Floor','Kitchen'].includes(params.get('department')||'')?params.get('department')!:'');setGroup(params.get('group')||(params.get('restaurant')&&params.get('department')?departmentKey(params.get('restaurant')!,params.get('department')!):''));const requested=params.get('week')||'';setWeek(/^\d{4}-\d{2}-\d{2}$/.test(requested)&&new Date(requested+'T00:00:00Z').getUTCDay()===1?requested:nextMonday(localClock(new Date(),'Etc/GMT-10').date));void refresh()},[]);
 const groups=Object.entries(state?.timetable?.groups||{}).filter(([,g])=>(shop==='legacy'?g?.employeeGroupId&&!g.profileRecipients:g?.profileRecipients&&g.restaurant===shop&&g.department===department)).map(([id])=>id);
 const label=(id:string)=>{const config=state?.timetable?.groups?.[id];return state?.groups.find(g=>g.id===config?.employeeGroupId)?.name||config?.name||'Employee group';};
 useEffect(()=>{if(step===2||modal||busy)return;const timer=setInterval(()=>void refresh(),30000);return()=>clearInterval(timer)},[step,modal,busy]);
 useEffect(()=>{if(state&&!groups.includes(group))setGroup(groups[0]||'')},[state,group,shop,department]);
 const config=state?.timetable?.groups?.[group],batch=state?.timetable?.weeks.find(w=>w.weekStart===week&&w.group===group),assignment=state?.assignments.find(a=>a.id===batch?.assignmentId),sourceGroup=state?.groups.find(g=>g.id===config?.employeeGroupId),employees=state?.employees||[],eligible=direct?departmentRecipients(employees,shop as Restaurant,department as 'Floor'|'Kitchen'):[...new Map((sourceGroup?.members||[]).map(p=>[p.email.toLowerCase(),p])).values()].flatMap(p=>{const e=employees.find(e=>e.email.toLowerCase()===p.email.toLowerCase());return e?.status==='Inactive'||shop!=='legacy'&&(!e||!e.assignedShops?.includes(shop as Restaurant))?[]:[{...p,id:e?.id||p.id}]});
 const settings=config?.settings||defaultSettings,availableGroups=state?.groups.filter(g=>!Object.values(state.timetable?.groups||{}).some(c=>c?.employeeGroupId===g.id&&c.restaurant===shop&&c.department===department))||[];
 const batchIds=batch?.employeeIds||[],sent=assignment?.recipients.filter(r=>r.delivery==='sent').length||0,replied=batch?.responses.length||0;
 async function run(action:string,data=new FormData(),extra:Record<string,string>={}){setBusy(true);setError('');setNotice('');data.set('action',action);data.set('group',group);if(shop!=='legacy'){data.set('restaurant',shop);data.set('department',department);}Object.entries(extra).forEach(([k,v])=>data.set(k,v));try{const r=await fetch('/api/availability',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state?.workspaceRevision??0)},body:data});const result=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(result.error);setState(result);if(action==='add-group'){const added=Object.entries(result.timetable?.groups||{}).find(([,g])=>g?.employeeGroupId===extra.employeeGroupId&&(shop==='legacy'?!g.restaurant:g.restaurant===shop&&g.department===department))?.[0]||'';setGroup(added);location.assign(pageUrl(2,added));}setModal('');setNotice(action==='prepare'?`${label(group)} form prepared. Preview it before sending.`:action==='start'||action==='send'||action==='retry'?'Send attempted. Review individual delivery results.':action==='custom-form'?'Form saved for this group. Supported front-of-house shift responses appear in Available time automatically after employees reply.':'Saved / refreshed.');}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 function pageUrl(target:number,g=group,w=week){return (target===1?'/availability':target===2?'/availability/setup':target===3?'/availability/results':'/availability/visualize')+'?'+new URLSearchParams({group:g,week:w,restaurant:shop,department})}
 function selectWeek(w:string){setWeek(w);history.replaceState(null,'',pageUrl(step,group,w))}
 if(!restaurants.includes(shop as Restaurant)&&shop!=='legacy')return <ShopWorkspacePicker area="availability" href="/availability" description="Choose a shop, then manage its Floor and Kitchen availability collections."/>;
 if(requestedStep===1&&shop!=='legacy'&&!department)return <SidebarProvider><PortalSidebar active="availability"/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows / Availability / {shop}</span></div></header><main className="availability-page"><a className="text-link" href="/availability">← All shops</a><div className="page-heading"><div><p className="eyebrow">WEEKLY AVAILABILITY</p><h1>{shop}</h1><p>Send availability forms and track replies by department.</p></div><a className="text-link" href="/employees">Manage employee profiles →</a></div>{error&&<p className="error">{error}</p>}<div className="availability-department-grid">{(['Floor','Kitchen'] as const).map(d=>{const people=departmentRecipients(state?.employees||[],shop as Restaurant,d),c=state?.timetable?.groups?.[departmentKey(shop,d)];return <section className="panel availability-department-card" key={d}><p className="eyebrow">{d}</p><h2>{d==='Floor'?'Front of house':'Back of house'}</h2><dl><div><dt>Eligible employees</dt><dd>{state?people.length:'—'}</dd></div></dl><p>{c?.configured&&c.customForm?c.settings.enabled?`Sends ${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][c.settings.sendDay??4]} at ${c.settings.sendTime} · UTC+10`:'Ready for manual sending':'Set your form and sending schedule once.'}</p><div className="availability-group-summary"><h3>Recipients from employee profiles</h3>{people.length?<ul>{people.map(p=><li key={p.id}><strong>{p.name}</strong><span>{p.email}</span></li>)}</ul>:<p>No eligible employees. Set their shop and department in Official Employee.</p>}</div><a className="primary-link" href={'/availability/results?'+new URLSearchParams({restaurant:shop,department:d})}>Open Result Patch <ArrowRight size={16}/></a><a className="text-link" href={'/availability/setup?'+new URLSearchParams({restaurant:shop,department:d})}>{c?.configured&&c.customForm?'Workflow settings':'Initial setup'}</a></section>})}</div><p className="performance-hint">Only active employees assigned to this shop and department are included. Each email appears once. Profiles with conflicting departments for the same email are excluded until corrected.</p></main></div></SidebarProvider>;

 if(direct&&step!==2){const people=(batch?batchIds:eligible.map(e=>e.id)).map(id=>{const p=assignment?.recipients.find(r=>r.id===id)||batch?.recipients?.find(r=>r.id===id)||eligible.find(r=>r.id===id)||{id,name:'Employee unavailable',email:''};const e=employees.find(e=>e.id===id||e.email.toLowerCase()===p.email.toLowerCase());return {...p,position:e?.position,phone:e?.phone,type:e?.type,level:e?.level||e?.casualLevel||1,profileId:e?.id};});return <AvailabilityResultsView shop={shop} department={department} week={week} batch={batch} people={people} assignment={assignment} busy={busy} error={error} loading={!state} onWeek={selectWeek} onRefresh={()=>void run('collect')}/>;}

 return <SidebarProvider><PortalSidebar active="availability" reviewCount={state?.reviews.filter(r=>!r.resolved).length||0}/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows / Availability Collection</span></div><span className="demo-badge">UTC+10</span></header><main className="availability-page" style={step===4?{maxWidth:'none'}:undefined}><div className="page-heading"><div><p className="eyebrow">WEEKLY AVAILABILITY</p><h1>{step===1?'Availability Collection':step===2?(config?.configured&&config.customForm?'Workflow settings':'Initial setup'):step===3?'Collection results':'Team availability'}</h1><p>{step===1?'Open a group to send a collection, track replies and view available time.':step===2?'Set the form and sending schedule once. Future weeks reuse these settings.':step===3?'Track replies and delivery for this weekly batch.':'Explore employee details and the shifts they can work.'}</p></div>{step===1&&state&&groups.length>0&&<Button disabled={busy||!availableGroups.length} onClick={()=>setModal('add')}>+ Add employee group</Button>}</div><div className="actions"><a className="text-link" href={'/availability?restaurant='+shop}>← Department overview</a><strong>{shop==='legacy'?'Previous unassigned collections':shop}</strong>{['Floor','Kitchen'].map(d=><a key={d} className={department===d?'primary-link':'text-link'} href={'/availability?'+new URLSearchParams({restaurant:shop,department:d})}>{d==='Floor'?'Front of house · Floor':'Back of house · Kitchen'}</a>)}</div><nav className="collection-steps" aria-label="Availability navigation">{!direct&&<a href={pageUrl(1)} aria-current={step===1?'page':undefined}>Groups</a>}{group&&<><a href={pageUrl(3)} aria-current={step===3?'page':undefined}>{direct?'Results':'Weekly collection'}</a>{!direct&&<a href={pageUrl(4)} aria-current={step===4?'page':undefined}>Available time</a>}<a href={pageUrl(2)} aria-current={step===2?'page':undefined}>Settings</a></>}</nav>{step>1&&groups.length>0&&<div className="availability-toolbar"><strong>{label(group)}</strong><Button variant="outline" disabled={busy||!week} onClick={()=>selectWeek(dayAdd(week,-7))} aria-label="Previous week"><ArrowLeft size={16}/></Button><strong>{week} — {week?dayAdd(week,6):''}</strong><Button variant="outline" disabled={busy||!week} onClick={()=>selectWeek(dayAdd(week,7))} aria-label="Next week"><ArrowRight size={16}/></Button>{step>=3&&<><Button variant="outline" disabled={busy||!state} onClick={()=>void run('collect')}>Check responses</Button><a className="text-link" href={'/timetable?week='+week+'&restaurant='+shop+'&category='+department}>Open timetable</a></>}</div>}
 {error&&!modal&&<p className="error" role="alert">{error}</p>}{notice&&<p className="demo-notice" role="status">{notice}</p>}
 {!direct&&step>1&&state&&<section className="demo-notice" aria-label="Automatic response tracking"><div><strong>{state.availabilityTracking?.enabled===false?'Automatic tracking is paused':sent?'Automatic response tracking is on':'Automatic tracking starts after sending'}</strong><p>{state.availabilityTracking?.enabled===false?'Background polling is disabled on this server. Use Check responses to sync manually.':`Sent forms are checked approximately every ${state.availabilityTracking?.intervalSeconds||60} seconds while the server is running. Results and Available time refresh automatically.`}</p><small>{batch?.lastChecked?`This collection last synced: ${new Date(batch.lastChecked).toLocaleString('en-GB',{timeZone:'Etc/GMT-10'})} UTC+10`:sent?'Waiting for the first background sync.':'Send this department’s form to begin tracking.'}</small>{state.availabilityTracking?.error&&<p role="alert">{state.availabilityTracking.error}</p>}</div></section>}
 {step===1&&groups.length>0&&<div className="collection-team-cards">{groups.map(g=>{const c=state?.timetable?.groups?.[g];return <a key={g} className="panel collection-team-card collection-group-link" href={pageUrl(c?.configured&&c?.customForm?3:2,g)}><div><Users size={24}/><strong>{label(g)}</strong><ArrowRight size={18}/></div><p>{state?.groups.find(x=>x.id===c?.employeeGroupId)?.members.length||0} group members · only active employees assigned to this shop receive new collections</p><small>{c?.configured&&c?.customForm?(c.settings.enabled?'Automatic weekly sending enabled':'Open weekly collection'):'Complete initial setup'}</small></a>})}</div>}

 {!state?<section className="panel empty"><p>{error||'Loading…'}</p><a href="/google">Google connection</a></section>:!groups.length?<section className="panel empty collection-start"><Users size={40}/><h2>{state.groups.length?'Start with an Employee Group':'Create your first Employee Group'}</h2><p>{state.groups.length?'Choose an existing group to set up its own availability form, scheduled sending and response tracking.':'There are no Employee Groups yet. Create a group and add its members, then return here to set up collection.'}</p>{state.groups.length?<Button disabled={busy} onClick={()=>setModal('add')}>+ Add employee group</Button>:<a className="primary-link" href="/?mode=live&view=groups">Create employee group</a>}</section>:step>1?<section className="panel collection-team-detail"><div className="collection-detail-heading"><div><h2>{step===2?'Saved form & weekly schedule':step===3?'Response overview':'Available time & employee details'}</h2><p>{direct?`${eligible.length} eligible employees from Official Employee profiles. Active status, assigned shop and department determine recipients.`:sourceGroup?`${eligible.length} current group members. Future collections use this group’s membership; existing batches keep their recipient list.`:'Source Employee Group was removed. Existing batches and replies remain available.'}</p></div></div>
 {config?.automationError&&<p className="error">{config.automationError}</p>}{batch?.error&&<p className="error">{batch.error}</p>}{batch?.responseErrors.map((e,i)=><p className="error" key={i}>{e}</p>)}
 {step===2&&<div className="collection-own-form">
 <section><h3>1. Add your Google Form</h3><p>Select a form from your library or paste its Google Forms editor link.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();void run('custom-form',new FormData(),{formUrl:url})}}><select aria-label="Google Form from library" value="" onChange={e=>setUrl(`https://docs.google.com/forms/d/${e.target.value}/edit`)}><option value="" disabled>Select from Document Library</option>{state.documents.filter(d=>d.type==='FORM').map(d=><option key={d.id} value={d.driveId||d.id}>{d.name}</option>)}</select><Input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://docs.google.com/forms/d/…/edit"/><Button disabled={busy||(!direct&&!sourceGroup)}>{config?.customForm?'Replace form':'Add form'}</Button></form>{config?.customForm&&<p className="collection-linked-form"><a href={config.customForm.url} target="_blank" rel="noreferrer">{config.customForm.name} ↗</a><Button variant="ghost" disabled={busy} onClick={()=>void run('remove-custom-form')}>Remove</Button></p>}<small>In Google Forms, enable Verified email collection and publish the form. In Share → General access → Responder view, choose Anyone with the link so personal Google accounts can respond without requesting access. For weekly reuse, turn off “Limit to 1 response” so employees can submit a new response each week. Your questions remain unchanged.</small></section>
 <section><h3>2. Weekly sending</h3><form key={group+':'+config?.configured+':'+settings.sendDay+':'+settings.sendTime+':'+settings.enabled} className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('group-settings',f,{employeeIds:JSON.stringify(eligible.map(p=>p.id)),formSource:'custom',enabled:f.get('enabled')==='yes'?'yes':'no'})}}><div className="roster-time-inputs"><label>Every<select name="sendDay" defaultValue={settings.sendDay??4}>{[1,2,3,4,5,6,0].map(d=><option key={d} value={d}>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d]}</option>)}</select></label><label>At · UTC+10<Input type="time" name="sendTime" required defaultValue={settings.sendTime}/></label></div><label className="live-confirm"><input type="checkbox" name="enabled" value="yes" defaultChecked={settings.enabled} onChange={e=>setEnabled(e.target.checked)} disabled={!config?.customForm}/>Enable weekly sending</label>{(enabled||settings.enabled)&&<label className="live-confirm"><input type="checkbox" name="confirmWeekly" value="yes"/>I confirm weekly email delivery to eligible employees in this shop and department.</label>}<small>Each collection asks for the following Monday–Sunday. The server must be running to send.</small><Button disabled={busy||(!direct&&!sourceGroup)}>Save schedule</Button></form></section>

 </div>}
 {(step===3||direct&&step===2&&config?.configured&&!!config.customForm)&&<> <section><h3>This week’s collection</h3>{direct&&<p className="performance-hint">Missing from this list? Open Official Employee and check Active status, assigned shops and Department. Duplicate emails with conflicting departments are excluded.</p>}<p>{week} — {week?dayAdd(week,6):''} · {batch?batchIds.length:eligible.length} recipients</p>{config?.configured&&config.customForm?<><p>{settings.enabled?`Automatic sending: ${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][settings.sendDay??4]} at ${settings.sendTime} · UTC+10`:'Manual sending. Recipients are selected from employee profiles.'}</p>{batch?.formUrl&&<a className="text-link" href={batch.formUrl} target="_blank" rel="noreferrer">Preview form ↗</a>} <Button disabled={busy||!(batch?batchIds.length:eligible.length)||!!assignment&&!assignment.recipients.some(r=>r.delivery==='ready'||r.delivery==='failed')} onClick={()=>{setError('');setModal('send')}}><Send size={16}/>{assignment?'Retry unsent invitations':'Send this week’s form'}</Button><p>{sent} sent / {batch?batchIds.length:eligible.length} recipients</p><a className="text-link" href={pageUrl(2)}>Edit saved settings</a></>:<a className="primary-link" href={pageUrl(2)}>Complete initial setup →</a>}</section>
 {!direct&&<><div className="collection-result-stats"><div><strong>{sent}</strong><span>Forms sent</span></div><div><strong>{replied} / {batchIds.length}</strong><span>Replies received</span></div><div><strong>{Math.max(0,batchIds.length-replied)}</strong><span>Awaiting reply</span></div></div>
 <div className="collection-progress-line"><strong>{sent} sent / {replied} replied / {batchIds.length} in this batch</strong><span>{batch?.lastChecked?`Last checked ${new Date(batch.lastChecked).toLocaleString('en-GB',{timeZone:'Etc/GMT-10'})} UTC+10`:'No response check yet'}</span></div><details className="collection-response-details"><summary>Individual replies &amp; delivery details</summary><div className="report-scroll"><table className="collection-response-table"><thead><tr><th>Employee</th><th>Delivery</th><th>Reply</th><th>Available hours</th></tr></thead><tbody>{(batch?batchIds:eligible.map(e=>e.id)).map(id=>{const e=batch?.recipients?.find(e=>e.id===id)||eligible.find(e=>e.id===id)||employees.find(e=>e.id===id),r=assignment?.recipients.find(r=>r.id===id),reply=batch?.responses.find(r=>r.employeeId===id);return <tr key={id}><td><strong>{r?.name||e?.name||'Employee unavailable'}</strong><small>{r?.email||e?.email}</small></td><td>{r?.delivery||'Not sent'}{r?.deliveryError&&<small className="error">{r.deliveryError}</small>}</td><td>{reply?reply.mappingError?'Replied · needs review':'Replied':batch?'Waiting':'No batch yet'}{reply&&<small>Updated {new Date(reply.submittedAt).toLocaleString('en-GB',{timeZone:'Etc/GMT-10'})} UTC+10</small>}</td><td>{reply?.mappingError?'Needs review':reply&&batch?.customForm&&!reply.shiftChoices?'Check responses to import':reply?(Object.values(reply.hours).reduce((n,a)=>n+a.length,0)*(reply.slotMinutes||batch?.settings.slotMinutes||60)/60).toFixed(1):'—'}</td></tr>})}</tbody></table></div></details>{!(batch?batchIds:eligible.map(e=>e.id)).length&&<div className="empty"><Users size={26}/><p>No employees selected for {label(group)}.</p><a className="text-link" href="/employees">Update employee profiles</a></div>}

 {!batch&&<div className="empty"><p>No collection for this week yet.</p><p>Use Send this week’s form above, or wait for your saved weekly schedule.</p></div>}</>}
 </>}
 {step===4&&(batch?<AvailabilityResultsCalendar key={batch.id} batch={batch} people={batchIds.map(id=>{const p=assignment?.recipients.find(e=>e.id===id)||batch?.recipients?.find(e=>e.id===id)||eligible.find(e=>e.id===id)||employees.find(e=>e.id===id)||{id,name:'Employee unavailable',email:''};const employee=employees.find(e=>e.id===id||e.email.toLowerCase()===p.email.toLowerCase());return {...p,phone:employee?.phone,position:employee?.position,type:employee?.type,level:employee?.level||employee?.casualLevel||1,profileId:employee?.id}})}/>:<div className="empty"><p>No collection for this week yet.</p><a className="text-link" href={pageUrl(3)}>Open weekly collection →</a></div>)}
 <div className="collection-page-footer"><a className="text-link" href={direct&&step!==4?'/availability?restaurant='+shop:pageUrl(step===3?1:step===4?3:1)}>← {step===4?'Weekly collection':direct?'Department overview':'Groups'}</a>{step<4&&<a className="primary-link" href={pageUrl(step+1)}>{step===2?'Open weekly collection →':'View available time →'}</a>}</div></section>:null}
 {step===1&&!!state?.timetable?.weeks.length&&<details className="panel collection-legacy"><summary>Previous collections &amp; history</summary><a className="text-link" href="/availability?restaurant=legacy">Open unassigned group collections →</a><p>Old forms, mock data and replies remain separate. Employees have not been automatically assigned to a team.</p><a className="text-link" href={'/availability/legacy?week='+week}>Open previous collections ↗</a></details>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="portal-dialog"><DialogTitle>{modal==='add'?'Add employee group':'Send '+label(group)+' availability form'}</DialogTitle><DialogDescription>{modal==='add'?'Select a group you already created in Employee Groups. An existing unassigned collection keeps its form and history when moved here; review its saved schedule before enabling sending. No email is sent by adding it.':'Recipients come from active Official Employee profiles matching this shop and department. Review the list before sending.'}</DialogDescription>{error&&<p className="error">{error}</p>}{modal==='add'?<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run('add-group',f,{employeeGroupId:String(f.get('employeeGroupId'))})}}><label>Employee Group<select name="employeeGroupId" required defaultValue=""><option value="" disabled>Choose a group</option>{availableGroups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.members.length} members</option>)}</select></label><Button disabled={busy||!availableGroups.length}>Add group to collection</Button><a className="text-link" href="/?mode=live&view=groups">Manage Employee Groups</a></form>:<form className="form-stack" onSubmit={e=>{e.preventDefault();void run('start',new FormData(),{weekStart:week,confirmLive:'yes'})}}><p>{label(group)} · {week} · {batch?batchIds.length:eligible.length} recipients</p><ul>{(batch?batchIds:eligible.map(p=>p.id)).map(id=><li key={id}>{assignment?.recipients.find(r=>r.id===id)?.email||batch?.recipients?.find(r=>r.id===id)?.email||eligible.find(e=>e.id===id)?.email||employees.find(e=>e.id===id)?.email}</li>)}</ul>{batch?.formUrl&&<a href={batch.formUrl} target="_blank" rel="noreferrer">Preview responder form ↗</a>}<label className="live-confirm"><input type="checkbox" required/>I confirm real email delivery to these employees. Sent or uncertain messages will not be resent.</label><Button disabled={busy}>Send {label(group)} form</Button></form>}</DialogContent></Dialog>
 </main></div></SidebarProvider>}
