'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,CalendarDays,Clock,Send,Check,Settings} from 'lucide-react';
import {PortalSidebar} from '@/components/portal-sidebar';
import {SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {LiveState} from '@/lib/live-store';
import {defaultSettings,eligibleEmployees,localClock,nextMonday,weekDates,dayAdd,hourLabel} from '@/lib/timetable-model';
const dayName=(date:string)=>new Date(date+'T00:00:00Z').toLocaleDateString('en-GB',{weekday:'short',timeZone:'UTC'});
export function AvailabilityWorkspace({calendar}:{calendar:boolean}){
 const [state,setState]=useState<LiveState|null>(null),[weekStart,setWeekStart]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[selected,setSelected]=useState<string[]>([]),[sendTime,setSendTime]=useState('08:00'),[enabled,setEnabled]=useState(false),[personFilter,setPersonFilter]=useState('all'),[customFormUrl,setCustomFormUrl]=useState('');
 async function refresh(){try{const r=await fetch('/api/live');const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);setState(data)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('week');const date=nextMonday(localClock(new Date(),'Etc/GMT-10').date);setWeekStart(requested&&/^\d{4}-\d{2}-\d{2}$/.test(requested)&&Number.isFinite(Date.parse(requested))&&new Date(requested+'T00:00:00Z').getUTCDay()===1?requested:date);void refresh()},[]);
 const settings=state?.timetable?.settings||defaultSettings,weeks=state?.timetable?.weeks.filter(w=>!w.group)||[],week=weeks.find(w=>w.weekStart===weekStart),assignment=state?.assignments.find(a=>a.id===week?.assignmentId),eligible=eligibleEmployees(state?.employees||[]),employees=state?.employees||[];
 const ids=week?.employeeIds||[],total=ids.length,sent=assignment?.recipients.filter(r=>r.delivery==='sent').length||0,replied=week?.responses.length||0,uncertain=assignment?.recipients.filter(r=>['sending','uncertain'].includes(r.delivery||'')).length||0;
 async function run(action:string,extra:Record<string,string>={},f=new FormData()){setBusy(true);setError('');setNotice('');try{f.set('action',action);Object.entries(extra).forEach(([k,v])=>f.set(k,v));const r=await fetch('/api/availability',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state?.workspaceRevision??0)},body:f});const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);setState(data);setModal('');setNotice(action==='send'||action==='retry'?'Send attempted. Check individual delivery results below.':action==='prepare'?'Weekly form prepared. Preview it, then send when ready.':action==='custom-form'?'Custom form saved. Response mapping is pending; built-in weekly forms remain unchanged.':action==='collect'?'Responses checked. The calendar shows available hours only.':'Settings saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 function configure(){setSelected(settings.employeeIds.filter(id=>eligible.some(e=>e.id===id)));setSendTime(settings.sendTime);setEnabled(settings.enabled);setModal('settings');setError('')}
 function selectWeek(value:string){setWeekStart(value);setPersonFilter('all');const url=new URL(window.location.href);url.searchParams.set('week',value);window.history.replaceState(null,'',url.pathname+url.search)}
 const name=(id:string)=>assignment?.recipients.find(r=>r.id===id)?.name||employees.find(e=>e.id===id)?.name||'Unavailable employee';
 const colors=['#e4f3ed','#e8effb','#f8ebdc','#f0e8f8','#f9e7ed','#e3f3f7'];
 return <SidebarProvider><PortalSidebar active={calendar?'timetable':'availability'} reviewCount={state?.reviews.filter(r=>!r.resolved).length||0}/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows</span><span>/</span><strong>{calendar?'Timetable Arrangement':'Availability Collection'}</strong></div><span className="demo-badge">UTC+10</span></header><main className="availability-page"><div className="page-heading"><div><p className="eyebrow">WORKFLOWS</p><h1>{calendar?'Timetable Arrangement':'Availability Collection'}</h1><p>{calendar?'See who is available throughout the week. Shifts are not assigned yet.':'Collect next week’s working availability from selected part-time and casual employees.'}</p></div><Button variant="outline" disabled={busy||!state} onClick={configure}><Settings size={16}/>Collection settings</Button></div>
 {error&&!modal&&<p className="error" role="alert">{error}</p>}{notice&&<p className="demo-notice" role="status">{notice}</p>}{state?.timetable?.automationError&&<p className="error" role="alert">Weekly automation: {state.timetable.automationError}</p>}{week?.error&&<p className="error" role="alert">{week.error}</p>}{week?.responseErrors.map((message,i)=><p className="error" role="alert" key={i}>{message} Ask the employee to correct their response.</p>)}
 <div className="availability-toolbar"><div className="week-navigation"><Button variant="outline" size="icon" aria-label="Previous week" disabled={!weekStart||busy} onClick={()=>selectWeek(dayAdd(weekStart,-7))}><ArrowLeft size={16}/></Button><strong>{weekStart} — {weekStart?dayAdd(weekStart,6):''}</strong><Button variant="outline" size="icon" aria-label="Next week" disabled={!weekStart||busy} onClick={()=>selectWeek(dayAdd(weekStart,7))}><ArrowRight size={16}/></Button></div>{weeks.length>0&&<Select value={week?.id||'none'} onValueChange={id=>{const w=weeks.find(w=>w.id===id);if(w)selectWeek(w.weekStart)}}><SelectTrigger aria-label="Existing weekly collection"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Choose collected week</SelectItem>{weeks.map(w=><SelectItem key={w.id} value={w.id}>Week of {w.weekStart}</SelectItem>)}</SelectContent></Select>}<Button variant="outline" disabled={busy||!week?.assignmentId} onClick={()=>void run('collect')}>Check responses</Button><a className="text-link" href={`${calendar?'/availability':'/timetable'}?week=${weekStart}`}>{calendar?'Open response tracking':'Open main timetable'} <ArrowUpRight size={14}/></a></div>
 {!state?<section className="panel empty"><p>{error?'Connect Google to use this workflow.':'Loading…'}</p><a href="/google" className="text-link">Google connection</a></section>:!week?<section className="panel empty"><CalendarDays size={36}/><h2>No collection for this week</h2><p>Select employees in Collection settings, then prepare the weekly Google Form. Each day offers hourly choices from 08:00 to 20:00 and Not available.</p><Button disabled={busy||!settings.employeeIds.length} onClick={()=>void run('prepare',{weekStart})}>{busy?'Preparing…':'Prepare this week’s form'}</Button>{!eligible.length&&<a href="/employees" className="text-link">Add eligible Official Employees through Hiring Process first</a>}</section>:<>
 <section className="performance-progress">{[{label:'Selected employees',count:total,icon:CalendarDays},{label:'Forms sent',count:sent,icon:Send},{label:'Employees replied',count:replied,icon:Check}].map(({label,count,icon:Icon})=><article className="panel performance-metric" key={label}><div className="metric-label">{label}<Icon size={20}/></div><div className="metric-value"><strong>{count}</strong><span>/ {total}</span></div><progress aria-label={label} value={count} max={total||1}/></article>)}</section>
 <div className="live-actions">{week.sample&&<p className="demo-notice">Mock data · Sample availability for testing only. No emails were sent. <Button variant="outline" disabled={busy} onClick={()=>void run('remove-sample',{id:week.id})}>Clear sample week</Button></p>}{!week.sample&&!week.formReady&&<Button disabled={busy} onClick={()=>void run('prepare',{weekStart})}>Retry form preparation</Button>}{week.formId&&<a className="text-link" href={`https://docs.google.com/forms/d/${week.formId}/edit`} target="_blank" rel="noreferrer">View weekly form <ArrowUpRight size={14}/></a>}{week.formReady&&(!assignment||assignment.recipients.some(r=>r.delivery==='ready'||r.delivery==='failed'))&&<Button disabled={busy} onClick={()=>setModal('send')}><Send size={16}/>{assignment?'Review unsent / failed emails':'Review & send form'}</Button>}<span className="muted">{total-replied} not yet replied{week.lastChecked?` · Last checked ${new Date(week.lastChecked).toLocaleTimeString()}`:''}</span>{uncertain>0&&<p className="error">{uncertain} delivery result(s) are uncertain. Check responses to reconcile Gmail before retrying.</p>}</div>
 {calendar?<><div className="calendar-legend"><span className="availability-only-label">AVAILABILITY ONLY · NOT A CONFIRMED ROSTER</span><Select value={personFilter} onValueChange={setPersonFilter}><SelectTrigger aria-label="Filter employee availability"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All selected employees</SelectItem>{ids.map(id=><SelectItem key={id} value={id}>{name(id)}</SelectItem>)}</SelectContent></Select></div>{!replied&&<p className="demo-notice">No valid replies yet. Empty cells mean no availability has been received, not confirmed time off.</p>}<div className="availability-calendar" role="region" aria-label="Weekly employee availability calendar" tabIndex={0}><table><thead><tr><th>UTC+10</th>{weekDates(weekStart).map(date=><th key={date}>{dayName(date)}<span>{date.slice(5)}</span></th>)}</tr></thead><tbody>{Array.from({length:12},(_,i)=>i+8).map(hour=><tr key={hour}><th>{hourLabel(hour)}<span>– {hourLabel(hour+1)}</span></th>{weekDates(weekStart).map(date=>{const available=week.responses.filter(r=>(personFilter==='all'||r.employeeId===personFilter)&&r.hours[date]?.includes(hour));return <td key={date}>{available.map(reply=><div className="availability-person" key={reply.employeeId} style={{backgroundColor:colors[Math.max(0,ids.indexOf(reply.employeeId))%colors.length]}} title={`${name(reply.employeeId)}: available ${date} ${hourLabel(hour)}–${hourLabel(hour+1)} UTC+10`}>{name(reply.employeeId)}</div>)}</td>})}</tr>)}</tbody></table></div><p className="performance-hint">A name in a time slot means the employee said they can work that hour. Employees who selected Not available all week still count as replied. No shifts or payroll hours are created.</p></>:<section className="panel hiring-table"><div className="collection-table-heading"><h2>Employee responses</h2><p>Track who has replied before arranging the week.</p></div><Table><TableHeader><TableRow><TableHead>Employee</TableHead><TableHead>Email delivery</TableHead><TableHead>Response</TableHead><TableHead>Available hours</TableHead></TableRow></TableHeader><TableBody>{ids.map(id=>{const r=assignment?.recipients.find(r=>r.id===id),reply=week.responses.find(r=>r.employeeId===id);const hours=reply?Object.values(reply.hours).reduce((sum,values)=>sum+values.length,0):null;return <TableRow key={id}><TableCell><strong>{name(id)}</strong><small className="block muted">{r?.email||employees.find(e=>e.id===id)?.email}</small></TableCell><TableCell>{r?.delivery||'Not sent'}{r?.deliveryError&&<p className="error">{r.deliveryError}</p>}</TableCell><TableCell><span className={'status '+(reply?'completed':'pending')}>{reply?'Replied':'Waiting'}</span>{reply&&<small className="block muted">{new Date(reply.submittedAt).toLocaleString('en-GB',{timeZone:'Etc/GMT-10'})} UTC+10</small>}</TableCell><TableCell>{hours===null?'—':`${hours} hours${hours===0?' · unavailable all week':''}`}</TableCell></TableRow>})}</TableBody></Table></section>}
 </>}
 <details className="panel collection-options"><summary>Form &amp; automation settings <span>Thursday · {settings.sendTime} · UTC+10 · {settings.enabled?'Enabled':'Off'}</span></summary> <div className="availability-schedule"><Clock size={19}/><div><strong>Every Thursday · {settings.sendTime} · fixed UTC+10</strong><p>{settings.enabled?`Weekly sending enabled for ${settings.employeeIds.length} selected employees.`:'Weekly sending is off. Select employees and enable it in Collection settings.'} Keep the local server running. If it starts late on Thursday, it catches up that day; it does not send missed weeks on Friday.</p></div></div>
 {!calendar&&<section className="panel custom-availability-form"><h2>Your own Google Form</h2><p>Design the form in Google Forms (stored in Drive), then select it from the document library or paste its editor link here.</p><form onSubmit={e=>{e.preventDefault();void run('custom-form',{formUrl:customFormUrl})}}><select aria-label="Choose Google Form from library" value="" onChange={e=>setCustomFormUrl(`https://docs.google.com/forms/d/${e.target.value}/edit`)}><option value="" disabled>Select a library form…</option>{state?.documents.filter(d=>d.type==='FORM').map(d=><option key={d.id} value={d.driveId||d.id}>{d.name}</option>)}</select><Input aria-label="Google Form editor or Drive link" type="url" required placeholder="https://docs.google.com/forms/d/…/edit" value={customFormUrl} onChange={e=>setCustomFormUrl(e.target.value)}/><Button disabled={busy||!state}>Save custom form</Button></form>{state?.timetable?.customForm&&<p><a className="text-link" href={state.timetable.customForm.url} target="_blank" rel="noreferrer">{state.timetable.customForm.name} ↗</a> · Saved — response mapping pending. <Button variant="ghost" disabled={busy} onClick={()=>void run('remove-custom-form')}>Remove selection</Button></p>}<p>Custom form sending and calendar import will be connected after its question design is agreed. The built-in weekly form remains available below. <a className="text-link" href="/?mode=live&view=library">Add a Google Form to the document library</a></p></section>}
</details>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy)setModal('')}}><DialogContent className="portal-dialog"><DialogTitle>{modal==='settings'?'Weekly availability settings':'Confirm weekly form delivery'}</DialogTitle><DialogDescription>{modal==='settings'?'Settings apply to future weeks. Existing weekly collections keep their original selected employees.':'Each selected employee receives a separate Gmail message with the form for this specific week.'}</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}
 {modal==='settings'?<form className="form-stack" onSubmit={e=>{e.preventDefault();void run('settings',{employeeIds:JSON.stringify(selected),sendTime,enabled:enabled?'yes':'no'},new FormData(e.currentTarget))}}><label>Thursday send time · fixed UTC+10<Input type="time" required value={sendTime} onChange={e=>setSendTime(e.target.value)}/></label><p>Next week means Monday to Sunday. Available hours: 08:00–20:00, in one-hour blocks.</p><fieldset><legend>Active Part-time / Casual employees</legend>{eligible.map(e=><label key={e.id} className="group-option"><Checkbox checked={selected.includes(e.id)} onCheckedChange={checked=>setSelected(checked?[...selected,e.id]:selected.filter(id=>id!==e.id))}/><span>{e.name}<small>{e.email} · {e.type}{e.casualLevel?` Level ${e.casualLevel}`:''}</small></span></label>)}{!eligible.length&&<p>No eligible employees yet.</p>}</fieldset><label className="group-option"><Checkbox checked={enabled} onCheckedChange={v=>setEnabled(v===true)}/><span>Enable weekly Thursday sends</span></label>{enabled&&<label className="live-confirm"><input type="checkbox" name="confirmWeekly" value="yes" required/>I authorize real Gmail delivery every Thursday to the selected employees while the server is running.</label>}<Button disabled={busy}>{busy?'Saving…':'Save collection settings'}</Button></form>:week&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(assignment?'retry':'send',{id:week.id,confirmLive:'yes'})}}><p>Week: <strong>{weekStart} – {dayAdd(weekStart,6)}</strong></p><p>Recipients: {ids.map(id=>`${name(id)} (${assignment?.recipients.find(r=>r.id===id)?.email||employees.find(e=>e.id===id)?.email||'unavailable'})`).join(', ')}</p>{week.formUrl&&<a className="text-link" target="_blank" rel="noreferrer" href={week.formUrl}>Preview responder form <ArrowUpRight size={14}/></a>}<p>Only active employees whose messages are unsent or definitely failed will be sent an email. Confirmed and uncertain sends are skipped.</p><label className="live-confirm"><input type="checkbox" required/>I confirm sending this availability form by real Gmail.</label><Button disabled={busy}>Confirm send</Button></form>}
 </DialogContent></Dialog></main></div></SidebarProvider>
}
