'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,FolderOpen,Download,CheckCircle2} from 'lucide-react';
import {PortalSidebar} from './portal-sidebar';
import {SidebarProvider,SidebarTrigger} from './ui/sidebar';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {payrollBreakdown,paymentStatus,type MonthlyReport,type MonthEmployee} from '@/lib/monthly-finance';
import {localClock} from '@/lib/timetable-model';
const hours=(n:number)=>(n/60).toFixed(2);
const money=(n:number|null)=>n===null?'Needs review':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100);
const monthName=(month:string)=>new Date(month+'-01T00:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'});
const stamp=(value:string)=>new Date(value).toLocaleString('en-GB',{timeZone:'Etc/GMT-10'});
type PaymentForm={employeeId:string;name:string;amount:string;payrun:string;cash:string;kind:'payment'|'recovery';date:string;reference:string;requestId:string};
export function FinanceWorkspace({restaurant}:{restaurant?:import('@/lib/shift-templates').Restaurant}){
 const scope=restaurant?'&restaurant='+restaurant:'&legacy=1';
 const [payrollInfo,setPayrollInfo]=useState<{employeeId:string;name:string;payrollerName:string;remarks:string}|null>(null);
 const [months,setMonths]=useState<string[]>([]),[year,setYear]=useState(''),[month,setMonth]=useState(''),[report,setReport]=useState<MonthlyReport|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[version,setVersion]=useState('');
 const [settling,setSettling]=useState(false),[reason,setReason]=useState(''),[payment,setPayment]=useState<PaymentForm|null>(null),[confirmed,setConfirmed]=useState(false);
 const request=useRef(0);const [workspaceRevision,setWorkspaceRevision]=useState(0);
 const load=useCallback(async(selectedMonth:string,selectedYear:string)=>{
  const ticket=++request.current;setLoading(true);setError('');setVersion('');
  try{
   const response=await fetch((selectedMonth?'/api/finance?month='+selectedMonth:'/api/finance?')+scope);
   const data=await response.json() as {workspaceRevision?:number;error?:string;months?:string[];report?:MonthlyReport};
   if(!response.ok)throw Error(data.error);
   if(ticket!==request.current)return;
   setWorkspaceRevision(data.workspaceRevision||0);setMonth(selectedMonth);setYear(selectedMonth.slice(0,4)||selectedYear);setReport(data.report||null);if(data.months)setMonths(data.months);
  }catch(e){if(ticket===request.current)setError((e as Error).message);}finally{if(ticket===request.current)setLoading(false);}
 },[scope]);
 useEffect(()=>{
  const sync=async()=>{const params=new URLSearchParams(location.search);let selected=params.get('month')||'';const id=params.get('id');
   if(id&&!selected){try{const r=await fetch('/api/finance?id='+encodeURIComponent(id));const d=await r.json() as {month?:string};if(r.ok)selected=d.month||'';}catch{/* Show normal Finance navigation if an old link cannot resolve. */}}
   await load(selected,params.get('year')||'');
  };
  void sync();window.addEventListener('popstate',sync);return()=>{window.removeEventListener('popstate',sync);};
 },[load]);
 function navigate(selectedMonth='',selectedYear=''){setNotice('');history.pushState(null,'',selectedMonth?'/finance?month='+selectedMonth+scope:selectedYear?'/finance?year='+selectedYear+scope:'/finance?'+scope.slice(1));void load(selectedMonth,selectedYear);}
 async function mutate(action:string,fields:Record<string,string>){
  setBusy(true);setError('');
  try{const form=new FormData();form.set('action',action);form.set('month',month);if(restaurant)form.set('restaurant',restaurant);for(const [key,value] of Object.entries(fields))form.set(key,value);
   const response=await fetch('/api/finance',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(workspaceRevision)},body:form});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error);
   setSettling(false);setPayment(null);setPayrollInfo(null);setNotice(action==='payroll-info'?'Payroll details saved.':action==='settle'?'Monthly settlement saved. You can now record completed payments.':'Payment record saved.');await load(month,year);
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const selected=report?.history.find(r=>r.id===version),historical=!!selected&&selected.id!==report?.settlement?.id;
 const rows=selected?.rows||report?.rows||[],details=selected?.details||report?.details||[];
 const payrollLines=payrollBreakdown(rows,details,report?.payments||[]);
 const shownHandoffs=selected?(report?.handoffHistory||[]).filter(h=>selected.details.some(p=>p.handoffId===h.id)):report?.handoffs||[];
 const paid=(id:string)=>report?.payments.filter(p=>p.employeeId===id).reduce((n,p)=>n+p.amountCents,0)||0;
 const balance=(row:MonthEmployee)=>row.payableCents===null?null:row.payableCents-paid(row.employeeId);
 const total=rows.some(r=>r.payableCents===null)?null:rows.reduce((n,r)=>n+(r.payableCents||0),0);
 const canSettle=!!report&&(!restaurant||!!report.checkout)&&!report.legacyPayments.length&&!historical&&report.monthEnded&&!report.pending.length&&!!rows.length&&total!==null&&(!report.settlement||report.changed)&&!selected;
 const canPay=!!report?.settlement&&!report.changed&&!historical;
 const exportVersion=selected?.id||(!report?.changed?report?.settlement?.id:'');
 const download=(kind:string)=>`/api/finance?month=${month}&kind=${kind}${scope}${exportVersion?'&settlement='+exportVersion:''}`;
 function openPayment(row:MonthEmployee){const outstanding=balance(row)||0;setError('');setConfirmed(false);setPayment({employeeId:row.employeeId,name:row.name,amount:(Math.abs(outstanding)/100).toFixed(2),payrun:'',cash:'',kind:outstanding<0?'recovery':'payment',date:localClock(new Date(),'Etc/GMT-10').date,reference:'',requestId:crypto.randomUUID()});}
 const years=[...new Set([...months.map(m=>m.slice(0,4)),String(new Date().getFullYear())])].sort().reverse();
 return <SidebarProvider><PortalSidebar active="finance"/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows / Finance / {restaurant||'Legacy combined'}</span></div><span className="demo-badge">AUD · UTC+10</span></header>
 <main className="availability-page finance-workspace">
  <div className="page-heading"><div><p className="eyebrow">MONTHLY FINANCE</p><h1>{month?monthName(month):year||'Finance'}</h1><p>Monthly monthly Timetable checkout hands over approved work. Finance settles this shop’s roster month and tracks payments.</p></div><div className="actions"><a className="primary-link" href={'/finance?view=trial'+scope}>Trial daily settlements</a><a className="text-link" href={'/timetable?restaurant='+(restaurant||'all')}>Open timetable</a></div></div>
  <a className="text-link" href="/finance">← Choose shop</a>{!!report?.legacyPayments.length&&<p className="error">This month contains previous combined payments. They are preserved in legacy history and are not assigned to either shop. Reconcile them before recording shop payments.</p>}<nav className="finance-breadcrumb" aria-label="Finance folders"><Button variant="ghost" disabled={busy} onClick={()=>navigate()}>Finance</Button>{year&&<><span>/</span><Button variant="ghost" disabled={busy} onClick={()=>navigate('',year)}>{year}</Button></>}{month&&<><span>/</span><strong>{monthName(month)}</strong></>}</nav>
  <div className="finance-month-toolbar"><label>Open month<Input aria-label="Open month" type="month" value={month} disabled={busy||loading} onChange={e=>{if(e.target.value)navigate(e.target.value)}}/></label>{month&&<Button variant="outline" disabled={busy||loading} onClick={()=>void load(month,year)}>Refresh report</Button>}</div>
  {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="demo-notice" role="status">{notice}</p>}
  {loading?<section className="panel empty">Loading Finance…</section>:!month?<><p className="performance-hint">Roster months include complete Monday–Sunday weeks, assigned by Thursday. Submit the shop’s monthly checkout from Timetable.</p><div className="finance-folders">{(year?Array.from({length:12},(_,i)=>`${year}-${String(i+1).padStart(2,'0')}`):years).map(value=><button key={value} className="panel finance-folder" onClick={()=>year?navigate(value):navigate('',value)}><FolderOpen/><h2>{year?monthName(value):value}</h2><p>{year?(months.includes(value)?'Open monthly report':'View month'):'Monthly reports'}</p><ArrowRight size={18}/></button>)}</div></>:report&&<>
   {restaurant&&<p className="demo-notice">{report.checkout?`Monthly checkout v${report.checkout.version} · ${stamp(report.checkout.createdAt)} · ${report.checkout.createdBy}`:'No monthly checkout yet. Submit this roster month from Timetable.'}</p>}<div className="finance-record-meta"><strong>{report.dates[0]} — {report.dates.at(-1)} · {historical?'Historical settlement':report.changed?'Changes awaiting reconciliation':report.settlement?'Settled':'Draft'}</strong>{report.history.length>0&&<label>Report version <select aria-label="Report version" value={version} disabled={busy} onChange={e=>setVersion(e.target.value)}><option value="">Current monthly report</option>{report.history.map(r=><option key={r.id} value={r.id}>Settlement v{r.version} · {stamp(r.createdAt)}</option>)}</select></label>}</div>
   {historical&&<p className="demo-notice">Historical amounts are frozen. Payment totals show the current ledger; record payments from the current report.</p>}
   {report.changed&&!selected&&<p className="demo-notice">The timetable handover differs from the last settlement. Review the differences and confirm a revised month. Previous settlements and payment records are retained.</p>}
   {!!report.pending.length&&<details className="panel finance-pending" open><summary>{report.pending.length} shift changes need monthly Timetable checkout</summary><p>These changes are not included in the handed-over totals. The roster owner must review and submit them before month close.</p><div className="report-scroll"><table><thead><tr><th>Work date</th><th>Employee</th><th>Handover issue</th><th>Next step</th></tr></thead><tbody>{report.pending.map((p,i)=><tr key={p.weekStart+p.date+i}><td>{p.date}</td><td>{p.name}</td><td>{p.reason}</td><td><a className="text-link" href={`/timetable?week=${p.weekStart}&restaurant=all`}>Review timetable →</a></td></tr>)}</tbody></table></div></details>}
   <div className="finance-metrics"><section className="panel"><span>Employees handed over</span><strong>{rows.length}</strong></section><section className="panel"><span>Confirmed actual hours</span><strong>{hours(rows.reduce((n,r)=>n+r.actualMinutes,0))} h</strong></section><section className="panel"><span>Nett Total</span><strong>{money(total)}</strong></section><section className="panel"><span>Payments recorded, net</span><strong>{money(report.payments.reduce((n,p)=>n+p.amountCents,0))}</strong></section></div>
   {!!rows.reduce((n,r)=>n+r.unconfirmed,0)&&<p className="error">{rows.reduce((n,r)=>n+r.unconfirmed,0)} shifts were handed over before checkout confirmed working hours automatically. Review the Timetable and check out again to confirm its hours before settling.</p>}
   {!!report.overtimeWarnings&&<p className="error">{report.overtimeWarnings} shifts have overtime warnings. Review payroll separately; base pay excludes overtime premiums.</p>}
   <section className="panel roster-list"><div className="finance-heading"><div><h2>Monthly payroll report</h2><p>Rates × approved paid hours, grouped by shop and day type. Nett Total is the system-calculated amount before any external payroll adjustments.</p></div><div className="actions"><a className="primary-link" href={download('payroll')}><Download size={16}/>Payroll report CSV</a><a className="text-link" href={download('details')}>Daily details CSV</a></div></div>
   {!rows.length&&<div className="finance-empty"><h3>No work handed over for this month</h3><p>Use Checkout month in Timetable. Only submitted dates appear here.</p></div>}
   {!!rows.length&&<div className="report-scroll payroll-report-scroll"><table className="payroll-month-table"><thead><tr>{['Shop','Name / employment','Day','Rate','Hour','Total','Nett Total','Payroller Name','Payrun','Cash','Final pay','Status','Remarks','Annual Leave','Sick Leave','Total Hour'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{payrollLines.map((line,index)=><tr key={index} className={line.first?'payroll-person-start':''}><td>{line.shop}</td><td><strong>{line.name}</strong><small>{line.employment}</small></td><td>{line.dayType}</td><td>{line.rateCents===null?'—':money(line.rateCents)}</td><td>{hours(line.minutes)}</td><td>{money(line.totalCents)}</td><td>{line.first?money(line.row.payableCents):''}</td><td>{line.first&&<><span>{line.row.payrollerName||'Not set'}</span><Button size="sm" variant="ghost" disabled={busy||historical||!!selected} onClick={()=>{setError('');setPayrollInfo({employeeId:line.employeeId,name:line.name,payrollerName:line.row.payrollerName||'',remarks:line.row.remarks||''})}}>Edit</Button></>}</td><td>{line.first?money(line.payrun):''}</td><td>{line.first?money(line.cash):''}</td><td>{line.first?line.finalPay||'Not paid':''}</td><td>{line.first&&<><span>{paymentStatus(line.row,report.payments)}</span>{line.other!==0&&<small>Other / legacy: {money(line.other)}</small>}<Button size="sm" variant="outline" disabled={busy||!canPay||balance(line.row)===null||balance(line.row)===0} onClick={()=>openPayment(line.row)}>{(balance(line.row)||0)<0?'Record recovery':'Record payment'}</Button></>}</td><td className="payroll-remarks">{line.first?line.row.remarks||'—':''}</td><td>{line.first?(line.row.annualHours??0).toFixed(4)+' h':''}</td><td>{line.first?(line.row.sickHours??0).toFixed(4)+' h':''}</td><td>{line.first?hours(line.row.actualMinutes):''}</td></tr>)}</tbody></table></div>}
   <p className="performance-hint">Payrun and Cash show manually recorded payments. Final pay shows the latest payment date; every payment remains in the history. Annual Leave and Sick Leave show hours earned from this month’s approved work using your configured rules. Nett Total excludes tax, super, overtime premiums and leave payouts. Missing rates require review.</p>
   <details><summary>Daily / weekly details and reconciliation</summary>
   {rows.map(row=>{const outstanding=balance(row),employeeDetails=details.filter(p=>p.shift.employeeId===row.employeeId),old=report.settlement?.rows.find(r=>r.employeeId===row.employeeId),delta=row.payableCents!==null&&old?.payableCents!==null?row.payableCents-(old?.payableCents||0):null;
    const status=outstanding===null?'Needs review':outstanding<0?'Overpaid — recovery needed':outstanding===0?(row.payableCents===0?'No payment due':'Paid'):paid(row.employeeId)>0?'Part paid':'Unpaid';
    return <div className="finance-employee" key={row.employeeId}><details className="finance-person"><summary><span><strong>{row.name}</strong><small>{row.types.join(' / ')||'No remaining shifts'}{row.sample?' · MOCK':''}</small></span><span>{row.days} days · {hours(row.actualMinutes)} h confirmed<small>{hours(row.scheduledMinutes)} h scheduled</small></span><strong>{money(row.payableCents)}<small>Confirmed base pay</small></strong><span>Daily details ↓</span></summary>
    <p className="error">{row.issues.join('; ')}</p><div className="report-scroll"><table><thead><tr><th>Date</th><th>Scheduled hours</th><th>Confirmed hours</th><th>Confirmed base pay</th></tr></thead><tbody>{report.dates.map(date=>{const day=employeeDetails.filter(p=>p.shift.date===date);return <tr key={date}><td>{date}</td><td>{hours(day.reduce((n,p)=>n+p.scheduledMinutes,0))}</td><td>{day.some(p=>!p.shift.actual)?'Needs confirmation':hours(day.reduce((n,p)=>n+p.actualMinutes,0))}</td><td>{!day.length?'—':money(day.some(p=>p.actualCents===null)?null:day.reduce((n,p)=>n+(p.actualCents||0),0))}</td></tr>})}</tbody></table></div>
    <details className="finance-actual"><summary>Shift details &amp; handover responsibility</summary><div className="report-scroll"><table><thead><tr><th>Date / shop</th><th>Scheduled work</th><th>Actual work</th><th>Rate / day</th><th>Checkout by</th></tr></thead><tbody>{employeeDetails.map(p=><tr key={p.weekStart+p.shift.id}><td>{p.shift.date}<small>{p.shift.restaurant||'Unclassified'} / {p.shift.category||'Unclassified'}</small></td><td>{p.shift.start}–{p.shift.end}<small>{p.shift.breakMinutes} min unpaid</small></td><td>{p.shift.actual?`${p.shift.actual.start}–${p.shift.actual.end}`:'Not confirmed'}<small>{p.shift.actual?`${p.shift.actual.breakMinutes} min unpaid`:''}</small></td><td>{money(p.rateCents)} / h<small>{p.dayType}</small><small className="error">{p.issues.join('; ')}</small></td><td>{p.handoffBy}<small>{stamp(p.handoffAt)} · v{p.handoffVersion}</small></td></tr>)}</tbody></table></div></details></details>
    <div className="finance-payment-row"><span className="finance-status">{status}</span><span>Recorded: {money(paid(row.employeeId))}</span><span>{outstanding!==null&&outstanding<0?'Recover':'Outstanding'}: {money(outstanding===null?null:Math.abs(outstanding))}</span>{report.changed&&!selected&&delta!==null&&<span>Change since settlement: {delta>=0?'+':''}{money(delta)}</span>}<Button variant="outline" disabled={busy||!canPay||outstanding===null||outstanding===0} onClick={()=>openPayment(row)}>{outstanding!==null&&outstanding<0?'Record recovery':'Record payment'}</Button></div></div>;
   })}</details></section>
   <section className="panel finance-close"><div><h2><CheckCircle2 size={20}/>Monthly settlement</h2><p>{!report.monthEnded?'The month is still open. Review the draft now and settle after the last day (UTC+10).':report.settlement?`Last settled by ${report.settlement.createdBy} · ${stamp(report.settlement.createdAt)} · v${report.settlement.version}`:'Review all handed-over work and confirm this month before recording payments.'}</p><p>Amounts are base pay only. Tax, super, overtime premiums, allowances and leave payments are not included. Recording a payment does not send a bank transfer.</p></div><Button disabled={busy||!canSettle} onClick={()=>{setReason('');setConfirmed(false);setError('');setSettling(true)}}>{report.settlement?'Confirm revised month':'Confirm monthly settlement'}</Button></section>
   <details className="panel finance-audit"><summary>Handover and payment history</summary><h3>Timetable handovers used in this report</h3>{shownHandoffs.length?shownHandoffs.map(h=><p key={h.id}><a className="text-link" href={`/timetable?week=${h.weekStart}&restaurant=all`}>{h.weekStart} — {h.through}</a> · v{h.version} · {h.by} · {stamp(h.at)}{'early' in h&&h.early?' · Early checkout':''}<small>{h.reason||'Initial handover'}</small></p>):<p>No handovers.</p>}<h3>All checkout versions</h3>{report.handoffHistory.map(h=><p key={h.id}>{h.weekStart} — {h.through} · v{h.version}{h.current?' · Current':' · Superseded'} · {h.by} · {stamp(h.at)}<small>{h.reason||'Initial handover'}</small></p>)}<h3>Monthly settlements</h3>{report.history.map(r=><p key={r.id}>v{r.version} · {r.createdBy} · {stamp(r.createdAt)}<small>{r.reason||'Initial settlement'}</small></p>)}<h3>Payment ledger</h3>{report.payments.length?<div className="report-scroll"><table><thead><tr><th>Date</th><th>Employee</th><th>Payrun</th><th>Cash</th><th>Total</th><th>Reference</th><th>Recorded by</th></tr></thead><tbody>{report.payments.map(p=><tr key={p.id}><td>{p.date}</td><td>{rows.find(r=>r.employeeId===p.employeeId)?.name||p.employeeId}</td><td>{p.payrunCents===undefined?'—':money(p.payrunCents)}</td><td>{p.cashCents===undefined?'—':money(p.cashCents)}</td><td>{money(p.amountCents)}{p.amountCents<0?' · Recovery':''}</td><td>{p.reference}</td><td>{p.createdBy}<small>{stamp(p.createdAt)}</small></td></tr>)}</tbody></table></div>:<p>No payments recorded.</p>}</details>
   <p className="performance-hint">Only known roster shifts can be checked for missing handover. Review the full month for days that were never entered. Employee pay types and rates are preserved from checkout; profile changes require a new checkout.</p>
  </>}
  <Dialog open={!!payrollInfo} onOpenChange={v=>{if(!v&&!busy)setPayrollInfo(null)}}><DialogContent className="portal-dialog"><DialogTitle>Payroll details · {payrollInfo?.name}</DialogTitle><DialogDescription>Payroller Name carries forward into future monthly reports. Remarks apply to this month. Past settled versions remain unchanged.</DialogDescription>{payrollInfo&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void mutate('payroll-info',payrollInfo)}}><label>Payroller Name<Input maxLength={160} value={payrollInfo.payrollerName} onChange={e=>setPayrollInfo({...payrollInfo,payrollerName:e.target.value})}/></label><label>Remarks<Textarea maxLength={2000} value={payrollInfo.remarks} onChange={e=>setPayrollInfo({...payrollInfo,remarks:e.target.value})} placeholder="Optional payroll notes"/></label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy}>Save payroll details</Button></form>}</DialogContent></Dialog>
  <Dialog open={settling} onOpenChange={v=>{if(!v&&!busy)setSettling(false)}}><DialogContent className="portal-dialog"><DialogTitle>Confirm {month?monthName(month):'month'} settlement</DialogTitle><DialogDescription>Save a frozen monthly report for {rows.length} employees, with {money(total)} confirmed base pay. Previous versions and payments remain in history.</DialogDescription><form className="form-stack" onSubmit={e=>{e.preventDefault();if(report)void mutate('settle',{sourceKey:report.sourceKey,previousId:report.settlement?.id||'',reason,confirm:confirmed?'yes':'no'})}}><label>{report?.settlement?'Reason for revision':'Review note (optional)'}<Input required={!!report?.settlement} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="live-confirm"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the full month, missing handovers and payroll exclusions.</label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||!confirmed}>{busy?'Saving…':'Confirm settlement'}</Button></form></DialogContent></Dialog>
  <Dialog open={!!payment} onOpenChange={v=>{if(!v&&!busy)setPayment(null)}}><DialogContent className="portal-dialog"><DialogTitle>{payment?.kind==='recovery'?'Record completed recovery':'Record completed payment'}</DialogTitle><DialogDescription>{payment?.name} · {month?monthName(month):''}. Enter the Payrun and Cash amounts already paid outside the portal. Final pay is the actual payment date.</DialogDescription>{payment&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void mutate('payment',{...payment,settlementId:report?.settlement?.id||'',confirm:confirmed?'yes':'no'})}}><div className="roster-time-inputs"><label>Payrun (AUD)<Input required type="number" min="0" step="0.01" value={payment.payrun} onChange={e=>setPayment({...payment,payrun:e.target.value})} placeholder="0.00"/></label><label>Cash (AUD)<Input required type="number" min="0" step="0.01" value={payment.cash} onChange={e=>setPayment({...payment,cash:e.target.value})} placeholder="0.00"/></label></div><p>Total entered: {money(Math.round((Number(payment.payrun||0)+Number(payment.cash||0))*100))} · Outstanding: {money(Math.round(Number(payment.amount)*100))}</p><label>Final pay · payment date<Input required type="date" max={localClock(new Date(),'Etc/GMT-10').date} value={payment.date} onChange={e=>setPayment({...payment,date:e.target.value})}/></label><label>Transfer reference / note<Input required maxLength={300} value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label><label className="live-confirm"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this payment or recovery has already been completed.</label>{error&&<p className="error" role="alert">{error}</p>}<Button disabled={busy||!confirmed}>{busy?'Saving…':'Save payment record'}</Button></form>}</DialogContent></Dialog>
 </main></div></SidebarProvider>;
}
