'use client';
import type {ReactNode} from 'react';
import {minutes,netMinutes,type Shift} from '@/lib/roster-model';
import {hourLabel} from '@/lib/timetable-model';
const palette=[['#e3efff','#3868a7'],['#e7f3ea','#347550'],['#f1e9fb','#7954a0'],['#fff0df','#a96c25'],['#fce8ee','#a84f6f']];
function color(id:string){let n=0;for(const c of id)n=(n*31+c.charCodeAt(0))>>>0;return palette[n%palette.length];}
export function StaffDayCalendar({date,employees,shifts,onEdit,hasConflict,emptyAction,overtimeLabels}:{overtimeLabels?:Record<string,string>;emptyAction?:ReactNode;date:string;employees:{id:string;name:string;type:string;casualLevel?:1|2}[];shifts:Shift[];onEdit:(shift:Shift)=>void;hasConflict:(shift:Shift)=>boolean}){
 const dayShifts=shifts.filter(sh=>sh.date===date&&employees.some(e=>e.id===sh.employeeId));
 const from=Math.min(8,...dayShifts.map(sh=>Math.floor(minutes(sh.start)/60))),to=Math.max(20,...dayShifts.map(sh=>Math.ceil(minutes(sh.end)/60)));
 const hourHeight=72,height=(to-from)*hourHeight,columns=`80px repeat(${Math.max(1,employees.length)}, 220px)`;
 if(emptyAction&&(!employees.length||!dayShifts.length))return <>{emptyAction}</>;
 if(!employees.length)return <div className="empty"><p>No employees match this view.</p></div>;
 return <div className="staff-day-scroll" role="region" aria-label={`Assigned employee shifts for ${date}; hours down the left, employees across the top`} tabIndex={0}><div className="staff-day-grid" style={{minWidth:80+employees.length*220}}><div className="staff-day-header" style={{gridTemplateColumns:columns}}><div className="staff-day-corner">UTC+10</div>{employees.map(e=>{const own=dayShifts.filter(sh=>sh.employeeId===e.id);return <div className="staff-day-person" key={e.id}><span className="staff-day-avatar" style={{background:color(e.id)[0],color:color(e.id)[1]}}>{e.name.replace('[Mock] ','').slice(0,1)}</span><div><strong title={e.name}>{e.name}</strong><small>{e.type==='Casual'?`Casual Level ${e.casualLevel}`:e.type}</small><span>{own.length?`${(own.reduce((n,sh)=>n+netMinutes(sh),0)/60).toFixed(2)} scheduled hours`:'No shift assigned'}</span></div></div>})}</div><div className="staff-day-body" style={{gridTemplateColumns:columns}}><div className="staff-day-times" style={{height}}>{Array.from({length:to-from+1},(_,i)=><div key={i} className={'staff-day-time '+(i===to-from?'last':'')} style={{top:i*hourHeight}}>{hourLabel(from+i)}</div>)}</div>{employees.map(e=><div className="staff-day-lane" key={e.id} style={{height,backgroundSize:`100% ${hourHeight}px`}}>{dayShifts.filter(sh=>sh.employeeId===e.id).map(sh=>{const duration=minutes(sh.end)-minutes(sh.start),conflict=hasConflict(sh),ot=overtimeLabels?.[sh.id],colors=color(e.id);return <button type="button" key={sh.id} className={'staff-day-event '+(duration<45?'compact ':'')+(ot?'overtime':conflict?'conflict':'')} style={{top:(minutes(sh.start)-from*60)/60*hourHeight+2,height:Math.max(8,duration/60*hourHeight-4),backgroundColor:ot?'#fee2e2':conflict?'#fff0da':colors[0],borderLeftColor:ot?'#dc2626':conflict?'#b77726':colors[1],color:ot?'#991b1b':conflict?'#805018':colors[1]}} onClick={()=>onEdit(sh)} aria-label={`Edit ${e.name}, ${date}, ${sh.start} to ${sh.end}`} title={`${e.name} · ${sh.start}–${sh.end} · ${(netMinutes(sh)/60).toFixed(2)} scheduled hours · ${sh.breakMinutes} min unpaid break${conflict?' · availability changed':''}${ot?' · '+ot:''}`}><strong>{sh.start}–{sh.end}</strong>{duration>=45&&<><span>{e.name}</span><small>{sh.restaurant||'Unclassified'} · {sh.category||'Unclassified'}</small>{sh.breakStart&&sh.breakEnd&&<small>Break {sh.breakStart}–{sh.breakEnd} · unpaid</small>}<small>{(netMinutes(sh)/60).toFixed(2)} h · {sh.breakMinutes} min break</small><small className="staff-day-event-status">{ot|| (conflict?'Availability changed':sh.actual?'Actual confirmed':'Assigned · click to edit')}</small></>}</button>})}</div>)}</div></div></div>;
}
