'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Plus,Download,Store} from 'lucide-react';
import {FloorAutoScheduler} from './floor-auto-scheduler';
import {floorCoverage,floorOvertimeLimits,overtimeByShift} from '@/lib/floor-planning';
import {TrialScheduler} from './trial-scheduler';
import {StaffDayCalendar} from './staff-day-calendar';
import {PortalSidebar} from './portal-sidebar';
import {SidebarProvider,SidebarTrigger} from './ui/sidebar';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import type {LiveState} from '@/lib/live-store';
import {dayAdd,weekDates,nextMonday,localClock} from '@/lib/timetable-model';
import {restaurants,timetableCategories,shiftTemplates,templateApplies,templateBreak,templateHours} from '@/lib/shift-templates';
import {isTrialShift,filterRoster,openAvailability,overlap,availabilityRanges,isShiftAvailable,minutes,validMonday,type Shift} from '@/lib/roster-model';
import {rosterMonth,rosterMonthWeeks,latestMonthCheckout} from '@/lib/roster-month';
import {employeeCategory} from '@/lib/employee-model';
const dateLabel=(date:string)=>new Date(date+'T00:00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'});
const hours=(n:number)=>(n/60).toFixed(2);
export function TimetableWorkspace(){
 const [checkout,setCheckout]=useState<{month:string;reason:string;holidays:string[]}|null>(null);
 const [floorEditor,setFloorEditor]=useState(false);
 const [trialEditor,setTrialEditor]=useState<{shift?:Shift;candidateId?:string}|null>(null);
 const [state,setState]=useState<LiveState|null>(null),[week,setWeek]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[editing,setEditing]=useState<Shift|undefined>(),[employeeId,setEmployeeId]=useState(''),[date,setDate]=useState(''),[start,setStart]=useState('08:00'),[end,setEnd]=useState('12:00'),[revision,setRevision]=useState(0),[selectedDay,setSelectedDay]=useState(''),[categoryFilter,setCategoryFilter]=useState('all'),[restaurantFilter,setRestaurantFilter]=useState(''),[shiftCategory,setShiftCategory]=useState(''),[shiftRestaurant,setShiftRestaurant]=useState(''),[templateId,setTemplateId]=useState(''),[breakMinutes,setBreakMinutes]=useState('0'),[breakStart,setBreakStart]=useState(''),[breakEnd,setBreakEnd]=useState('');
 async function refresh(){try{const r=await fetch('/api/live');const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);setState(data)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const shop=params.get('restaurant')||'';if(['all','Unclassified',...restaurants].includes(shop)){setRestaurantFilter(shop);if(restaurants.includes(shop as typeof restaurants[number]))setCategoryFilter('Floor');}if(timetableCategories.includes(params.get('category') as typeof timetableCategories[number]))setCategoryFilter(params.get('category')!);if(params.get('category')==='Trial'||params.get('candidate')||params.get('open')==='trial')setCategoryFilter('Trial');if(params.get('candidate')||params.get('open')==='trial')setTrialEditor({candidateId:params.get('candidate')||undefined});const requested=params.get('week')||'';setWeek(validMonday(requested)?requested:nextMonday(localClock(new Date(),'Etc/GMT-10').date));void refresh();},[]);
 useEffect(()=>{if(!state||!week||!restaurantFilter||categoryFilter==='Trial'||categoryFilter==='Floor')return;let cancelled=false;const f=new FormData();f.set('action','auto');f.set('weekStart',week);void fetch('/api/roster',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state?.workspaceRevision??0)},body:f}).then(async r=>{const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);if(!cancelled)setState(data);}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[week,categoryFilter,restaurantFilter,!!state]);
 const roster=state?.rosters?.find(w=>w.weekStart===week),allShifts=roster?.shifts||[],employees=state?.employees||[],active=employees.filter(e=>e.status==='Active'),employee=employees.find(e=>e.id===employeeId),days=week?weekDates(week):[],collection=state?.timetable?.weeks.find(w=>w.weekStart===week);
 async function checkoutNow(){if(!checkout||!state)return;setBusy(true);setError('');try{const f=new FormData();f.set('action','checkout-month');f.set('month',checkout.month);f.set('restaurant',restaurantFilter);f.set('reason',checkout.reason);f.set('holidays',JSON.stringify(checkout.holidays));f.set('previousId',latestMonthCheckout(state,checkout.month,restaurantFilter as typeof restaurants[number])?.id||'');f.set('confirm','yes');const r=await fetch('/api/finance',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state.workspaceRevision??0)},body:f});const d=await r.json() as {month:string;error?:string};if(!r.ok)throw Error(d.error);window.location.href='/finance?month='+d.month+'&restaurant='+restaurantFilter;}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 function changeWeek(value:string){setWeek(value);setError('');setNotice('');const url=new URL(window.location.href);url.searchParams.set('week',value);window.history.replaceState(null,'',url.pathname+url.search)}
 function chooseShop(value:string){setRestaurantFilter(value);if(restaurants.includes(value as typeof restaurants[number])&&categoryFilter==='all')setCategoryFilter('Floor');setError('');setNotice('');const url=new URL(window.location.href);if(value)url.searchParams.set('restaurant',value);else url.searchParams.delete('restaurant');window.history.replaceState(null,'',url.pathname+url.search)}
 function open(kind:string,shift?:Shift,day=week,hour='08:00',person?:string,finish?:string){const id=shift?.employeeId||person||'';const bestDay=!shift&&!person&&kind==='shift'?(days.find(d=>state&&openAvailability(state,week,id,d).length)||day):day;const available=state?openAvailability(state,week,id,bestDay)[0]:undefined;setEditing(shift);setShiftCategory(shift?.category||(timetableCategories.includes(categoryFilter as typeof timetableCategories[number])?categoryFilter:''));setShiftRestaurant(shift?.restaurant||(restaurants.includes(restaurantFilter as typeof restaurants[number])?restaurantFilter:''));setTemplateId(shift?.templateId||'');setBreakMinutes(String(shift?.breakMinutes||0));setBreakStart(shift?.breakStart||'');setBreakEnd(shift?.breakEnd||'');setEmployeeId(id);setDate(shift?.date||bestDay);setStart(shift?.start||(person?hour:available?.start)||hour);setEnd(shift?.end||finish||available?.end||'12:00');setRevision(roster?.revision||0);setError('');setModal(kind);}
 function closeTrial(){setTrialEditor(null);const url=new URL(window.location.href);url.searchParams.delete('candidate');url.searchParams.delete('open');window.history.replaceState(null,'',url.pathname+url.search)}
 function choosePersonDate(id:string,day:string){setTemplateId('');setEmployeeId(id);setDate(day);if(!editing&&modal==='shift'&&state){const available=openAvailability(state,week,id,day)[0];setStart(available?.start||'08:00');setEnd(available?.end||'12:00');}}
 function chooseTemplate(id:string){setTemplateId(id);const t=shiftTemplates.find(t=>t.id===id);if(t){setStart(t.start);setEnd(t.end);setBreakMinutes(String(templateBreak(t)));setBreakStart(t.breakStart||'');setBreakEnd(t.breakEnd||'');}}
 async function run(action:string,form:FormData,extra:Record<string,string>={}){setBusy(true);setError('');try{form.set('action',action);form.set('weekStart',week);form.set('revision',String(modal?revision:roster?.revision||0));for(const [k,v] of Object.entries(extra))form.set(k,v);const r=await fetch('/api/roster',{method:'POST',headers:{'x-portal-request':'1','x-workspace-revision':String(state?.workspaceRevision??0)},body:form});const data=await r.json() as LiveState&{error?:string};if(!r.ok)throw Error(data.error);setState(data);setModal('');setNotice(action==='floor-auto'?`${restaurantFilter} arranged. Review unfilled shifts, coverage gaps and red overtime warnings.`:action==='availability'?'Employee-confirmed availability saved. You can now arrange a shift within these hours.':action==='delete'?'Shift removed.':'Timetable saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false)}}

 const selectedRanges=state&&date?availabilityRanges(state,week,employeeId,date):[];
 const editingState=state?{...state,rosters:state.rosters?.map(w=>w.weekStart===week?{...w,shifts:w.shifts.filter(sh=>sh.id!==editing?.id)}:w)}:null;
 const remaining=editingState&&date?openAvailability(editingState,week,employeeId,date):[];
 const allowed=!!state&&isShiftAvailable(state,week,employeeId,date,{start,end,breakStart,breakEnd});
 const conflict=allShifts.some(sh=>sh.id!==editing?.id&&sh.employeeId===employeeId&&sh.date===date&&overlap(sh,{start,end}));
 const calendarDay=days.includes(selectedDay)?selectedDay:days[0]||'';
 const knownWeeks=[...new Set([week,...(state?.rosters||[]).map(w=>w.weekStart),...(state?.timetable?.weeks||[]).map(w=>w.weekStart)])].filter(Boolean).sort();
 const scopedShifts=filterRoster(state||{documents:[],groups:[],assignments:[],reviews:[],activity:[],processedMessages:[]},categoryFilter,restaurantFilter).rosters?.find(w=>w.weekStart===week)?.shifts||[];
 const trialPeople=[...new Map(scopedShifts.filter(sh=>sh.candidateId&&sh.date===calendarDay).map(sh=>[sh.employeeId,{id:sh.employeeId,name:sh.employee.name,type:'Candidate'}])).values()];

 const visibleEmployees=employees.filter(e=>(e.status==='Active'||allShifts.some(sh=>sh.employeeId===e.id))&&scopedShifts.some(sh=>sh.employeeId===e.id&&sh.date===calendarDay));
 const overtime=overtimeByShift(allShifts,floorOvertimeLimits);
 const overtimeLabels=Object.fromEntries([...overtime].filter(([,value])=>value.minutes>0).map(([id,value])=>[id,`Overtime warning · ${(value.minutes/60).toFixed(2)} h${value.dailyMinutes?' · daily limit':''}${value.weeklyMinutes?' · weekly limit':''}`]));
 const isFloor=categoryFilter==='Floor'&&restaurants.includes(restaurantFilter as typeof restaurants[number]);
 const closedDay=!!roster?.floorPlan?.closedDates[restaurantFilter as typeof restaurants[number]]?.includes(calendarDay);
 const coverage=isFloor&&calendarDay&&!closedDay?floorCoverage(allShifts,restaurantFilter as typeof restaurants[number],calendarDay,'10:30','22:00'):undefined;
 const clockLabel=(value:number)=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;
 const unfilledRoles=isFloor&&!closedDay?(['full','early','late'] as const).filter(role=>!scopedShifts.some(sh=>sh.date===calendarDay&&(sh.floorRole===role||sh.autoFloorRole===role||shiftTemplates.some(t=>t.restaurant===restaurantFilter&&(role==='full'?t.id.includes('FULL'):role==='early'?t.id.includes('EARLY'):t.id.includes('LATE'))&&(sh.templateId===t.id||sh.start===t.start&&sh.end===t.end))))):[];
 const unassignedCount=allShifts.filter(sh=>!sh.restaurant).length;
 if(!restaurantFilter)return <SidebarProvider><PortalSidebar active="timetable" reviewCount={state?.reviews.filter(r=>!r.resolved).length||0}/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows / Timetable Arrangement</span></div><span className="demo-badge">UTC+10</span></header><main className="availability-page timetable-page"><div className="page-heading"><div><p className="eyebrow">TIMETABLE ARRANGEMENT</p><h1>Choose your shop</h1><p>Open a shop to manage its timetable and candidate trials.</p></div></div><div className="timetable-shop-grid">{restaurants.map(shop=><button className="panel timetable-shop-card" key={shop} onClick={()=>chooseShop(shop)}><Store size={30}/><h2>{shop}</h2><p>Kitchen · Floor · Trial</p><span>Open timetable <ArrowRight size={18}/></span></button>)}</div><div className="timetable-shop-secondary"><Button variant="outline" onClick={()=>chooseShop('Unclassified')}>Unassigned shifts{state?` (${unassignedCount})`:''}</Button><Button variant="ghost" onClick={()=>chooseShop('all')}>All shops overview</Button></div><p className="performance-hint">Assign a shop to unassigned shifts so they appear in the correct timetable.</p>{error&&<p className="error" role="alert">{error}</p>}</main></div></SidebarProvider>;
 return <SidebarProvider><PortalSidebar active="timetable" reviewCount={state?.reviews.filter(r=>!r.resolved).length||0}/><div className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Workflows / Timetable Arrangement</span></div><span className="demo-badge">UTC+10</span></header><main className="availability-page timetable-page"><div className="page-heading"><div><p className="eyebrow">TIMETABLE ARRANGEMENT</p><h1>{restaurantFilter==='all'?'All shops':restaurantFilter==='Unclassified'?'Unassigned shifts':restaurantFilter} · Timetable</h1><p>Arrange confirmed availability into shifts. Candidate trials are added manually.</p></div><div className="actions">{isFloor&&<><Button variant="outline" disabled={busy||!state} onClick={()=>setFloorEditor(true)}>Closed days</Button><Button disabled={!state||busy||!week} onClick={()=>void run('floor-auto',new FormData(),{restaurant:restaurantFilter})}>{busy?'Arranging…':'Auto arrange Floor'}</Button></>}<Button variant="outline" disabled={!state||busy||!week} onClick={()=>setTrialEditor({})}><Plus size={16}/>Add Candidate to Trial</Button>{categoryFilter!=='Trial'&&<Button className="assign-shift-button" disabled={!state||busy||!active.length} onClick={()=>open('shift',undefined,calendarDay)}><Plus size={16}/>Assign shift</Button>}</div></div>
 {categoryFilter==='Trial'?<div className="finance-checkout-bar"><div><strong>Trial · flexible hours, same-day settlement</strong><p>Choose any start and end time. Trial work has no early, late or full-day shift template. Enter the total and record payment in Finance on the trial date.</p></div><a className="primary-link" href={'/finance?view=trial&restaurant='+restaurantFilter+'&date='+(calendarDay||week)}>Settle trials in Finance</a></div>:<div className="finance-checkout-bar"><div><strong>Monthly timetable checkout</strong><p>Confirm this shop’s full roster month once. Cross-month weeks belong to the month containing Thursday.</p><a className="text-link" href={'/finance?restaurant='+restaurantFilter}>Open this shop’s Finance →</a></div><Button disabled={busy||!state||!restaurants.includes(restaurantFilter as typeof restaurants[number])} onClick={()=>{setError('');setCheckout({month:rosterMonth(week),reason:'',holidays:(state?.rosters||[]).filter(w=>rosterMonth(w.weekStart)===rosterMonth(week)).flatMap(w=>w.publicHolidays||[])})}}>Checkout month</Button></div>}


 <a className="text-link timetable-back" href="/timetable"><ArrowLeft size={15}/>Timetable Arrangement</a>
 <div className="availability-toolbar"><div className="week-navigation"><Button variant="outline" aria-label="Previous week" disabled={!week||busy} onClick={()=>changeWeek(dayAdd(week,-7))}><ArrowLeft size={16}/></Button><strong>{week} — {week?dayAdd(week,6):''}</strong><Button variant="outline" aria-label="Next week" disabled={!week||busy} onClick={()=>changeWeek(dayAdd(week,7))}><ArrowRight size={16}/></Button></div><select aria-label="Choose week with data" value={week} onChange={e=>changeWeek(e.target.value)}>{knownWeeks.map(w=><option value={w} key={w}>Week of {w}{state?.timetable?.weeks.find(c=>c.weekStart===w)?.sample?' · Mock':''}</option>)}</select><Button variant="outline" disabled={busy||!state||!scopedShifts.length} onClick={()=>window.location.assign(`/api/roster/export?week=${week}&kind=roster&category=${encodeURIComponent(categoryFilter)}&restaurant=${encodeURIComponent(restaurantFilter)}`)} title="Download the selected week, shop and department as an Excel-compatible CSV. Includes staff shifts, without pay or private contact details."><Download size={16}/>Export roster (Excel CSV)</Button></div>
 {error&&!modal&&<p className="error" role="alert">{error}</p>}{notice&&<p className="demo-notice" role="status">{notice}</p>}{collection?.sample&&<p className="demo-notice">This week includes sample availability. Mock employees and their reports are for testing.</p>}
 {!state?<section className="panel empty"><p>{error||'Loading timetable…'}</p><a href="/google">Google connection</a></section>:<>

 <nav className="timetable-departments" aria-label="Timetable department">{timetableCategories.map(value=><button type="button" key={value} aria-pressed={categoryFilter===value} onClick={()=>{setCategoryFilter(value);const url=new URL(window.location.href);url.searchParams.set('category',value);window.history.replaceState(null,'',url.pathname+url.search)}}>{value}</button>)}</nav>
<section className="panel planner-panel"><nav className="staff-day-picker" aria-label="Select timetable date">{days.map(d=><button type="button" key={d} aria-pressed={calendarDay===d} onClick={()=>setSelectedDay(d)}><strong>{dateLabel(d)}</strong><span>{scopedShifts.filter(sh=>sh.date===d).length} shifts</span></button>)}</nav>{isFloor&&<div className="floor-plan-status"><strong>{closedDay?'Shop marked closed':`Floor coverage · ${dateLabel(calendarDay)}`}</strong>{unfilledRoles.length>0&&<p className="error">Unfilled shifts: {unfilledRoles.join(' / ')}. No employee has been assigned to these roles.</p>}{coverage&&coverage.gaps.length>0&&<details open><summary>Fewer than 2 people on duty during {coverage.gaps.length} time ranges</summary><div className="floor-gap-list">{coverage.gaps.map(g=><span key={g.start}>{clockLabel(g.start)}–{clockLabel(g.end)} · {g.staff} on duty · need {g.missing} more</span>)}</div></details>}{coverage?.unknownBreaks.length? <p>Break times are missing for {coverage.unknownBreaks.length} shifts; coverage needs review.</p>:null}<p className={scopedShifts.some(sh=>overtimeLabels[sh.id])?'error':''}>{scopedShifts.filter(sh=>overtimeLabels[sh.id]).length} overtime-warning shifts this week · red on the calendar.</p><details><summary>Planning limits</summary><p>Daily: Full-time / Part-time 11.5 h; Casual 12 h. Weekly: 38 h across all shops and departments. Unpaid breaks excluded. No four-week averaging; Part-time rostered-hours agreements require separate review. Overtime pay is not calculated in Finance.</p></details></div>}<StaffDayCalendar overtimeLabels={overtimeLabels} emptyAction={categoryFilter==='Trial'?<div className="empty"><h2>No candidate trials in this view</h2><p>Add a candidate and choose their trial date, start and end time.</p><Button disabled={busy||!week} onClick={()=>setTrialEditor({})}><Plus size={16}/>Add Candidate to Trial</Button></div>:<div className="empty"><h2>No shifts scheduled for this day</h2><Button className="assign-shift-button" disabled={busy||!active.length} onClick={()=>open('shift',undefined,calendarDay)}>Assign shift</Button></div>} date={calendarDay} employees={[...visibleEmployees,...trialPeople]} shifts={scopedShifts} onEdit={sh=>sh.candidateId?setTrialEditor({shift:sh}):open('shift',sh)} hasConflict={sh=>!sh.candidateId&&!isShiftAvailable(state,week,sh.employeeId,sh.date,sh)}/></section>
 {!!roster?.manualAvailability.length&&<section className="panel roster-list"><h2>Availability confirmed outside the form</h2>{roster.manualAvailability.map(a=><div className="roster-person-status" key={a.id}><span><strong>{employees.find(e=>e.id===a.employeeId)?.name}</strong> · {a.date} {a.start}–{a.end}<small>{a.note}</small></span><Button variant="ghost" disabled={busy} onClick={()=>void run('remove-availability',new FormData(),{id:a.id})}>Remove</Button></div>)}</section>}
 </>}
 {floorEditor&&state&&<FloorAutoScheduler state={state} week={week} restaurant={restaurantFilter as typeof restaurants[number]} onClose={()=>setFloorEditor(false)} onSaved={data=>{setState(data);setNotice(`${restaurantFilter} closed days saved. Click Auto arrange Floor to apply them.`);}}/>}
 {trialEditor&&state&&<TrialScheduler defaultRestaurant={restaurants.includes(restaurantFilter as typeof restaurants[number])?restaurantFilter:undefined} state={state} week={week} shift={trialEditor.shift} requestedCandidate={trialEditor.candidateId} onClose={closeTrial} onSaved={(data,trialDate,savedRestaurant)=>{setState(data);setSelectedDay(trialDate);setCategoryFilter('Trial');chooseShop(savedRestaurant||restaurantFilter);const url=new URL(window.location.href);url.searchParams.set('category','Trial');window.history.replaceState(null,'',url.pathname+url.search);setNotice('Trial timetable saved.');}}/>}
 <Dialog open={!!checkout} onOpenChange={v=>{if(!v&&!busy)setCheckout(null)}}><DialogContent className="portal-dialog"><DialogTitle>Check out roster month</DialogTitle><DialogDescription>Confirm all Floor and Kitchen timetable hours for {restaurantFilter}. Unpaid breaks are deducted. Adjust absences and working hours before checkout; candidate trials are settled separately.</DialogDescription>{checkout&&<><label className="form-stack">Roster month<Input type="month" value={checkout.month} disabled={busy} onChange={e=>{if(e.target.value)setCheckout({...checkout,month:e.target.value,reason:'',holidays:(state?.rosters||[]).filter(w=>rosterMonth(w.weekStart)===e.target.value).flatMap(w=>w.publicHolidays||[])})}}/></label><p>Weeks included:</p><ul>{rosterMonthWeeks(checkout.month).map(w=><li key={w}>{w} — {dayAdd(w,6)} · {state?.rosters?.find(r=>r.weekStart===w)?.shifts.filter(sh=>sh.restaurant===restaurantFilter&&!isTrialShift(sh)).length||0} shifts</li>)}</ul><details><summary>Public holidays · shared by both shops</summary><div className="payroll-holidays">{rosterMonthWeeks(checkout.month).flatMap(w=>weekDates(w)).map(d=><label key={d}><input type="checkbox" checked={checkout.holidays.includes(d)} disabled={busy} onChange={e=>setCheckout({...checkout,holidays:e.target.checked?[...checkout.holidays,d]:checkout.holidays.filter(x=>x!==d)})}/>{dateLabel(d)}</label>)}</div></details><p>Checkout opens after {dayAdd(rosterMonthWeeks(checkout.month).at(-1)!,6)} (UTC+10). Weeks without shifts contribute zero hours.</p>{state&&latestMonthCheckout(state,checkout.month,restaurantFilter as typeof restaurants[number])&&<label>Reason for revised checkout<Input value={checkout.reason} maxLength={1000} onChange={e=>setCheckout({...checkout,reason:e.target.value})}/></label>}</>}{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><Button variant="outline" disabled={busy} onClick={()=>setCheckout(null)}>Cancel</Button><Button disabled={busy||!checkout||localClock(new Date(),'Etc/GMT-10').date<=dayAdd(rosterMonthWeeks(checkout.month).at(-1)!,6)||!!(state&&latestMonthCheckout(state,checkout.month,restaurantFilter as typeof restaurants[number]))&&!checkout.reason.trim()} onClick={()=>void checkoutNow()}>{busy?'Saving…':'Confirm monthly checkout'}</Button></div></DialogContent></Dialog>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="portal-dialog"><DialogTitle>{modal==='availability'?'Record employee-confirmed availability':editing?'Edit assigned shift':'Add employee / shift'}</DialogTitle><DialogDescription>{modal==='availability'?'Use this only for hours the employee has explicitly confirmed through another channel.':'Only confirmed available times are permitted. Overlapping shifts for the same employee are blocked.'}</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}
 <form className="form-stack" onSubmit={e=>{e.preventDefault();void run(modal==='availability'?'availability':'shift',new FormData(e.currentTarget),{employeeId,date,start,end,id:editing?.id||'',actualConfirmed:'no',category:shiftCategory,restaurant:shiftRestaurant,templateId,breakStart,breakEnd})}}>{modal==='shift'&&<section className="shift-classification"><div className="roster-time-inputs"><label>Restaurant<select value={shiftRestaurant} onChange={e=>{setShiftRestaurant(e.target.value);setTemplateId('')}}><option value="">Unclassified</option>{restaurants.map(r=><option key={r}>{r}</option>)}</select></label><label>Timetable category<select value={shiftCategory} onChange={e=>{setShiftCategory(e.target.value);setTemplateId('')}}><option value="">Unclassified</option>{timetableCategories.map(c=><option key={c}>{c}</option>)}</select></label></div></section>}<label>Employee<select required value={employeeId} onChange={e=>choosePersonDate(e.target.value,date)}><option value="" disabled>Choose employee</option>{employees.filter(e=>e.status==='Active'||e.id===editing?.employeeId).map(e=><option key={e.id} value={e.id}>{e.name} · {employeeCategory(e)}{e.status!=='Active'?' (Inactive)':''}</option>)}</select></label><label>Date<select required value={date} onChange={e=>choosePersonDate(employeeId,e.target.value)}>{days.map(d=><option value={d} key={d}>{dateLabel(d)}</option>)}</select></label> {modal==='availability'?<><div className="roster-time-inputs"><label>Start<Input required type="time" value={start} onChange={e=>{setStart(e.target.value);setTemplateId('')}}/></label><label>End (24:00 = midnight)<Input required pattern="([01][0-9]|2[0-3]):[0-5][0-9]|24:00" placeholder="HH:mm" value={end} onChange={e=>{setEnd(e.target.value);setTemplateId('')}}/></label></div>
<label>How did the employee confirm?<Input name="note" required maxLength={1000} placeholder="E.g. employee confirmed by phone on 24 Sep"/></label><label className="live-confirm"><input type="checkbox" name="confirm" value="yes" required/>The employee explicitly confirmed these available hours.</label></>:<>{shiftCategory==='Floor'&&<label>Floor shift template<select value={templateId} onChange={e=>chooseTemplate(e.target.value)}><option value="">Custom / adjusted shift</option>{shiftTemplates.filter(t=>t.restaurant===shiftRestaurant&&templateApplies(t,date)).map(t=><option key={t.id} value={t.id}>{t.name} · {t.start}–{t.end} · {templateHours(t)} paid hours</option>)}</select><small>Choose a restaurant and date first. Templates include unpaid break times.</small></label>}<section className="remaining-availability"><strong>{hours(remaining.reduce((n,r)=>n+minutes(r.end)-minutes(r.start),0))} hours remaining{editing?' (excluding this shift)':''}</strong><p>Select a remaining time range, then adjust the start and end below.</p><div className="actions">{remaining.map(r=><Button type="button" variant="outline" key={r.start} onClick={()=>{setStart(r.start);setEnd(r.end);setTemplateId('')}}>{r.start}–{r.end}</Button>)}</div>{!remaining.length&&<p>{employeeId?'No remaining confirmed availability on this date.':'Choose an employee first, then choose a date.'}</p>}</section>{!allowed&&selectedRanges.length>0&&<p className="error">Choose a time within the confirmed availability above.</p>}{conflict&&<p className="error">This time overlaps an existing shift. Select a free time or edit that shift.</p>}<div className="roster-time-inputs"><label>Start<Input required type="time" value={start} onChange={e=>{setStart(e.target.value);setTemplateId('')}}/></label><label>End (24:00 = midnight)<Input required pattern="([01][0-9]|2[0-3]):[0-5][0-9]|24:00" placeholder="HH:mm" value={end} onChange={e=>{setEnd(e.target.value);setTemplateId('')}}/></label></div>
<label>Unpaid break (minutes)<Input name="breakMinutes" required type="number" min="0" step="1" value={breakMinutes} onChange={e=>{setBreakMinutes(e.target.value);setTemplateId('')}}/></label><div className="roster-time-inputs"><label>Unpaid break start · optional<Input type="time" value={breakStart} onChange={e=>{setBreakStart(e.target.value);setTemplateId('')}}/></label><label>Unpaid break end · optional<Input type="time" value={breakEnd} onChange={e=>{setBreakEnd(e.target.value);setTemplateId('')}}/></label></div><p className="performance-hint">Fixed Floor templates set these times automatically. For custom breaks, the interval must match the unpaid minutes.</p><label>HR shift notes · optional<Input name="notes" maxLength={1000} defaultValue={editing?.notes}/></label><p>Pay is calculated automatically from the employee profile and Pay Rate Table · <a className="text-link" href={'/employees?person='+employeeId} target="_blank" rel="noreferrer">Edit employee profile</a></p><p>Adjust working hours and absences here. Monthly checkout confirms the final timetable hours automatically, excluding unpaid breaks.</p></>}
 <Button disabled={busy||!employeeId||(modal==='shift'&&(!allowed||conflict))}>{busy?'Saving…':modal==='availability'?'Save confirmed availability':'Save shift'}</Button></form>{modal==='shift'&&editing&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run('delete',new FormData(e.currentTarget),{id:editing.id})}}><label className="live-confirm"><input type="checkbox" name="confirm" value="yes" required/>Delete this shift{editing.actual?' and its confirmed actual work entry':''}.</label><Button variant="destructive" disabled={busy}>Delete shift</Button></form>}
 </DialogContent></Dialog></main></div></SidebarProvider>
}
