import {departmentScope,departmentRecipients} from './department-availability';
import {restaurants,type Restaurant} from './shift-templates';
import {autoAllocateWeek} from './roster';
import {randomUUID} from 'node:crypto';
import {googleJson,GoogleError} from './google-auth';
import {saveLive,type LiveState} from './live-store';
import {deliver} from './google-workflow';
import {log,type Assignment} from './demo-store';
import {parseCustomAvailability,defaultSettings,eligibleEmployees,localClock,nextMonday,weekDates,hourLabel,dayAdd,type AvailabilityGroup,type AvailabilityGroupConfig,type AvailabilitySettings,type AvailabilityWeek,type AvailabilityReply} from './timetable-model';
const forms='https://forms.googleapis.com/v1/forms';
const drive='https://www.googleapis.com/drive/v3/files';
const post=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const none='Not available';
type Form={formId:string;responderUri?:string;settings?:{emailCollectionType?:string};items?:{itemId?:string;title?:string;questionItem?:{question?:{questionId?:string;required?:boolean;choiceQuestion?:{type?:string;options?:{value:string}[]}}}}[];publishSettings?:{publishState?:{isPublished?:boolean;isAcceptingResponses?:boolean}}};
type ResponseRecord={responseId:string;respondentEmail?:string;createTime:string;lastSubmittedTime?:string;answers?:Record<string,{textAnswers?:{answers?:{value:string}[]}}>};
export function availabilityState(s:LiveState){return s.timetable??={settings:{...defaultSettings,employeeIds:[]},weeks:[]}}
export function groupMembers(s:LiveState,id:string,restaurant?:Restaurant){const source=s.groups.find(g=>g.id===id);if(!source)return [];return [...new Map(source.members.map(p=>[p.email.trim().toLowerCase(),p])).values()].flatMap(p=>{const e=s.employees?.find(e=>e.email.toLowerCase()===p.email.toLowerCase());if(e?.status==='Inactive'||restaurant&&(!e||!e.assignedShops?.includes(restaurant)))return [];return [{id:e?.id||p.id,name:p.name,email:p.email.trim().toLowerCase()}];});}
export function addCollectionGroup(s:LiveState,email:string,id:string,restaurant?:Restaurant,department?:string){if(restaurant&&(!restaurants.includes(restaurant)||!['Floor','Kitchen'].includes(department||'')))throw Error('Choose a shop and department.');const source=s.groups.find(g=>g.id===id);if(!source)throw Error('Choose an existing Employee Group.');const t=availabilityState(s);const legacy=restaurant?Object.entries(t.groups||{}).find(([,g])=>g?.employeeGroupId===id&&!g.restaurant):undefined;if(legacy){const [key,g]=legacy;Object.assign(g!,{restaurant,department});g!.settings={...g!.settings,enabled:false,employeeIds:groupMembers(s,id,restaurant).map(p=>p.id)};saveLive(email,s);return key;}const key='employee-group:'+id+(restaurant?':'+restaurant+':'+department:'');t.groups??={};if(!t.groups[key])t.groups[key]={restaurant,department:department as 'Floor'|'Kitchen'|undefined,employeeGroupId:id,name:source.name,settings:{...defaultSettings,employeeIds:groupMembers(s,id,restaurant).map(p=>p.id),slotMinutes:30},configured:false,hoursConfigured:false,formSource:'custom'};saveLive(email,s);return key;}
export function collectionMembers(s:LiveState,g:AvailabilityGroupConfig){return g.profileRecipients&&g.restaurant&&g.department?departmentRecipients(s.employees||[],g.restaurant,g.department):g.employeeGroupId?groupMembers(s,g.employeeGroupId,g.restaurant):eligibleEmployees(s.employees||[]).filter(e=>g.settings.employeeIds.includes(e.id));}
export function collectionGroup(s:LiveState,group:string):AvailabilityGroupConfig{const t=availabilityState(s);const found=t.groups?.[group];if(found)return found;const scope=departmentScope(group);if(scope){t.groups??={};const old=Object.values(t.groups).filter(g=>g?.restaurant===scope.restaurant&&g.department===scope.department&&!g.profileRecipients);const inherited=old.length===1?old[0]:undefined;for(const g of old)if(g)g.settings.enabled=false;return t.groups[group]={...inherited,...scope,profileRecipients:true,employeeGroupId:undefined,name:scope.restaurant+' · '+scope.department,settings:{...(inherited?.settings||defaultSettings),enabled:false,employeeIds:departmentRecipients(s.employees||[],scope.restaurant,scope.department).map(e=>e.id)},configured:inherited?.configured||false,formSource:'custom'};}if(!['Floor','Kitchen'].includes(group))throw Error('Add an Employee Group to availability collection first.');t.groups??={};return t.groups[group]??={settings:{...defaultSettings,employeeIds:[],openHour:group==='Floor'?10.5:8,closeHour:22,slotMinutes:30},configured:false,formSource:'builtin'};}
export function saveGroupSettings(s:LiveState,email:string,group:string,input:AvailabilitySettings,formSource:string){const g=collectionGroup(s,group);if(g.profileRecipients){input={...input,employeeIds:collectionMembers(s,g).map(p=>p.id)};}else if(g.employeeGroupId){if(!s.groups.some(x=>x.id===g.employeeGroupId))throw Error('The source Employee Group no longer exists.');input={...input,employeeIds:groupMembers(s,g.employeeGroupId,g.restaurant).map(p=>p.id)};}if(!Array.isArray(input.employeeIds))throw Error('Choose employee IDs.');const pending=input.openHour===-1&&input.closeHour===-1;if(pending&&input.enabled&&formSource==='builtin')throw Error('Set working hours before enabling automatic sends.');if(!['builtin','custom'].includes(formSource))throw Error('Choose a form source.');const others=Object.entries(s.timetable?.groups||{}).filter(([key])=>key!==group).map(([,g])=>g);if(!g.profileRecipients&&!g.employeeGroupId&&input.employeeIds.some(id=>others.some(other=>other?.settings.employeeIds.includes(id))))throw Error('An employee can belong to only one collection group. Remove them from the other group first.');if(!pending&&(!Number.isFinite(input.openHour)||!Number.isFinite(input.closeHour)||input.openHour<0||input.closeHour>24||input.closeHour<=input.openHour||!Number.isInteger(input.openHour*2)||!Number.isInteger(input.closeHour*2)))throw Error('Choose a valid half-hour range.');if(formSource==='custom'&&input.enabled&&!g.customForm)throw Error('Add your Google Form before enabling scheduled sends.');const original=availabilityState(s).settings;saveAvailabilitySettings(s,email,{...input,enabled:false},false,g.profileRecipients||g.employeeGroupId?collectionMembers(s,g):undefined);const validated=availabilityState(s).settings;availabilityState(s).settings=original;g.settings={...validated,enabled:input.enabled,openHour:pending?8:input.openHour,closeHour:pending?22:input.closeHour,slotMinutes:30};if(g.settings.enabled&&!g.settings.employeeIds.length)throw Error('Select employees first.');g.formSource=formSource as 'builtin'|'custom';g.configured=true;g.hoursConfigured=!pending;saveLive(email,s);}
export function saveAvailabilitySettings(s:LiveState,email:string,input:AvailabilitySettings,persist=true,members?:{id:string}[]){const selected=members||eligibleEmployees(s.employees||[]);if(input.sendDay!==undefined&&(!Number.isInteger(input.sendDay)||input.sendDay<0||input.sendDay>6))throw Error('Choose a valid weekday.');if(input.timezone!=='Etc/GMT-10'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.sendTime))throw Error('Choose a valid sending time in fixed UTC+10.');if(!Array.isArray(input.employeeIds)||input.employeeIds.some(id=>typeof id!=='string'||!selected.some(e=>e.id===id)))throw Error('Select active Part-time or Casual employees.');if(input.enabled&&!input.employeeIds.length)throw Error('Select employees before enabling weekly sends.');const t=availabilityState(s);t.settings={...defaultSettings,timezone:'Etc/GMT-10',sendTime:input.sendTime,sendDay:input.sendDay??4,enabled:input.enabled===true,employeeIds:[...new Set(input.employeeIds)]};if(persist)saveLive(email,s)}
export function availabilityWeek(s:LiveState,id:string){const w=availabilityState(s).weeks.find(w=>w.id===id);if(!w)throw Error('Weekly collection not found.');return w}
function options(w:AvailabilityWeek){const step=(w.settings.slotMinutes||60)/60;return [...Array.from({length:(w.settings.closeHour-w.settings.openHour)/step},(_,i)=>`${hourLabel(w.settings.openHour+i*step)}–${hourLabel(w.settings.openHour+(i+1)*step)}`),none]}
function item(w:AvailabilityWeek,date:string,index:number){return {itemId:`a000000${index}`,title:date,description:'Select every time slot you can work, or select Not available on its own. Times are UTC+10.',questionItem:{question:{questionId:`b000000${index}`,required:true,choiceQuestion:{type:'CHECKBOX',options:options(w).map(value=>({value})),shuffle:false}}}}}
export function verifyAvailabilityForm(w:AvailabilityWeek,form:Form){if(form.settings?.emailCollectionType!=='VERIFIED')throw Error('This availability form must collect Verified Google account email.');const dates=weekDates(w.weekStart);for(const [index,date] of dates.entries()){const expected=item(w,date,index),actual=form.items?.find(i=>i.itemId===expected.itemId),q=actual?.questionItem?.question;if(actual?.title!==date||q?.questionId!==expected.questionItem.question.questionId||!q?.required||q.choiceQuestion?.type!=='CHECKBOX'||JSON.stringify(q.choiceQuestion.options?.map(o=>o.value))!==JSON.stringify(options(w)))throw Error('The weekly form questions have changed. Restore its original dates and hourly options before sending or collecting responses.');}if(form.items?.length!==7)throw Error('The weekly form must contain exactly seven daily questions.');}
async function ensureWeeklyForm(s:LiveState,email:string,w:AvailabilityWeek){if(w.customForm){const form=await googleJson<Form>(forms+'/'+w.formId);if(form.settings?.emailCollectionType!=='VERIFIED')throw Error('Enable Verified email collection in your Google Form before sending.');if(!form.responderUri||form.publishSettings?.publishState?.isPublished===false||form.publishSettings?.publishState?.isAcceptingResponses===false)throw Error('Publish your Google Form and enable accepting responses first.');w.formUrl=form.responderUri;w.formReady=true;saveLive(email,s);return w;}const title=`Availability ${w.groupName?w.groupName+' ':w.group?w.group+' ':''}${w.weekStart} — ${w.id}`;
 if(!w.formId){if(w.formCreation){const found=await googleJson<{files:{id:string}[]}>(drive+'?'+new URLSearchParams({q:`trashed=false and mimeType='application/vnd.google-apps.form' and name='${title.replace(/\\/g,'\\\\').replace(/'/g,"\\'")}'`,fields:'files(id)',pageSize:'10'}));if(found.files.length===1)w.formId=found.files[0].id;else throw Error('Form creation result is uncertain. Check Google Drive; retry once the uniquely named weekly form appears. No duplicate form was created.');}
 else{w.formCreation='creating';saveLive(email,s);try{const form=await googleJson<Form>(forms+'?unpublished=true',post({info:{title,documentTitle:title}}));if(!form.formId)throw Error('Missing Google Form ID.');w.formId=form.formId;w.formCreation=undefined;saveLive(email,s)}catch(e){w.formCreation=e instanceof GoogleError&&[400,401,403,404,429].includes(e.status)?undefined:'uncertain';saveLive(email,s);throw e}}}
 const id=w.formId!;let form=await googleJson<Form>(forms+'/'+id);
 if(!w.formReady){const requests:unknown[]=[{updateSettings:{settings:{emailCollectionType:'VERIFIED'},updateMask:'emailCollectionType'}},{updateFormInfo:{info:{description:`Work availability for ${w.weekStart} to ${dayAdd(w.weekStart,6)}. All times are fixed UTC+10. Select each time slot you can work. Choose Not available alone on days you cannot work. This is availability collection, not a confirmed roster. Use the Google account that received the email.`},updateMask:'description'}}];for(const [index,date] of weekDates(w.weekStart).entries()){const expected=item(w,date,index);if(!form.items?.some(i=>i.itemId===expected.itemId))requests.push({createItem:{item:expected,location:{index}}})}await googleJson(forms+'/'+id+':batchUpdate',post({requests}));form=await googleJson<Form>(forms+'/'+id);verifyAvailabilityForm(w,form);
 await googleJson(forms+'/'+id+':setPublishSettings',post({publishSettings:{publishState:{isPublished:true,isAcceptingResponses:true}},updateMask:'publishState'}));form=await googleJson<Form>(forms+'/'+id);verifyAvailabilityForm(w,form);if(!form.responderUri||!form.publishSettings?.publishState?.isPublished||!form.publishSettings.publishState.isAcceptingResponses)throw Error('The weekly form is not published and accepting responses.');
 w.questionIds=Object.fromEntries(weekDates(w.weekStart).map((date,index)=>[date,`b000000${index}`]));w.formUrl=form.responderUri;w.formReady=true;w.formCreation=undefined;saveLive(email,s)
 }else verifyAvailabilityForm(w,form);
 if(!form.publishSettings?.publishState?.isPublished||!form.publishSettings.publishState.isAcceptingResponses)throw Error('The weekly form is not accepting responses. Publish it in Google Forms first.');return w;
}
export async function prepareAvailabilityWeek(s:LiveState,email:string,weekStart:string,group?:AvailabilityGroup){if(!/^\d{4}-\d{2}-\d{2}$/.test(weekStart)||!Number.isFinite(Date.parse(weekStart))||new Date(weekStart+'T00:00:00Z').getUTCDay()!==1||new Date(weekStart+'T00:00:00Z').toISOString().slice(0,10)!==weekStart)throw Error('Select a valid Monday for the collection week.');const t=availabilityState(s);const config=group?collectionGroup(s,group):undefined;if(config&&(!config.configured||(config.formSource==='builtin'&&config.hoursConfigured===false)||(config.formSource==='custom'&&!config.customForm)))throw Error('Add a Google Form and save the sending schedule first.');const settings=config?.settings||t.settings;let w=t.weeks.find(w=>w.weekStart===weekStart&&w.group===group);if(!w){const members=config?collectionMembers(s,config):eligibleEmployees(s.employees||[]).filter(e=>settings.employeeIds.includes(e.id));const employeeIds=members.map(p=>p.id);if(!employeeIds.length)throw Error('Choose eligible employees and save collection settings first.');if(t.weeks.some(other=>other.weekStart===weekStart&&!other.sample&&(!config?.restaurant||!other.group||s.timetable?.groups?.[other.group]?.restaurant===config.restaurant||other.formId===config.customForm?.id)&&(other.employeeIds.some(id=>employeeIds.includes(id))||(other.recipients||[]).some(p=>members.some(m=>m.email.toLowerCase()===p.email.toLowerCase())))))throw Error('Some employees already have another collection for this week in this shop or using the same form. Use the existing batch, or a separate form for the other shop.');w={id:randomUUID(),customForm:config?.formSource==='custom',formId:config?.formSource==='custom'?config.customForm?.id:undefined,group,groupName:config?.name||(config?.employeeGroupId?s.groups.find(g=>g.id===config.employeeGroupId)?.name:group),recipients:members.map(p=>({id:p.id,name:p.name,email:p.email})),weekStart,settings:{...settings,employeeIds:[...employeeIds]},employeeIds,responses:[],responseErrors:[],created:new Date().toISOString()};t.weeks.unshift(w);saveLive(email,s)}try{if(w.sample)throw Error('Sample collections cannot create or send Google Forms. Choose another week for live collection.');await ensureWeeklyForm(s,email,w);w.error=undefined;saveLive(email,s);return w}catch(e){w.error=(e as Error).message;saveLive(email,s);throw e}}
export async function sendAvailabilityWeek(s:LiveState,email:string,id:string,retry=false){const w=availabilityWeek(s,id);if(w.sample)throw Error('Sample collections cannot send email.');await ensureWeeklyForm(s,email,w);let a=s.assignments.find(a=>a.id===w.assignmentId);if(!a){const recipients=w.recipients||((s.employees||[]).filter(e=>w.employeeIds.includes(e.id)&&eligibleEmployees([e]).length));if(!recipients.length)throw Error('No active selected employees remain.');a={id:`JYM-${w.weekStart.slice(0,7).replace('-','')}-${randomUUID().slice(0,8).toUpperCase()}`,workflow:'availability',name:`${w.groupName?w.groupName+' — ':w.group?w.group+' — ':''}Work availability: ${w.weekStart} – ${dayAdd(w.weekStart,6)}`,docId:w.formId!,formId:w.formId,groups:[],due:'',message:`Please submit your available hours for next week (${w.weekStart} – ${dayAdd(w.weekStart,6)}). All times are UTC+10. Your answers indicate availability, not assigned shifts.`,created:new Date().toISOString(),recipients:recipients.map(e=>({id:e.id,name:e.name,email:e.email,status:'Pending',threadId:'',delivery:'ready',rfcMessageId:randomUUID()+'@jymmanuel.local'}))};s.assignments.unshift(a);w.assignmentId=a.id;w.employeeIds=recipients.map(e=>e.id);saveLive(email,s)}
 const config=w.group?s.timetable?.groups?.[w.group]:undefined;const active=new Set((config?collectionMembers(s,config):eligibleEmployees(s.employees||[])).map(e=>e.id));const selected=a.recipients.filter(r=>active.has(r.id)&&(r.delivery==='ready'||(retry&&r.delivery==='failed')));if(selected.length&&w.customForm)await collectAvailability(s,email);if(selected.length)await deliver(s,email,{...a,recipients:selected},{id:w.formId!,name:a.name,type:'FORM',category:'Availability',updated:'',size:'',url:w.formUrl});w.error=undefined;saveLive(email,s);
}
export function parseAvailability(w:AvailabilityWeek,response:ResponseRecord,employeeId:string):AvailabilityReply{const hours:Record<string,number[]>={};for(const date of weekDates(w.weekStart)){const key=w.questionIds?.[date],values=key?response.answers?.[key]?.textAnswers?.answers?.map(a=>a.value):undefined;if(!values?.length||values.some(v=>!options(w).includes(v))||(values.includes(none)&&values.length!==1))throw Error(`${date}: select valid hours or Not available alone.`);hours[date]=values.includes(none)?[]:[...new Set(values.map(v=>Number(v.slice(0,2))+Number(v.slice(3,5))/60))].sort((a,b)=>a-b)}const submittedAt=response.lastSubmittedTime||response.createTime;if(!Number.isFinite(Date.parse(submittedAt)))throw Error('Invalid submission time.');return {employeeId,responseId:response.responseId,submittedAt,hours}}
export async function collectAvailability(s:LiveState,email:string){for(const w of s.timetable?.weeks||[]){if(w.sample||!w.formReady||!w.assignmentId)continue;const a=s.assignments.find(a=>a.id===w.assignmentId);if(!a)continue;try{const form=await googleJson<Form>(forms+'/'+w.formId);if(w.customForm){if(form.settings?.emailCollectionType!=='VERIFIED')throw Error('The form must collect Verified Google account email.');}else verifyAvailabilityForm(w,form);let pageToken:string|undefined;const latest=new Map<string,ResponseRecord>(),seen=new Set<string>();w.responseErrors=[];
 do{const page=await googleJson<{responses?:ResponseRecord[];nextPageToken?:string}>(forms+'/'+w.formId+'/responses?'+new URLSearchParams({pageSize:'100',...(pageToken?{pageToken}:{}),fields:'responses(responseId,respondentEmail,createTime,lastSubmittedTime,answers),nextPageToken'}));for(const response of page.responses||[]){const r=a.recipients.find(r=>r.email.toLowerCase()===response.respondentEmail?.trim().toLowerCase()&&r.delivery==='sent');if(!r)continue;const window=availabilityResponseWindow(s,w,r.email);const created=Date.parse(response.createTime),updated=Date.parse(response.lastSubmittedTime||response.createTime);if(!response.responseId||!Number.isFinite(created)||!Number.isFinite(updated)||created<window.start||updated>=window.end)continue;const prev=latest.get(r.id);if(!prev||Date.parse(response.lastSubmittedTime||response.createTime)>Date.parse(prev.lastSubmittedTime||prev.createTime))latest.set(r.id,response)}pageToken=page.nextPageToken;if(pageToken&&seen.has(pageToken))throw Error('Repeated Google response page. Retry collection.');if(pageToken)seen.add(pageToken)}while(pageToken);
 const replies:AvailabilityReply[]=[];for(const [employeeId,response] of latest){try{const reply=w.customForm?parseCustomAvailability(w,form,response,employeeId):parseAvailability(w,response,employeeId);replies.push(reply);if(reply.mappingError)w.responseErrors.push(`${a.recipients.find(r=>r.id===employeeId)?.name||'Employee'}: ${reply.mappingError}`)}catch(e){const r=a.recipients.find(r=>r.id===employeeId)!;w.responseErrors.push(`${r.name}: ${(e as Error).message}`)}}if(w.customForm)for(const previous of w.responses){const recipient=a.recipients.find(r=>r.id===previous.employeeId);if(recipient&&Number.isFinite(availabilityResponseWindow(s,w,recipient.email).end)&&!replies.some(r=>r.employeeId===previous.employeeId))replies.push(previous);}w.responses=replies;for(const r of a.recipients){const reply=replies.find(reply=>reply.employeeId===r.id);r.status=reply?'Completed':'Pending';r.formResponseId=reply?.responseId;r.received=reply?.submittedAt;}w.lastChecked=new Date().toISOString();w.error=undefined;saveLive(email,s);if(!w.customForm)autoAllocateWeek(s,email,w.weekStart)
 }catch(e){w.error=(e as Error).message;saveLive(email,s)}}}
async function runLegacyWeeklyAvailability(s:LiveState,email:string,now=new Date()){const t=s.timetable;if(!t?.settings.enabled)return;const clock=localClock(now,t.settings.timezone);if(new Date(clock.date+'T00:00:00Z').getUTCDay()!==(t.settings.sendDay??4)||clock.time<t.settings.sendTime)return;const key=nextMonday(clock.date);const existing=t.weeks.find(w=>w.weekStart===key);if(existing?.assignmentId)return;if(t.lastAutomationAttempt&&Date.parse(t.lastAutomationAttempt)>now.getTime()-3600000)return;t.lastAutomationAttempt=now.toISOString();saveLive(email,s);try{const w=await prepareAvailabilityWeek(s,email,key);await sendAvailabilityWeek(s,email,w.id);t.automationError=undefined;log(s,`Weekly availability sent for ${key}`)}catch(e){t.automationError=(e as Error).message}saveLive(email,s)}

export async function runWeeklyAvailability(s:LiveState,email:string,now=new Date()){const groups=s.timetable?.groups;if(!groups||!Object.values(groups).some(g=>g?.configured))return runLegacyWeeklyAvailability(s,email,now);for(const group of Object.keys(groups)){const g=groups[group];if(g&&!g.profileRecipients&&Object.values(groups).some(c=>c?.profileRecipients))continue;if(g?.employeeGroupId&&!s.groups.some(x=>x.id===g.employeeGroupId))continue;if(!g?.configured||!g.settings.enabled||(g.formSource==='builtin'&&g.hoursConfigured===false)||(g.formSource==='custom'&&!g.customForm))continue;const clock=localClock(now,g.settings.timezone);if(new Date(clock.date+'T00:00:00Z').getUTCDay()!==(g.settings.sendDay??4)||clock.time<g.settings.sendTime)continue;const weekStart=nextMonday(clock.date);if(s.timetable!.weeks.some(w=>w.weekStart===weekStart&&w.group===group&&w.assignmentId))continue;if(g.lastAutomationAttempt&&Date.parse(g.lastAutomationAttempt)>now.getTime()-3600000)continue;g.lastAutomationAttempt=now.toISOString();saveLive(email,s);try{const w=await prepareAvailabilityWeek(s,email,weekStart,group);await sendAvailabilityWeek(s,email,w.id);g.automationError=undefined;}catch(e){g.automationError=(e as Error).message;}saveLive(email,s);}}

export function availabilityResponseWindow(s:LiveState,w:AvailabilityWeek,email:string){
 const assignment=s.assignments.find(a=>a.id===w.assignmentId),recipient=assignment?.recipients.find(r=>r.email.toLowerCase()===email.toLowerCase());
 const start=Date.parse(recipient?.deliveryStartedAt||recipient?.sentAt||assignment?.created||'');
 const later=(s.timetable?.weeks||[]).filter(other=>other.id!==w.id&&other.formId===w.formId&&!other.sample).flatMap(other=>{
  const a=s.assignments.find(a=>a.id===other.assignmentId),r=a?.recipients.find(r=>r.email.toLowerCase()===email.toLowerCase()&&r.delivery==='sent');
  return r?[Date.parse(r.deliveryStartedAt||r.sentAt||a!.created)]:[];
 }).filter(time=>time>start);
 return {start,end:Math.min(Infinity,...later)};
}

export async function startAvailabilityCollection(s:LiveState,email:string,weekStart:string,group:string,confirmed:boolean){
 if(!confirmed)throw Error('Confirm sending this week’s form by real Gmail.');
 collectionGroup(s,group);
 const batch=await prepareAvailabilityWeek(s,email,weekStart,group);
 await sendAvailabilityWeek(s,email,batch.id,!!batch.assignmentId);
 return batch;
}
