import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
export type Doc = {id:string; name:string; type:string; category:string; updated:string; size:string; file?:string; url?:string; driveId?:string; parentIds?:string[]; templateShortcutId?:string};
export type Person = {id:string; name:string; email:string};
export type Group = {id:string; name:string; description:string; members:Person[]};
export type Recipient = Person & {deliveryStartedAt?:string;sentAt?:string;status:'Pending'|'Completed'; threadId:string; draftId?:string; preparedPdfId?:string; preparedHash?:string; preparedAt?:string; preparationError?:string; reviewedAt?:string; formResponseId?:string; returnedFile?:string; returnedName?:string; received?:string; destination?:string; returnedUrl?:string; returnedDriveId?:string; returnedMessageId?:string; delivery?:"ready"|"sending"|"sent"|"failed"|"uncertain"; deliveryError?:string; messageId?:string; rfcMessageId?:string};
export type Assignment = {id:string; name:string; docId:string; groups:string[]; due:string; message:string; created:string; recipients:Recipient[]; workflow?:'performance'|'hiring'|'availability'; formId?:string; driveFolderId?:string; requestId?:string};
export type Review = {id:string; assignmentId:string; sender:string; reason:string; created:string; resolved?:boolean; formId?:string; formResponseId?:string; gmailMessageId?:string};
export type LibraryFolder = {id:string; name:string; parentIds?:string[]};
export type State = {folderOptions?:LibraryFolder[]; documents:Doc[]; groups:Group[]; assignments:Assignment[]; reviews:Review[]; activity:{id:string; text:string; time:string}[]};
const root=process.env.DEMO_DATA_DIR || path.join(process.cwd(),'.demo-data');
const database=path.join(root,'metadata.json');
export const files=path.join(root,'files');
export function samplePdf(title:string){const safe=title.replace(/[^a-zA-Z0-9 .-]/g,'');const stream=`BT /F1 20 Tf 60 750 Td (${safe}) Tj /F1 11 Tf 0 -40 Td (JYMMANUEL - LOCAL DEMO DOCUMENT) Tj 0 -35 Td (Employee name: ____________________________________) Tj 0 -40 Td (Department: _______________________________________) Tj 0 -40 Td (Review period: ____________________________________) Tj 0 -60 Td (Comments and achievements:) Tj 0 -40 Td (__________________________________________________) Tj 0 -40 Td (__________________________________________________) Tj 0 -60 Td (Signature: ___________________  Date: ______________) Tj ET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n';const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const x=Buffer.byteLength(pdf);pdf+=`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${String(o).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(pdf)}
export function load():State {fs.mkdirSync(files,{recursive:true});if(fs.existsSync(database)){const state:State=JSON.parse(fs.readFileSync(database,'utf8'));state.folderOptions??=[{id:'demo-templates',name:'Templates'}];state.documents=state.documents.map(d=>({...d,parentIds:d.parentIds??(d.file?['demo-templates']:[])}));return state;}const people=[['Amelia Tan','amelia'],['Daniel Lim','daniel'],['Sofia Wong','sofia'],['Marcus Lee','marcus'],['Priya Nair','priya'],['Adam Chen','adam']].map(([name,id])=>({id,name,email:`${id}@jymmanuel.example`}));const documents:Doc[]=[['Employee Performance Review','People & culture'],['Leave Application','People & culture'],['Expense Reimbursement','Finance'],['New Employee Checklist','Operations'],['Workplace Safety Acknowledgement','Operations']].map(([name,category],i)=>({id:`doc-${i+1}`,name,type:'PDF',category,updated:'2026-09-18',size:'1 KB',file:`sample-${i+1}.pdf`,parentIds:['demo-templates']}));for(const d of documents)fs.writeFileSync(path.join(files,d.file!),samplePdf(d.name));const groups=[{id:'operations',name:'Operations',description:'Day-to-day operations and administration',members:people.slice(0,3)},{id:'finance',name:'Finance',description:'Finance and accounts team',members:people.slice(3,5)},{id:'all',name:'All employees',description:'Everyone at Jymmanuel',members:people}];const a:Assignment={id:'JYM-202609-001',name:'September Employee Performance Review',docId:'doc-1',groups:['all'],due:'2026-09-30',message:'Please complete your September review and reply to this email with the completed PDF attached.',created:'2026-09-18T09:00:00Z',recipients:people.map((p,i)=>({...p,status:i<2?'Completed':'Pending',threadId:`demo-thread-${p.id}`,...(i<2?{returnedFile:'sample-1.pdf',returnedName:'Completed performance review.pdf',received:'2026-09-20T10:00:00Z',destination:`Submissions/2026-09/September Employee Performance Review/${p.name}/`}:{})}))};const state:State={folderOptions:[{id:'demo-templates',name:'Templates'}],documents,groups,assignments:[a],reviews:[],activity:[{id:'seed',text:'September performance review sent to 6 employees',time:a.created}]};save(state);return state}
export function save(state:State){fs.mkdirSync(root,{recursive:true});const temp=database+'.tmp';fs.writeFileSync(temp,JSON.stringify(state,null,2));fs.renameSync(temp,database)}
export function log(state:State,text:string){state.activity.unshift({id:randomUUID(),text,time:new Date().toISOString()});state.activity=state.activity.slice(0,30)}
export function storeFile(buffer:Buffer){const id=randomUUID()+'.pdf';fs.writeFileSync(path.join(files,id),buffer);return id}
export function isPdf(buffer:Buffer){return buffer.subarray(0,5).toString()==='%PDF-'}
