import {collectAvailability,runWeeklyAvailability} from './availability';
import {prepareForm,collectFormResponses} from './google-forms';
import {randomUUID} from 'node:crypto';
import {googleFetch,googleJson,GoogleError,readConnection} from './google-auth';
import {loadLive,saveLive,exclusive,type LiveState} from './live-store';
import {isPdf,log,type Doc,type LibraryFolder,type Assignment,type Recipient} from './demo-store';
const drive='https://www.googleapis.com/drive/v3';
const gmail='https://gmail.googleapis.com/gmail/v1/users/me';
const json=(body:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const quote=(s:string)=>s.replace(/\\/g,'\\\\').replace(/'/g,"\\'");
const maxPdf=15*1024*1024;
export type DriveFile={id:string;name:string;mimeType:string;webViewLink?:string;modifiedTime?:string;size?:string;appProperties?:Record<string,string>;parents?:string[];shortcutDetails?:{targetId:string;targetMimeType?:string}};
const fields='id,name,mimeType,webViewLink,modifiedTime,size,appProperties,parents,shortcutDetails';
function documentFromDrive(f:DriveFile):Doc{return {id:f.id,driveId:f.id,parentIds:f.parents||[],name:f.name.replace(/\.pdf$/i,''),type:f.mimeType==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'?'DOCX':f.mimeType==='application/pdf'?'PDF':f.mimeType==='application/vnd.google-apps.form'?'FORM':'DOC',category:f.appProperties?.role==='template'?'Templates':'Google Workspace',updated:(f.modifiedTime||new Date().toISOString()).slice(0,10),size:f.size?`${Math.max(1,Math.round(Number(f.size)/1024))} KB`:'Google file',url:f.webViewLink||`https://drive.google.com/file/d/${f.id}/view`}}
async function listFiles(q:string,pageToken?:string){return googleJson<{files:DriveFile[];nextPageToken?:string}>(drive+'/files?'+new URLSearchParams({q,pageSize:'1000',fields:`nextPageToken,files(${fields})`,supportsAllDrives:'true',includeItemsFromAllDrives:'true',...(pageToken?{pageToken}:{})}))}
export async function folder(name:string,parent?:string,key?:string){const stable=key||name;const q=`trashed=false and mimeType='application/vnd.google-apps.folder' and appProperties has { key='jymFolder' and value='${quote(stable)}' }${parent?` and '${quote(parent)}' in parents`:''}`;const found=await listFiles(q);if(found.files[0])return found.files[0].id;return (await googleJson<DriveFile>(drive+'/files?fields=id',json({name,mimeType:'application/vnd.google-apps.folder',...(parent?{parents:[parent]}:{}),appProperties:{jymFolder:stable}}))).id}
function rememberPortalFolders(s:LiveState){if(!s.folders)return;const f=s.folders;s.folderOptions??=[];for(const item of [{id:f.root,name:'Jymmanuel Document Portal',parentIds:[]},{id:f.templates,name:'Templates',parentIds:[f.root]},{id:f.assignments,name:'Assignments',parentIds:[f.root]},{id:f.submissions,name:'Submissions',parentIds:[f.root]}]){if(!s.folderOptions.some(existing=>existing.id===item.id))s.folderOptions.push(item)}}
export async function ensureFolders(s:LiveState,email:string){if(s.folders){rememberPortalFolders(s);return s.folders;}const root=await folder('Jymmanuel Document Portal',undefined,'jym-root');const templates=await folder('Templates',root),assignments=await folder('Assignments',root),submissions=await folder('Submissions',root);s.folders={root,templates,assignments,submissions};rememberPortalFolders(s);saveLive(email,s);return s.folders}
export async function syncDrive(s:LiveState,email:string){
 const result:Doc[]=[],folders:LibraryFolder[]=[],shortcuts:DriveFile[]=[];let pageToken:string|undefined;
 do{
  const page=await listFiles("trashed=false and (mimeType='application/vnd.openxmlformats-officedocument.wordprocessingml.document' or mimeType='application/pdf' or mimeType='application/vnd.google-apps.document' or mimeType='application/vnd.google-apps.form' or mimeType='application/vnd.google-apps.folder' or mimeType='application/vnd.google-apps.shortcut')",pageToken);
  for(const file of page.files){
   if(file.mimeType==='application/vnd.google-apps.folder')folders.push({id:file.id,name:file.name,parentIds:file.parents||[]});
   else if(file.mimeType==='application/vnd.google-apps.shortcut'){if(file.appProperties?.role==='template'||file.parents?.includes(s.folders?.templates||''))shortcuts.push(file);}
   else if(!['submission','performance-draft','performance-pdf'].includes(file.appProperties?.role||''))result.push(documentFromDrive(file));
  }
  pageToken=page.nextPageToken;
  if(result.length+folders.length+shortcuts.length>20000)throw Error('Drive library is too large for this local MVP. Use a dedicated demo account.');
 }while(pageToken);
 for(const shortcut of shortcuts){
  const id=shortcut.shortcutDetails?.targetId;if(!id)continue;
  let doc=result.find(d=>d.id===id);
  if(!doc){try{const target=await googleJson<DriveFile>(drive+`/files/${encodeURIComponent(id)}?`+new URLSearchParams({fields,supportsAllDrives:'true'}));if(!['application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/pdf','application/vnd.google-apps.document','application/vnd.google-apps.form'].includes(target.mimeType))continue;doc=documentFromDrive(target);result.push(doc)}catch(e){if(e instanceof GoogleError&&[403,404].includes(e.status))continue;throw e}}
  doc.parentIds=[...new Set([...(doc.parentIds||[]),...(shortcut.parents||[])])];doc.templateShortcutId=shortcut.id;doc.category='Templates';
 }
 for(const doc of result){if(s.documentNames?.[doc.id])doc.name=s.documentNames[doc.id];}
 s.documents=result;s.folderOptions=folders;s.driveSynced=new Date().toISOString();
 log(s,`Synced ${result.length} documents from Google Drive`);saveLive(email,s);
}
export async function uploadPdf(name:string,bytes:Buffer,parent:string,properties:Record<string,string>){const boundary='jym_'+randomUUID();const metadata={name:name.endsWith('.pdf')?name:name+'.pdf',parents:[parent],mimeType:'application/pdf',appProperties:properties};const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/pdf\r\n\r\n`),bytes,Buffer.from(`\r\n--${boundary}--\r\n`)]);return googleJson<DriveFile>('https://www.googleapis.com/upload/drive/v3/files?'+new URLSearchParams({uploadType:'multipart',fields}),{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body})}
export async function uploadTemplate(s:LiveState,email:string,name:string,bytes:Buffer){if(bytes.length>maxPdf||!isPdf(bytes))throw Error('Select a valid PDF no larger than 15 MB.');const folders=await ensureFolders(s,email);const file=await uploadPdf(name,bytes,folders.templates,{role:'template'});s.documents.unshift(documentFromDrive(file));log(s,`${name} uploaded to Google Drive Templates`);saveLive(email,s)}
export async function addGoogleTemplate(s:LiveState,email:string,id:string,name?:string){
 const displayName=name?.trim();if(name!==undefined&&(!displayName||displayName.length>160))throw Error('Enter a document name between 1 and 160 characters.');
 if(!/^[-\w]+$/.test(id))throw Error('Invalid Google Drive file ID.');
 const file=await googleJson<DriveFile>(drive+`/files/${id}?`+new URLSearchParams({fields,supportsAllDrives:'true'}));
 if(!['application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/pdf','application/vnd.google-apps.document','application/vnd.google-apps.form'].includes(file.mimeType))throw Error('Choose a PDF, Google Doc or Google Form.');
 const folders=await ensureFolders(s,email);const doc=documentFromDrive(file);doc.name=displayName||s.documentNames?.[id]||doc.name;
 if(!file.parents?.includes(folders.templates)){
  let shortcut:DriveFile|undefined;let pageToken:string|undefined;
  do{const page=await listFiles(`trashed=false and mimeType='application/vnd.google-apps.shortcut' and '${quote(folders.templates)}' in parents`,pageToken);shortcut=page.files.find(f=>f.shortcutDetails?.targetId===id);pageToken=page.nextPageToken}while(!shortcut&&pageToken);
  if(!shortcut)shortcut=await googleJson<DriveFile>(drive+'/files?'+new URLSearchParams({fields,supportsAllDrives:'true'}),json({name:doc.name,mimeType:'application/vnd.google-apps.shortcut',parents:[folders.templates],shortcutDetails:{targetId:id},appProperties:{role:'template',sourceFileId:id}}));
  if(!shortcut.parents?.includes(folders.templates)||shortcut.shortcutDetails?.targetId!==id)throw Error('Could not verify the template shortcut in Google Drive.');
  doc.templateShortcutId=shortcut.id;doc.parentIds=[...new Set([...(file.parents||[]),folders.templates])];
 }
 if(displayName){s.documentNames??={};s.documentNames[id]=displayName;}
 doc.category='Templates';s.documents=[doc,...s.documents.filter(d=>d.id!==id)];log(s,`${doc.name} added to Templates`);saveLive(email,s);return doc;
}
export async function linkGoogleDocument(s:LiveState,email:string,url:string,name?:string){
 let u:URL;try{u=new URL(url)}catch{throw Error('Enter a valid Google document URL.');}
 if(u.protocol!=='https:'||!['docs.google.com','drive.google.com'].includes(u.hostname))throw Error('Use the full Google Drive, Docs or Forms editor URL, not a shortened link.');
 if(/\/forms\/(?:u\/\d+\/)?d\/e\//.test(u.pathname))throw Error('This is a responder link. Open the form editor and copy its /edit URL to add the form to Templates.');
 const id=u.pathname.match(/\/d\/([\w-]+)/)?.[1]||u.searchParams.get('id');
 if(!id||!/^[-\w]+$/.test(id))throw Error('Could not find a Drive file ID. Use the document’s editor or Drive URL.');
 try{return await addGoogleTemplate(s,email,id,name)}catch(e){if(e instanceof GoogleError&&e.status===404)throw Error('The connected Google account cannot find this file. Use its full editor URL and check that this account can open it.');throw e}
}
const encoded=(s:string)=>'=?UTF-8?B?'+Buffer.from(s.replace(/[\r\n]/g,' ')).toString('base64')+'?=';
const base64Lines=(bytes:Buffer)=>bytes.toString('base64').match(/.{1,76}/g)?.join('\r\n')||'';
export function emailMime(a:Assignment,r:Recipient,doc:Doc,from:string,attachment?:Buffer){const boundary='jym_'+randomUUID();const body=`Hello ${r.name},\n\n${a.message||'Please complete the assigned document.'}\n\nAssignment: ${a.name}\nAssignment ID: ${a.id}\nDue: ${a.due||'No due date'}\n${attachment?`${a.workflow==='performance'?'Your performance review PDF is attached. Please sign it and reply to this email with the signed PDF.':'The PDF is attached. Complete it on your device and reply to this email with the completed PDF.'}`:`Document: ${doc.type==='FORM'?doc.url?.replace(/\/edit.*$/, '/viewform'):doc.url}\nOpen the link using your Google account. Existing document access permissions apply. ${doc.type==='FORM'?'Submit the form while signed in with '+r.email+'. Your verified Google account email will be used to track completion. No PDF reply is needed.':'For PDF return tracking, reply to this email with the completed PDF attached.'}`}\n\nKeep this email thread and assignment ID in your reply.\n\nJymmanuel Management`;
const lines=[`From: ${from}`,`To: ${r.email}`,`Subject: ${encoded(`[${a.id}] ${a.name}`)}`,`Message-ID: <${r.rfcMessageId}>`,'MIME-Version: 1.0',`Content-Type: multipart/mixed; boundary="${boundary}"`,'',`--${boundary}`,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',base64Lines(Buffer.from(body))];if(attachment)lines.push(`--${boundary}`,'Content-Type: application/pdf','Content-Disposition: attachment; filename="assignment.pdf"','Content-Transfer-Encoding: base64','',base64Lines(attachment));lines.push(`--${boundary}--`,'');return Buffer.from(lines.join('\r\n')).toString('base64url')}
async function downloadPdf(doc:Doc){if(!doc.driveId||!/^[-\w]+$/.test(doc.driveId))throw Error('Document must come from Google Drive.');const metadata=await googleJson<DriveFile>(drive+`/files/${doc.driveId}?fields=id,size,mimeType&supportsAllDrives=true`);if(Number(metadata.size)>maxPdf)throw Error('PDFs sent by this MVP must be 15 MB or smaller.');const bytes=Buffer.from(await(await googleFetch(drive+`/files/${doc.driveId}?alt=media&supportsAllDrives=true`)).arrayBuffer());if(bytes.length>maxPdf||!isPdf(bytes))throw Error('Google Drive did not return a valid PDF under 15 MB.');return bytes}
export async function sendAssignment(s:LiveState,email:string,input:{name:string;docId:string;groups:string[];due:string;message:string;requestId:string}){const old=s.assignments.find(a=>a.requestId===input.requestId);if(old)return old;const doc=s.documents.find(d=>d.id===input.docId);if(!doc)throw Error('Select a document from the live Drive library.');if(!input.name||input.name.length>160||input.message.length>4000)throw Error('Enter an assignment name up to 160 characters and message up to 4,000 characters.');if(input.due&&(!/^\d{4}-\d{2}-\d{2}$/.test(input.due)||input.due<new Date().toISOString().slice(0,10)))throw Error('Choose today or a future due date.');const groups=s.groups.filter(g=>input.groups.includes(g.id));const members=[...new Map(groups.flatMap(g=>g.members).map(p=>[p.email.toLowerCase(),p])).values()];if(!members.length||members.length>100)throw Error('Choose between 1 and 100 recipients per assignment.');if(members.some(p=>!/^[-\w.+]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(p.email)||p.email.endsWith('.example')))throw Error('Use real, valid employee addresses. Sample .example addresses cannot receive live email.');if(doc.type==='FORM'){const form=await prepareForm(s,email,doc.driveId||doc.id);if(!form.responderUri)throw Error('Google Form responder link is unavailable.');doc.url=form.responderUri;}const attachment=doc.type==='PDF'?await downloadPdf(doc):undefined;const folders=await ensureFolders(s,email);const id=`JYM-${new Date().toISOString().slice(0,7).replace('-','')}-${randomUUID().slice(0,8).toUpperCase()}`;const month=await folder(new Date().toISOString().slice(0,7),folders.assignments);const assignmentFolder=await folder(input.name,month,id);const a:Assignment={...input,...(doc.type==='FORM'?{formId:doc.driveId||doc.id}:{}),id,created:new Date().toISOString(),driveFolderId:assignmentFolder,recipients:members.map(p=>({...p,status:'Pending',threadId:'',delivery:'ready',rfcMessageId:randomUUID()+'@jymmanuel.local'}))};s.assignments.unshift(a);saveLive(email,s);await deliver(s,email,a,doc,attachment);return a}
export async function deliver(s:LiveState,email:string,a:Assignment,doc:Doc,attachment?:Buffer){for(const r of a.recipients){if(r.delivery!=='ready'&&r.delivery!=='failed')continue;if(/@[^@]+\.(example|invalid)$/i.test(r.email)){r.delivery='failed';r.deliveryError='Mock email address: live delivery is disabled.';saveLive(email,s);continue;}r.delivery='sending';r.deliveryStartedAt=new Date().toISOString();r.deliveryError=undefined;saveLive(email,s);try{const sent=await googleJson<{id:string;threadId:string}>(gmail+'/messages/send',json({raw:emailMime(a,r,doc,email,attachment)}));if(!sent.id||!sent.threadId)throw Error('Missing send result');r.messageId=sent.id;r.threadId=sent.threadId;r.delivery='sent';r.sentAt=new Date().toISOString();}catch(e){r.delivery=e instanceof GoogleError&&[400,401,403,404,405,413,422,429].includes(e.status)?'failed':'uncertain';r.deliveryError=r.delivery==='uncertain'?'Delivery outcome is uncertain. Check Gmail Sent before taking further action.':(e as Error).message}saveLive(email,s)}log(s,`${a.name}: ${a.recipients.filter(r=>r.delivery==='sent').length}/${a.recipients.length} Gmail sends confirmed`);saveLive(email,s)}
export async function retryDelivery(s:LiveState,email:string,id:string){const a=s.assignments.find(a=>a.id===id);if(!a)throw Error('Assignment not found.');if(a.workflow==='availability')throw Error('Use Availability Collection to send or retry this weekly form.');if(a.workflow==='hiring')throw Error('Use Hiring Process to send the candidate form.');if(a.workflow==='performance')throw Error('Use Performance Review to send the individual prepared PDF.');const doc=s.documents.find(d=>d.id===a.docId);if(!doc)throw Error('Source document is unavailable.');await deliver(s,email,a,doc,doc.type==='PDF'?await downloadPdf(doc):undefined)}
export type GmailPart={filename?:string;mimeType?:string;headers?:{name:string;value:string}[];body?:{size?:number;data?:string;attachmentId?:string};parts?:GmailPart[]};
export type GmailMessage={id:string;threadId:string;internalDate?:string;labelIds?:string[];payload?:GmailPart};
export const header=(m:GmailMessage,name:string)=>m.payload?.headers?.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value||'';
function allParts(p?:GmailPart):GmailPart[]{return p?[p,...(p.parts||[]).flatMap(allParts)]:[]}
export function decodeMailHeader(value:string){return value.replace(/=\?([^?]+)\?([bq])\?([^?]*)\?=/gi,(_match,charset:string,encoding:string,text:string)=>{try{const bytes=encoding.toLowerCase()==='b'?Buffer.from(text,'base64'):Buffer.from(text.replace(/_/g,' ').replace(/=([0-9a-f]{2})/gi,(_m:string,hex:string)=>String.fromCharCode(parseInt(hex,16))),'latin1');return new TextDecoder(charset).decode(bytes)}catch{return _match}})}
export function matchReply(s:LiveState,m:GmailMessage){const subject=decodeMailHeader(header(m,'subject'));const ids=[...new Set(subject.match(/JYM-\d{6}-[A-Z0-9]+/gi)?.map(s=>s.toUpperCase())||[])];const from=header(m,'from').trim();const sender=(from.match(/<([^<>]+)>/)?.[1]||from).trim().toLowerCase();const a=ids.length===1?s.assignments.find(a=>a.id===ids[0]):undefined;const r=a?.recipients.find(r=>r.email.toLowerCase()===sender&&r.threadId===m.threadId&&r.delivery==='sent');return {a,r,sender,id:ids.join(', '),reason:!a?'Assignment ID could not be matched uniquely.':!r?'Sender and Gmail thread do not match this assignment.':''}}
async function processReply(s:LiveState,email:string,m:GmailMessage){if(s.processedMessages.includes(m.id))return;const matched=matchReply(s,m);const {a,r,sender}=matched;if(s.assignments.some(a=>a.recipients.some(r=>r.messageId===m.id)))return;let reason=matched.reason||(a?.formId?'This assignment requires a Google Form submission; an email attachment does not complete it.':'');const pdfs=allParts(m.payload).filter(p=>p.filename&&(/\.pdf$/i.test(p.filename)||p.mimeType==='application/pdf'));
if(!reason&&r?.status==='Completed')reason='An additional return arrived after completion; check it manually.';
if(!reason&&pdfs.length!==1)reason=pdfs.length>1?'Multiple PDF attachments need manual selection.':'No valid PDF attachment found.';
let bytes:Buffer|undefined;const pdf=pdfs[0];if(!reason&&pdf){if((pdf.body?.size||0)>maxPdf)reason='PDF attachment exceeds the 15 MB limit.';else{let data=pdf.body?.data;if(!data&&pdf.body?.attachmentId)data=(await googleJson<{data:string}>(gmail+`/messages/${m.id}/attachments/${pdf.body.attachmentId}`)).data;bytes=Buffer.from(data||'','base64url');if(bytes.length>maxPdf||!isPdf(bytes))reason='Attachment is not a valid PDF under 15 MB.'}}
if(reason){s.reviews.unshift({id:randomUUID(),assignmentId:matched.id,sender,reason,created:new Date().toISOString(),gmailMessageId:m.id});log(s,`Gmail reply from ${sender||'unknown sender'} held for review`)}else if(a&&r&&bytes){const folders=await ensureFolders(s,email);const month=await folder(a.created.slice(0,7),folders.submissions);const assignmentFolder=await folder(a.name,month,a.id);const employeeFolder=await folder(r.name,assignmentFolder,r.email);const prior=await listFiles(`trashed=false and appProperties has { key='gmailMessageId' and value='${quote(m.id)}' }`);const stored=prior.files[0]||await uploadPdf(pdf.filename||'Completed document.pdf',bytes,employeeFolder,{role:'submission',assignmentId:a.id,employee:r.email,gmailMessageId:m.id});r.status='Completed';r.returnedDriveId=stored.id;r.returnedUrl=stored.webViewLink||`https://drive.google.com/file/d/${stored.id}/view`;r.returnedName=pdf.filename;r.returnedMessageId=m.id;r.received=m.internalDate?new Date(Number(m.internalDate)).toISOString():new Date().toISOString();r.destination=`Submissions/${a.created.slice(0,7)}/${a.name}/${r.name}/`;log(s,`${r.name} returned ${a.name} — saved to Google Drive`)}s.processedMessages.push(m.id);saveLive(email,s)}
export async function collectReplies(s:LiveState,email:string){try{
// Recover ambiguous sends by the unique RFC Message-ID; never blindly resend.
for(const a of s.assignments)for(const r of a.recipients){if(!['sending','uncertain'].includes(r.delivery||'')||!r.rfcMessageId)continue;const found=await googleJson<{messages?:{id:string;threadId:string}[]}>(gmail+'/messages?'+new URLSearchParams({q:`in:sent rfc822msgid:${r.rfcMessageId}`,maxResults:'2'}));if(found.messages?.length===1){r.delivery='sent';r.messageId=found.messages[0].id;r.threadId=found.messages[0].threadId;r.deliveryError=undefined;saveLive(email,s)}}
// Read all known assignment threads, including replies with an edited subject.
const threads=[...new Set(s.assignments.flatMap(a=>a.recipients.map(r=>r.threadId)).filter(Boolean))];for(const thread of threads){const t=await googleJson<{messages?:GmailMessage[]}>(gmail+`/threads/${thread}?format=full`);for(const m of t.messages||[])await processReply(s,email,m)}
// Catch new/unmatched assignment emails. Scan pages over successive runs, with an overlap.
const connection=readConnection();const since=Math.floor(new Date(s.scanAfter||connection?.connectedAt||new Date().toISOString()).getTime()/1000)-86400;const page=await googleJson<{messages?:{id:string}[];nextPageToken?:string}>(gmail+'/messages?'+new URLSearchParams({q:`after:${since} subject:JYM- -in:sent -in:trash -in:spam`,maxResults:'100',...(s.mailPageToken?{pageToken:s.mailPageToken}:{})}));for(const ref of page.messages||[]){if(s.processedMessages.includes(ref.id))continue;const m=await googleJson<GmailMessage>(gmail+`/messages/${ref.id}?format=full`);if(/JYM-\d{6}-[A-Z0-9]+/i.test(decodeMailHeader(header(m,'subject'))))await processReply(s,email,m)}s.mailPageToken=page.nextPageToken;if(!page.nextPageToken)s.scanAfter=new Date().toISOString();s.lastCollected=new Date().toISOString();s.collectionError=undefined;saveLive(email,s);
}catch(e){s.collectionError=(e as Error).message;saveLive(email,s);throw e}}
export async function collectAllResponses(s:LiveState,email:string){try{await collectReplies(s,email)}catch{/* Gmail error is persisted; Forms must still be checked. */}await collectFormResponses(s,email);await trackAvailabilityResponses(s,email)}
export function collectorIntervalSeconds(){const seconds=Number(process.env.GOOGLE_POLL_INTERVAL_SECONDS??60);return Number.isFinite(seconds)&&seconds>0?Math.max(30,seconds):0;}
export async function trackAvailabilityResponses(s:LiveState,email:string){
 s.availabilityTracking={...s.availabilityTracking,lastAttempt:new Date().toISOString(),error:undefined};saveLive(email,s);
 try{await collectAvailability(s,email);const failed=(s.timetable?.weeks||[]).filter(w=>!w.sample&&w.assignmentId&&w.error);
  if(failed.length)throw Error(`${failed.length} collection(s) could not sync. See the collection error for details.`);
  s.availabilityTracking.lastSuccess=new Date().toISOString();
 }catch(e){s.availabilityTracking.error=(e as Error).message;}
 saveLive(email,s);
}
export async function runCollectorCycle(s:LiveState,email:string){
 // Capture old replies before a reusable form is sent for another week.
 await trackAvailabilityResponses(s,email);
 try{await runWeeklyAvailability(s,email)}catch(e){s.collectionError=(e as Error).message;saveLive(email,s)}
 try{await collectReplies(s,email)}catch{/* Gmail failures must not block form tracking. */}
 try{await collectFormResponses(s,email)}catch(e){s.formsErrors=[(e as Error).message];saveLive(email,s)}
}
export function startCollector(){
 const g=globalThis as typeof globalThis & {jymCollector?:ReturnType<typeof setInterval>;jymCollecting?:boolean};const seconds=collectorIntervalSeconds();
 if(g.jymCollector||!seconds||process.env.NEXT_PHASE==='phase-production-build')return;
 g.jymCollector=setInterval(()=>{if(g.jymCollecting)return;g.jymCollecting=true;
  void exclusive(async()=>{const connection=readConnection();if(!connection)return;const s=loadLive(connection.email);await runCollectorCycle(s,connection.email)}).catch(e=>{console.error('Background response collection failed:',e instanceof Error?e.message:'Unknown error')}).finally(()=>{g.jymCollecting=false});
 },seconds*1000);g.jymCollector.unref();
}
