import {createHash} from 'node:crypto';
import {googleJson,GoogleError} from './google-auth';
import {saveLive,type LiveState} from './live-store';
import {hiringProgress} from './hiring-model';
const sheets='https://sheets.googleapis.com/v4/spreadsheets/';
const json=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
export function hiringRows(s:LiveState){return [['Candidate ID','Name','Email','Phone','Position','Interview','Interview date','Acknowledgement','Trial result','Trial date','Employee Info','Current stage','Final status','Employment type','Notes','Added','Updated','Acknowledgement response','Employee information response'],...(s.hiring?.candidates||[]).map(c=>{const p=hiringProgress(c,s.assignments);return [c.id,c.name,c.email,c.phone,c.position,c.interview,c.interviewAt||'',p.acknowledgement,c.trial,c.trialAt||'',p.employeeInformation,p.current,p.final,c.employment,c.notes,c.created,c.updated,p.ack?.received||'',p.form?.received||'']})]}
export async function syncHiringSheet(s:LiveState,email:string,create=false){if(!s.hiring)return;const h=s.hiring;if(!h.sheetId&&!create)return;
 try{
  if(!h.sheetId){const found=await googleJson<{files:{id:string}[]}>('https://www.googleapis.com/drive/v3/files?'+new URLSearchParams({q:"trashed=false and mimeType='application/vnd.google-apps.spreadsheet' and appProperties has { key='jymHiring' and value='tracking-v1' }",fields:'files(id)',pageSize:'100'}));if(found.files.length>1)throw Error('More than one hiring tracking sheet was found. Resolve the duplicate before syncing.');h.sheetId=found.files[0]?.id;if(!h.sheetId){const f=await googleJson<{id:string}>('https://www.googleapis.com/drive/v3/files?fields=id',json({name:'Jymmanuel — Hiring Process Tracking',mimeType:'application/vnd.google-apps.spreadsheet',appProperties:{jymHiring:'tracking-v1'}}));if(!f.id)throw Error('Could not create tracking sheet.');h.sheetId=f.id}saveLive(email,s)}
  const values=hiringRows(s),digest=createHash('sha256').update(JSON.stringify(values)).digest('hex');if(h.sheetHash===digest&&!h.syncError)return;
  if(h.sheetTabId===undefined){const doc=await googleJson<{sheets:{properties:{sheetId:number}}[]}>(sheets+h.sheetId+'?fields=sheets.properties.sheetId');if(!doc.sheets?.length)throw Error('Tracking sheet has no worksheet.');h.sheetTabId=doc.sheets[0].properties.sheetId;saveLive(email,s)}
  const rowCount=Math.max(values.length,h.sheetRows||0,2);await googleJson(sheets+h.sheetId+':batchUpdate',json({requests:[{updateSheetProperties:{properties:{sheetId:h.sheetTabId,gridProperties:{rowCount:Math.max(1000,rowCount),columnCount:19,frozenRowCount:1}},fields:'gridProperties'}},{updateCells:{range:{sheetId:h.sheetTabId,startRowIndex:0,endRowIndex:rowCount,startColumnIndex:0,endColumnIndex:19},rows:values.map(row=>({values:row.map(text=>({userEnteredValue:{stringValue:text}}))})),fields:'userEnteredValue'}},{repeatCell:{range:{sheetId:h.sheetTabId,startRowIndex:0,endRowIndex:1,startColumnIndex:0,endColumnIndex:19},cell:{userEnteredFormat:{backgroundColor:{red:0.03,green:0.49,blue:0.47},textFormat:{bold:true,foregroundColor:{red:1,green:1,blue:1}}}},fields:'userEnteredFormat'}},{autoResizeDimensions:{dimensions:{sheetId:h.sheetTabId,dimension:'COLUMNS',startIndex:0,endIndex:19}}}]}));
  h.sheetRows=values.length;h.sheetHash=digest;h.lastSynced=new Date().toISOString();h.syncError=undefined;
 }catch(e){h.syncError=e instanceof GoogleError&&e.status===403?'Enable Google Sheets API in your Google Cloud project, then retry Sheet sync. Check the connected account’s access if it remains denied.':(e as Error).message}saveLive(email,s)
}
