import fs from 'node:fs';
import {shiftTemplates} from './shift-templates';
import {suppliedRules,type BusinessRule} from './business-rules';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {hash,secretDir} from './google-auth';
import type {LiveState} from './live-store';
import type {Candidate} from './hiring-model';
import type {OfficialEmployee} from './employee-model';
function fingerprint(state:LiveState){const copy={...state} as Record<string,unknown>;for(const key of ['businessRules','workspaceRevision','workspaceFingerprint','lastCollected','lastFormsChecked','collectionError','formsErrors','availabilityTracking','mailPageToken','scanAfter','driveSynced'])delete copy[key];const stable=(v:unknown):unknown=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,stable(x)])):v;return hash(JSON.stringify(stable(copy)))}
const empty=():LiveState=>({documents:[],groups:[],assignments:[],reviews:[],activity:[],processedMessages:[],employees:[]});
function open(){fs.mkdirSync(secretDir,{recursive:true,mode:0o700});const filename=path.join(secretDir,'portal.sqlite');if(!fs.existsSync(filename))fs.closeSync(fs.openSync(filename,'wx',0o600));const db=new DatabaseSync(filename);db.exec(`PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS business_rule(rule_id TEXT NOT NULL,version INTEGER NOT NULL,area TEXT NOT NULL,description TEXT NOT NULL,parameters_json TEXT NOT NULL,usage TEXT NOT NULL,source TEXT NOT NULL,PRIMARY KEY(rule_id,version));
CREATE TABLE IF NOT EXISTS workspace(account_id TEXT PRIMARY KEY,state_json TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS person(account_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL COLLATE NOCASE,phone TEXT NOT NULL,PRIMARY KEY(account_id,id),UNIQUE(account_id,email));
CREATE TABLE IF NOT EXISTS hiring_candidate(account_id TEXT NOT NULL,id TEXT NOT NULL,person_id TEXT NOT NULL,record_json TEXT NOT NULL,PRIMARY KEY(account_id,id),UNIQUE(account_id,person_id),FOREIGN KEY(account_id,person_id) REFERENCES person(account_id,id));
CREATE TABLE IF NOT EXISTS official_employee(account_id TEXT NOT NULL,id TEXT NOT NULL,person_id TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('Part-Time','Full-Time','Casual')),casual_level INTEGER,status TEXT NOT NULL CHECK(status IN ('Active','Inactive')),source_candidate_id TEXT NOT NULL,record_json TEXT NOT NULL,PRIMARY KEY(account_id,id),UNIQUE(account_id,person_id),UNIQUE(account_id,source_candidate_id),FOREIGN KEY(account_id,person_id) REFERENCES person(account_id,id),CHECK((type='Casual' AND casual_level IN (1,2) AND casual_level IS NOT NULL) OR (type!='Casual' AND casual_level IS NULL)));
CREATE TABLE IF NOT EXISTS recruitment_history(account_id TEXT NOT NULL,candidate_id TEXT NOT NULL,person_id TEXT NOT NULL,employee_id TEXT NOT NULL,snapshot_json TEXT NOT NULL,converted_at TEXT NOT NULL,PRIMARY KEY(account_id,candidate_id),FOREIGN KEY(account_id,person_id) REFERENCES person(account_id,id));
CREATE TABLE IF NOT EXISTS employment_history(account_id TEXT NOT NULL,id INTEGER PRIMARY KEY AUTOINCREMENT,employee_id TEXT NOT NULL,type TEXT NOT NULL,casual_level INTEGER,effective_from TEXT NOT NULL,effective_to TEXT);
CREATE TRIGGER IF NOT EXISTS candidate_not_employee BEFORE INSERT ON hiring_candidate WHEN EXISTS(SELECT 1 FROM official_employee WHERE account_id=NEW.account_id AND person_id=NEW.person_id) BEGIN SELECT RAISE(ABORT,'Person is already an official employee'); END;
CREATE TRIGGER IF NOT EXISTS employee_not_candidate BEFORE INSERT ON official_employee WHEN EXISTS(SELECT 1 FROM hiring_candidate WHERE account_id=NEW.account_id AND person_id=NEW.person_id) BEGIN SELECT RAISE(ABORT,'Person is still a candidate'); END;`);const insertRule=db.prepare('INSERT OR IGNORE INTO business_rule VALUES(?,?,?,?,?,?,?)');for(const r of suppliedRules)insertRule.run(r.id,r.version,r.area,r.description,JSON.stringify(r.parameters),r.usage,r.source);return db}
function persist(db:DatabaseSync,account:string,s:LiveState){
 const candidates=s.hiring?.candidates||[],employees=s.employees||[];const people=[...candidates,...employees];const emails=new Set<string>(),ids=new Set<string>();for(const p of people){const address=p.email.trim().toLowerCase(),id=p.personId||p.id;if(emails.has(address)||ids.has(id))throw Error('Duplicate person in Candidate or Official Employee. No changes were saved.');emails.add(address);ids.add(id)}
 // Snapshot operations are committed together; no candidate can disappear halfway through a transfer.
 db.exec('BEGIN IMMEDIATE');try{
 const priorState=db.prepare('SELECT state_json FROM workspace WHERE account_id=?').get(account) as {state_json:string}|undefined;const revision=priorState?(JSON.parse(priorState.state_json).workspaceRevision||0):0;const workspaceFingerprint=fingerprint(s);const nextRevision=revision+(priorState&&JSON.parse(priorState.state_json).workspaceFingerprint===workspaceFingerprint?0:1);

 const prior=db.prepare('SELECT id,type,casual_level FROM official_employee WHERE account_id=?').all(account) as {id:string;type:string;casual_level:number|null}[];
 db.prepare('DELETE FROM hiring_candidate WHERE account_id=?').run(account);db.prepare('DELETE FROM official_employee WHERE account_id=?').run(account);
 // Historical names and email addresses remain in recruitment snapshots; the current person rows are canonical.
 db.prepare('DELETE FROM person WHERE account_id=? AND id NOT IN (SELECT person_id FROM recruitment_history WHERE account_id=?)').run(account,account);
 const person=db.prepare('INSERT INTO person(account_id,id,name,email,phone) VALUES(?,?,?,?,?) ON CONFLICT(account_id,id) DO UPDATE SET name=excluded.name,email=excluded.email,phone=excluded.phone');
 for(const p of people)person.run(account,p.personId||p.id,p.name,p.email.trim().toLowerCase(),p.phone||'');
 for(const c of candidates){const {name,email,phone,...record}=c;db.prepare('INSERT INTO hiring_candidate VALUES(?,?,?,?)').run(account,c.id,c.personId||c.id,JSON.stringify(record))}
 for(const e of employees){const {name,email,phone,hiringHistory,...record}=e;db.prepare('INSERT INTO official_employee VALUES(?,?,?,?,?,?,?,?)').run(account,e.id,e.personId,e.type,e.casualLevel??null,e.status,e.sourceCandidateId,JSON.stringify(record));db.prepare('INSERT INTO recruitment_history VALUES(?,?,?,?,?,?) ON CONFLICT(account_id,candidate_id) DO NOTHING').run(account,e.sourceCandidateId,e.personId,e.id,JSON.stringify(hiringHistory),e.created);
 const old=prior.find(p=>p.id===e.id);if(!old||old.type!==e.type||old.casual_level!==(e.casualLevel??null)){db.prepare('UPDATE employment_history SET effective_to=? WHERE account_id=? AND employee_id=? AND effective_to IS NULL').run(e.updated,account,e.id);db.prepare('INSERT INTO employment_history(account_id,employee_id,type,casual_level,effective_from) VALUES(?,?,?,?,?)').run(account,e.id,e.type,e.casualLevel??null,e.updated)}}
 const {employees:ignored,businessRules:ignoredRules,...workspace}=s;const state={...workspace,workspaceRevision:nextRevision,workspaceFingerprint,...(workspace.hiring?{hiring:{...workspace.hiring,candidates:[]}}:{})};db.prepare('INSERT INTO workspace VALUES(?,?,?) ON CONFLICT(account_id) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at').run(account,JSON.stringify(state),new Date().toISOString());db.exec('COMMIT');s.workspaceRevision=nextRevision;
 }catch(e){db.exec('ROLLBACK');throw e}
}
function migrate(db:DatabaseSync,email:string){const account=hash(email.toLowerCase());if(db.prepare('SELECT 1 FROM workspace WHERE account_id=?').get(account))return;const legacy=path.join(secretDir,account+'.json');let s=empty();if(fs.existsSync(legacy)){s=JSON.parse(fs.readFileSync(legacy,'utf8'));const backup=legacy+'.pre-sqlite.bak';if(!fs.existsSync(backup))fs.copyFileSync(legacy,backup,fs.constants.COPYFILE_EXCL);fs.chmodSync(backup,0o600)}persist(db,account,s)}
export function loadDatabase(email:string):LiveState{const db=open();try{migrate(db,email);const account=hash(email.toLowerCase());const row=db.prepare('SELECT state_json FROM workspace WHERE account_id=?').get(account) as {state_json:string};const s=JSON.parse(row.state_json) as LiveState;
 for(const w of s.rosters||[])for(const sh of w.shifts)if((sh.category as string)==='Trade')sh.category='Trial';
 for(const w of s.rosters||[])for(const sh of w.shifts)if(sh.templateId?.startsWith('SPENCER-')&&!shiftTemplates.some(t=>t.id===sh.templateId)){const current=shiftTemplates.find(t=>t.restaurant===sh.restaurant&&t.start===sh.start&&t.end===sh.end&&t.breakStart===sh.breakStart&&t.breakEnd===sh.breakEnd);sh.templateId=current?.id;}
 s.businessRules=(db.prepare('SELECT * FROM business_rule ORDER BY rule_id,version').all() as {rule_id:string;version:number;area:string;description:string;parameters_json:string;usage:BusinessRule['usage'];source:string}[]).map(r=>({id:r.rule_id,version:r.version,area:r.area,description:r.description,parameters:JSON.parse(r.parameters_json),usage:r.usage,source:r.source})).filter(r=>r.area!=='Floor shift templates'||suppliedRules.some(current=>current.id===r.id));
 const people=db.prepare('SELECT c.record_json,p.id AS person_id,p.name,p.email,p.phone FROM hiring_candidate c JOIN person p ON p.account_id=c.account_id AND p.id=c.person_id WHERE c.account_id=? ORDER BY c.rowid').all(account) as {record_json:string;person_id:string;name:string;email:string;phone:string}[];if(s.hiring||people.length)s.hiring={...(s.hiring||{}),candidates:people.map(p=>({...JSON.parse(p.record_json),personId:p.person_id,name:p.name,email:p.email,phone:p.phone}) as Candidate)};
 s.employees=(db.prepare('SELECT e.record_json,p.name,p.email,p.phone,h.snapshot_json FROM official_employee e JOIN person p ON p.account_id=e.account_id AND p.id=e.person_id JOIN recruitment_history h ON h.account_id=e.account_id AND h.candidate_id=e.source_candidate_id WHERE e.account_id=? ORDER BY e.rowid').all(account) as {record_json:string;name:string;email:string;phone:string;snapshot_json:string}[]).map(e=>({...JSON.parse(e.record_json),name:e.name,email:e.email,phone:e.phone,hiringHistory:JSON.parse(e.snapshot_json)}) as OfficialEmployee);return s;
 }finally{db.close()}}
export function saveDatabase(email:string,s:LiveState){const db=open();try{migrate(db,email);persist(db,hash(email.toLowerCase()),s)}finally{db.close()}}
