import {randomUUID,createHash} from 'node:crypto';
import {googleJson,googleFetch} from './google-auth';
import {saveLive,type LiveState} from './live-store';
import {ensureFolders,folder,uploadPdf,deliver,type DriveFile} from './google-workflow';
import {isPdf,log,type Assignment} from './demo-store';
const drive='https://www.googleapis.com/drive/v3';
const docx='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
const googleDoc='application/vnd.google-apps.document';
const post=(body:unknown)=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
function target(s:LiveState,id:string,person:string){const a=s.assignments.find(a=>a.id===id&&a.workflow==='performance');const r=a?.recipients.find(r=>r.id===person);if(!a||!r)throw Error('Performance review recipient not found.');return {a,r}}
function editable(delivery?:string){if(delivery&&['sending','uncertain','sent'].includes(delivery))throw Error('This review has already been sent or delivery needs checking.');}
async function importDocx(bytes:Buffer,metadata:unknown){if(bytes.length>15*1024*1024||bytes.subarray(0,2).toString()!=='PK')throw Error('Choose a valid DOCX under 15 MB.');const boundary='jym_'+randomUUID();const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${docx}\r\n\r\n`),bytes,Buffer.from(`\r\n--${boundary}--\r\n`)]);return googleJson<DriveFile>('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,mimeType,name,parents',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body})}
export async function uploadReviewTemplate(s:LiveState,email:string,name:string,bytes:Buffer){if(!name||name.length>160)throw Error('Enter a template name up to 160 characters.');const f=await ensureFolders(s,email);const file=await importDocx(bytes,{name,mimeType:googleDoc,parents:[f.templates],appProperties:{role:'template'}});if(file.mimeType!==googleDoc)throw Error('Word conversion failed.');s.documents.unshift({id:file.id,driveId:file.id,name,type:'DOC',category:'Templates',updated:new Date().toISOString().slice(0,10),size:'Google file',parentIds:[f.templates],url:`https://docs.google.com/document/d/${file.id}/edit`});saveLive(email,s)}
export async function createPerformance(s:LiveState,email:string,input:{name:string;docId:string;groups:string[];due:string;requestId:string}){
 const prior=s.assignments.find(a=>a.requestId===input.requestId);if(prior)return prior;
 const doc=s.documents.find(d=>d.id===input.docId&&['DOC','DOCX'].includes(d.type)&&d.parentIds?.includes(s.folders?.templates||''));if(!doc)throw Error('Choose a Word or Google Docs template from Templates.');
 if(!input.name||input.name.length>160)throw Error('Enter a batch name up to 160 characters.');if(input.due&&(!/^\d{4}-\d{2}-\d{2}$/.test(input.due)||input.due<new Date().toISOString().slice(0,10)))throw Error('Choose today or a future due date.');
 const members=[...new Map(s.groups.filter(g=>input.groups.includes(g.id)).flatMap(g=>g.members).map(p=>[p.email.toLowerCase(),p])).values()];if(!members.length||members.length>100||members.some(p=>!/^[-\w.+]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(p.email)||p.email.endsWith('.example')))throw Error('Select a group with 1–100 real employee addresses.');
 const f=await ensureFolders(s,email),id=`JYM-${new Date().toISOString().slice(0,7).replace('-','')}-${randomUUID().slice(0,8).toUpperCase()}`;
 const a:Assignment={...input,id,workflow:'performance',created:new Date().toISOString(),message:'Please review and sign your performance review, then reply to this email with the signed PDF attached.',driveFolderId:await folder(input.name,f.assignments,id),recipients:members.map(p=>({...p,id:randomUUID(),status:'Pending',threadId:'',rfcMessageId:randomUUID()+'@jymmanuel.local'}))};s.assignments.unshift(a);saveLive(email,s);log(s,`${a.name}: created performance review batch`);saveLive(email,s);await generateDrafts(s,email,a.id);return a;
}
export async function generateDrafts(s:LiveState,email:string,id:string){const a=s.assignments.find(a=>a.id===id&&a.workflow==='performance');if(!a||!a.driveFolderId)throw Error('Batch not found.');const meta=await googleJson<DriveFile>(`${drive}/files/${encodeURIComponent(a.docId)}?fields=id,mimeType,size`);if(![googleDoc,docx].includes(meta.mimeType))throw Error('Template must be DOCX or Google Docs.');if(Number(meta.size)>15*1024*1024)throw Error('DOCX must be under 15 MB.');let bytes:Buffer|undefined;
 for(const r of a.recipients){if(r.draftId)continue;try{const key=a.id+':'+r.id;const found=await googleJson<{files:DriveFile[]}>(drive+'/files?'+new URLSearchParams({q:`trashed=false and appProperties has { key='performanceKey' and value='${key}' }`,fields:'files(id,mimeType)',pageSize:'100'}));if(found.files.length>1)throw Error('Multiple draft copies found. Check Drive before continuing.');let file=found.files[0];
 if(!file){const metadata={name:`${a.name} — ${r.name} (${r.email})`,mimeType:googleDoc,parents:[a.driveFolderId],appProperties:{role:'performance-draft',performanceKey:key}};if(meta.mimeType===googleDoc)file=await googleJson<DriveFile>(`${drive}/files/${encodeURIComponent(a.docId)}/copy?fields=id,mimeType`,post(metadata));else{bytes??=Buffer.from(await(await googleFetch(`${drive}/files/${encodeURIComponent(a.docId)}?alt=media`)).arrayBuffer());file=await importDocx(bytes,metadata)}}
 if(!file.id||file.mimeType!==googleDoc)throw Error('Could not create a Google Docs copy.');r.draftId=file.id;r.preparationError=undefined;
 }catch(e){r.preparationError=(e as Error).message}saveLive(email,s)}
}
export async function preparePerformance(s:LiveState,email:string,id:string,person:string){const {a,r}=target(s,id,person);editable(r.delivery);if(!r.draftId||!a.driveFolderId)throw Error('Create this employee’s draft first.');const bytes=Buffer.from(await(await googleFetch(`${drive}/files/${encodeURIComponent(r.draftId)}/export?mimeType=application%2Fpdf`)).arrayBuffer());if(!isPdf(bytes)||bytes.length>15*1024*1024)throw Error('Google did not return a valid PDF. Google Docs exports are limited to 10 MB.');const file=await uploadPdf(`${a.name} - ${r.name}`,bytes,a.driveFolderId,{role:'performance-pdf',assignmentId:a.id,employee:r.email});if(!file.id)throw Error('PDF storage failed.');r.preparedPdfId=file.id;r.preparedHash=hash(bytes);r.preparedAt=new Date().toISOString();r.delivery=undefined;r.deliveryError=undefined;r.preparationError=undefined;saveLive(email,s)}
export async function preparedBytes(s:LiveState,id:string,person:string,version?:string){const {r}=target(s,id,person);if(version!==undefined&&version!==r.preparedPdfId)throw Error('The PDF version changed. Refresh this page to preview the current version.');if(!r.preparedPdfId||!r.preparedHash)throw Error('Prepare a PDF first.');const bytes=Buffer.from(await(await googleFetch(`${drive}/files/${encodeURIComponent(r.preparedPdfId)}?alt=media`)).arrayBuffer());if(!isPdf(bytes)||hash(bytes)!==r.preparedHash)throw Error('Prepared PDF has changed. Generate and review a new PDF before sending.');return bytes}
export async function performanceAction(s:LiveState,email:string,id:string,person:string,action:string,version:string){const {a,r}=target(s,id,person);
 if(action==='reviewed'){if(r.status!=='Completed'||!r.returnedDriveId)throw Error('Wait for a returned PDF and inspect the signature first.');r.reviewedAt=new Date().toISOString();saveLive(email,s);return}
 editable(r.delivery);
 if(action==='draft'){r.preparedPdfId=undefined;r.preparedHash=undefined;r.preparedAt=undefined;r.delivery=undefined;r.deliveryError=undefined;saveLive(email,s);return}
 if(!version||version!==r.preparedPdfId)throw Error('The PDF version changed. Refresh and preview the current PDF.');
 if(action==='ready'){await preparedBytes(s,id,person);r.delivery='ready';saveLive(email,s);return}
 if(action==='send'){if(!['ready','failed'].includes(r.delivery||''))throw Error('Preview the PDF and mark it ready first.');const bytes=await preparedBytes(s,id,person);await deliver(s,email,{...a,recipients:[r]},{id:r.preparedPdfId!,name:a.name,type:'PDF',category:'Performance',updated:'',size:''},bytes);return}
 throw Error('Unsupported performance action.');
}
