import {payRateVersion} from './pay-rates';
import type {LiveState} from './live-store';
import {payrollStatus,payrollRows,financeRows,isShiftAvailable,netMinutes} from './roster-model';
const cell=(value:unknown)=>{let str=value===undefined||value===null?'':String(value);if(/^[\s]*[=+\-@]/.test(str))str="'"+str;return '"'+str.replaceAll('"','""')+'"';};
const csv=(rows:unknown[][])=>'\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n');
const decimal=(value:number,places=6)=>Number(value.toFixed(places));
export function rosterCSV(s:LiveState,weekStart:string){return csv([['Week starting','Timezone','Employee','Employee type','Restaurant','Category','Template','Unpaid break start','Unpaid break end','Date','Start','End','Unpaid break minutes','Scheduled hours','Availability check','Data'],...(s.rosters?.find(w=>w.weekStart===weekStart)?.shifts||[]).map(sh=>[weekStart,'UTC+10',sh.employee.name,sh.employee.type==='Casual'?`Casual Level ${sh.employee.casualLevel}`:sh.employee.type,sh.restaurant||'Unclassified',sh.category||'Unclassified',sh.templateId||'Custom',sh.breakStart||'',sh.breakEnd||'',sh.date,sh.start,sh.end,sh.breakMinutes,decimal(netMinutes(sh)/60),sh.candidateId?'Manually scheduled trial':isShiftAvailable(s,weekStart,sh.employeeId,sh.date,sh)?'Within confirmed availability':'Availability changed - HR review required',/\.(example|invalid)$/i.test(sh.employee.email)?'MOCK':'Live'])]);}
export function financeCSV(s:LiveState,weekStart:string){return csv([['Week starting','Employee ID','Name','Email','Phone','Position','Employee type','Restaurant','Category','Currency','Hourly rates (Pay Rate Table)','Scheduled hours','Estimated scheduled pay','Confirmed actual hours','Confirmed actual pay','Unconfirmed shifts','Uncalculated planned shifts','Uncalculated actual shifts','Annual leave accrued hours','Personal leave accrued hours','Rate effective from','Calculation issues','Scope','Data'],...financeRows(s,weekStart).map(r=>[weekStart,r.employeeId,r.name,r.email,r.phone,r.position,r.type,r.restaurant,r.category,r.currency,r.rates.join(' / '),decimal(r.scheduledMinutes/60),r.estimated===null?r.status.label:r.estimated.toFixed(2),decimal(r.actualMinutes/60),r.actualPay===null?r.status.label:r.actualPay.toFixed(2),r.unconfirmed,r.missingScheduledRate,r.missingActualRate,decimal(r.annual),decimal(r.personal),payRateVersion.effectiveFrom,r.issues.join('; '),'Recalculated from current profiles; age on shift date; day rates include manually marked public holidays; unpaid breaks excluded; per-shift cent rounding; excludes tax, super, overtime, allowances and leave payments; leave values are accruals, not balances',r.sample?'MOCK':'Live'])]);}
const html=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function printableRoster(s:LiveState,weekStart:string){const shifts=s.rosters?.find(w=>w.weekStart===weekStart)?.shifts||[];return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Staff roster ${html(weekStart)}</title><style>body{font:14px system-ui;color:#172b23;margin:40px}h1{margin-bottom:8px}p{color:#50645a}table{width:100%;border-collapse:collapse;margin-top:24px}td,th{padding:12px 8px;border-bottom:1px solid #ddd;text-align:left}th{background:#edf3ef}tr{break-inside:avoid}button{padding:10px 18px;cursor:pointer}@media print{button{display:none}body{margin:0}@page{size:A4 landscape;margin:14mm}thead{display:table-header-group}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><h1>Staff roster · week of ${html(weekStart)}</h1><p>Fixed UTC+10 · Assigned shifts only · Generated ${html(new Date().toISOString())}</p>${shifts.some(sh=>/\.(example|invalid)$/i.test(sh.employee.email))?'<p><strong>Includes MOCK employees — testing data.</strong></p>':''}<table><thead><tr><th>Employee</th><th>Type</th><th>Restaurant / category</th><th>Date</th><th>Start</th><th>End</th><th>Unpaid break</th><th>Scheduled hours</th><th>Availability</th></tr></thead><tbody>${shifts.map(sh=>`<tr><td>${html(sh.employee.name)}</td><td>${html(sh.employee.type==='Casual'?`Casual Level ${sh.employee.casualLevel}`:sh.employee.type)}</td><td>${html(sh.restaurant||'Unclassified')} / ${html(sh.category||'Unclassified')}</td><td>${html(sh.date)}</td><td>${html(sh.start)}</td><td>${html(sh.end)}</td><td>${sh.breakMinutes} min${sh.breakStart?' ('+html(sh.breakStart)+'–'+html(sh.breakEnd)+')':''}</td><td>${decimal(netMinutes(sh)/60,2)}</td><td>${sh.candidateId?'Manually scheduled trial':isShiftAvailable(s,weekStart,sh.employeeId,sh.date,sh)?'Confirmed':'Changed — HR review required'}</td></tr>`).join('')}</tbody></table>${!shifts.length?'<p>No assigned shifts for this week.</p>':''}<p>This report contains no pay rates, private employee contact details or HR notes.</p></body></html>`;}

export function payrollCSV(s:LiveState,weekStart:string){
 return csv([['Week starting','Shift ID','Employee ID','Name','Employee type','Level','Age on shift date','Age group','Restaurant','Category','Date','Day type','Start','End','Unpaid break minutes','Paid scheduled hours','Currency','Hourly rate','Estimated scheduled pay','Actual start','Actual end','Actual unpaid break minutes','Confirmed actual hours','Confirmed actual pay','Status','Rate effective from','Calculation basis','Data'],...payrollRows(s,weekStart).map(p=>{
  const {shift:sh}=p,e=p.employee||sh.employee;
  return [weekStart,sh.id,sh.employeeId,e.name,e.type,p.level,p.age,p.ageGroup,sh.restaurant||'Unclassified',sh.category||'Unclassified',sh.date,p.dayType,sh.start,sh.end,sh.breakMinutes,decimal(p.scheduledMinutes/60),'AUD',p.rateCents===null?'':(p.rateCents/100).toFixed(2),p.estimatedCents===null?payrollStatus(p.issues).label:(p.estimatedCents/100).toFixed(2),sh.actual?.start,sh.actual?.end,sh.actual?.breakMinutes,sh.actual?decimal(p.actualMinutes/60):'',!sh.actual?'':p.actualCents===null?payrollStatus(p.issues).label:(p.actualCents/100).toFixed(2),p.issues.join('; ')||'Calculated',payRateVersion.effectiveFrom,'Current employee profile; age on shift date; round each shift to cents; excludes tax, super, overtime, allowances and leave payments',/\.(example|invalid)$/i.test(e.email)?'MOCK':'Live'];
 })]);
}
