import {checkWorkspaceRevision} from '@/lib/live-store';
import {googleJson,localRequest,session} from '@/lib/google-auth';
import {exclusive,loadLive,saveLive} from '@/lib/live-store';
import {startAvailabilityCollection,addCollectionGroup,collectionGroup,saveGroupSettings,availabilityState,saveAvailabilitySettings,prepareAvailabilityWeek,sendAvailabilityWeek} from '@/lib/availability';
import {startCollector,trackAvailabilityResponses} from '@/lib/google-workflow';
export const runtime='nodejs';
export const dynamic='force-dynamic';
export async function POST(request:Request){try{localRequest(request,true);const c=session(request);const f=await request.formData(),field=(key:string)=>String(f.get(key)||'').trim();return await exclusive(async()=>{if(session(request).email!==c.email)throw Error('Google account changed.');const s=loadLive(c.email);checkWorkspaceRevision(request,s);startCollector();switch(field('action')){
 case 'add-group':addCollectionGroup(s,c.email,field('employeeGroupId'),(field('restaurant')||undefined) as import('@/lib/shift-templates').Restaurant|undefined,field('department')||undefined);break;
 case 'group-settings':if(field('enabled')==='yes'&&field('confirmWeekly')!=='yes')throw Error('Confirm weekly real email delivery.');saveGroupSettings(s,c.email,field('group'),{employeeIds:JSON.parse(field('employeeIds')),timezone:'Etc/GMT-10',sendTime:field('sendTime'),sendDay:field('sendDay')===''?4:Number(field('sendDay')),enabled:field('enabled')==='yes',openHour:field('openHour')===''?-1:Number(field('openHour')),closeHour:field('closeHour')===''?-1:Number(field('closeHour'))},field('formSource'));break;
 case 'remove-sample':{const t=availabilityState(s);t.weeks=t.weeks.filter(w=>!(w.id===field('id')&&w.sample));saveLive(c.email,s);break;}
 case 'custom-form':{const raw=field('formUrl');let id='';try{const url=new URL(raw);if(url.protocol!=='https:'||!['docs.google.com','drive.google.com'].includes(url.hostname))throw Error();id=url.pathname.match(/^\/forms\/d\/(?!e\/)([\w-]+)/)?.[1]||url.pathname.match(/^\/file\/d\/([\w-]+)/)?.[1]||url.searchParams.get('id')||'';}catch{throw Error('Paste the Google Form editor link or its Google Drive file link.');}if(!/^[\w-]+$/.test(id))throw Error('Use the editor link (forms/d/FORM_ID/edit), not the shortened or responder link.');const file=await googleJson<{id:string;name:string;mimeType:string;trashed?:boolean}>('https://www.googleapis.com/drive/v3/files/'+id+'?fields=id,name,mimeType,trashed');if(file.mimeType!=='application/vnd.google-apps.form'||file.trashed)throw Error('Select an accessible Google Form in Drive.');const target=field('group')?collectionGroup(s,field('group')):availabilityState(s);if(field('group')&&Object.entries(availabilityState(s).groups||{}).some(([key,g])=>key!==field('group')&&g?.customForm?.id===file.id&&!(('profileRecipients' in target)&&target.profileRecipients&&!g.profileRecipients&&!g.settings.enabled)))throw Error('Use a different Google Form for each group.');if('formSource' in target)target.formSource='custom';target.customForm={id:file.id,name:file.name,url:'https://docs.google.com/forms/d/'+file.id+'/edit',savedAt:new Date().toISOString()};saveLive(c.email,s);break;}
 case 'remove-custom-form':{const target=field('group')?collectionGroup(s,field('group')):availabilityState(s);target.customForm=undefined;target.settings.enabled=false;saveLive(c.email,s);break;}
 case 'settings':if(field('enabled')==='yes'&&field('confirmWeekly')!=='yes')throw Error('Confirm weekly real email delivery.');saveAvailabilitySettings(s,c.email,{employeeIds:JSON.parse(field('employeeIds')),timezone:'Etc/GMT-10',sendTime:field('sendTime'),sendDay:field('sendDay')===''?4:Number(field('sendDay')),enabled:field('enabled')==='yes',openHour:8,closeHour:20});break;
 case 'start':await startAvailabilityCollection(s,c.email,field('weekStart'),field('group'),field('confirmLive')==='yes');break;
 case 'prepare':if(field('group'))collectionGroup(s,field('group'));await prepareAvailabilityWeek(s,c.email,field('weekStart'),field('group')||undefined);break;
 case 'send':case 'retry':if(field('confirmLive')!=='yes')throw Error('Confirm sending this week’s form by real Gmail.');await sendAvailabilityWeek(s,c.email,field('id'),field('action')==='retry');break;
 case 'collect':await trackAvailabilityResponses(s,c.email);break;
 default:throw Error('Unsupported availability action.');}return Response.json(s,{headers:{'Cache-Control':'no-store'}})})}catch(e){return Response.json({error:(e as Error).message},{status:400})}}
